<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Default="None" Version="0.1" State="modified">
  <DEFINITION Label="none" Value="None"/>
  <DEFINITION Label="SC" Value="SC"/>
  <DEFINITION Label="SCA" Value="SCA"/>
  <DEFINITION Label="SCAH" Value="SCAH"/>
  <DEFINITION Label="SCAHB" Value="SCAHB"/>
  <DEFINITION Label="SCAHBE" Value="SCAHBE"/>
  <DEFINITION Label="SCAHBEM" Value="SCAHBEM"/>
  <DEFINITION Label="SCAHG" Value="SCAHG"/>
  <DEFINITION Label="SCAHGE" Value="SCAHGE"/>
  <DEFINITION Label="SCAHGEM" Value="SCAHGEM"/>
  <DEFINITION Label="SCAHH" Value="SCAHH"/>
  <DEFINITION Label="SCAHHE" Value="SCAHHE"/>
  <DEFINITION Label="SCAHHEM" Value="SCAHHEM"/>
  <DEFINITION Label="SCAHP" Value="SCAHP"/>
  <DEFINITION Label="SCAHPE" Value="SCAHPE"/>
  <DEFINITION Label="SCAHPEM" Value="SCAHPEM"/>
  <DEFINITION Label="SCAHS" Value="SCAHS"/>
  <DEFINITION Label="SCAHSE" Value="SCAHSE"/>
  <DEFINITION Label="SCAHSEM" Value="SCAHSEM"/>
  <DEFINITION Label="SCAHV" Value="SCAHV"/>
  <DEFINITION Label="SCAHVE" Value="SCAHVE"/>
  <DEFINITION Label="SCAHVEM" Value="SCAHVEM"/>
  <DEFINITION Label="SCAL" Value="SCAL"/>
  <DEFINITION Label="SCALB" Value="SCALB"/>
  <DEFINITION Label="SCALBE" Value="SCALBE"/>
  <DEFINITION Label="SCALBEM" Value="SCALBEM"/>
  <DEFINITION Label="SCALG" Value="SCALG"/>
  <DEFINITION Label="SCALGE" Value="SCALGE"/>
  <DEFINITION Label="SCALGEM" Value="SCALGEM"/>
  <DEFINITION Label="SCALP" Value="SCALP"/>
  <DEFINITION Label="SCALPE" Value="SCALPE"/>
  <DEFINITION Label="SCALPEM" Value="SCALPEM"/>
  <DEFINITION Label="SCALS" Value="SCALS"/>
  <DEFINITION Label="SCALSE" Value="SCALSE"/>
  <DEFINITION Label="SCALSEM" Value="SCALSEM"/>
  <DEFINITION Label="SCALV" Value="SCALV"/>
  <DEFINITION Label="SCALVE" Value="SCALVE"/>
  <DEFINITION Label="SCALVEM" Value="SCALVEM"/>
  <DEFINITION Label="SCAM" Value="SCAM"/>
  <DEFINITION Label="SCAMB" Value="SCAMB"/>
  <DEFINITION Label="SCAMBE" Value="SCAMBE"/>
  <DEFINITION Label="SCAMBEM" Value="SCAMBEM"/>
  <DEFINITION Label="SCAMG" Value="SCAMG"/>
  <DEFINITION Label="SCAMGE" Value="SCAMGE"/>
  <DEFINITION Label="SCAMGEM" Value="SCAMGEM"/>
  <DEFINITION Label="SCAMP" Value="SCAMP"/>
  <DEFINITION Label="SCAMPE" Value="SCAMPE"/>
  <DEFINITION Label="SCAMPEM" Value="SCAMPEM"/>
  <DEFINITION Label="SCAMS" Value="SCAMS"/>
  <DEFINITION Label="SCAMSE" Value="SCAMSE"/>
  <DEFINITION Label="SCAMSEM" Value="SCAMSEM"/>
  <DEFINITION Label="SCAMV" Value="SCAMV"/>
  <DEFINITION Label="SCAMVE" Value="SCAMVE"/>
  <DEFINITION Label="SCAMVEM" Value="SCAMVEM"/>
  <DEFINITION Label="SCAS" Value="SCAS"/>
  <DEFINITION Label="SCASB" Value="SCASB"/>
  <DEFINITION Label="SCASBE" Value="SCASBE"/>
  <DEFINITION Label="SCASBEM" Value="SCASBEM"/>
  <DEFINITION Label="SCASS" Value="SCASS"/>
  <DEFINITION Label="SCASSE" Value="SCASSE"/>
  <DEFINITION Label="SCASSEM" Value="SCASSEM"/>
  <DEFINITION Label="SCJ" Value="SCJ"/>
  <DEFINITION Label="SCJA" Value="SCJA"/>
  <DEFINITION Label="SCJAA" Value="SCJAA"/>
  <DEFINITION Label="SCJAAE" Value="SCJAAE"/>
  <DEFINITION Label="SCJAAEM" Value="SCJAAEM"/>
  <DEFINITION Label="SCJB" Value="SCJB"/>
  <DEFINITION Label="SCJBA" Value="SCJBA"/>
  <DEFINITION Label="SCJBAE" Value="SCJBAE"/>
  <DEFINITION Label="SCJBAEM" Value="SCJBAEM"/>
  <DEFINITION Label="SCJD" Value="SCJD"/>
  <DEFINITION Label="SCJDA" Value="SCJDA"/>
  <DEFINITION Label="SCJDAE" Value="SCJDAE"/>
  <DEFINITION Label="SCJDAEM" Value="SCJDAEM"/>
  <DEFINITION Label="SCJE" Value="SCJE"/>
  <DEFINITION Label="SCJEA" Value="SCJEA"/>
  <DEFINITION Label="SCJEAE" Value="SCJEAE"/>
  <DEFINITION Label="SCJEAEM" Value="SCJEAEM"/>
  <DEFINITION Label="SCJP" Value="SCJP"/>
  <DEFINITION Label="SCJPA" Value="SCJPA"/>
  <DEFINITION Label="SCJPAE" Value="SCJPAE"/>
  <DEFINITION Label="SCJPAEM" Value="SCJPAEM"/>
  <DEFINITION Label="SCJR" Value="SCJR"/>
  <DEFINITION Label="SCJRA" Value="SCJRA"/>
  <DEFINITION Label="SCJRAE" Value="SCJRAE"/>
  <DEFINITION Label="SCJRAEM" Value="SCJRAEM"/>
  <DEFINITION Label="SCM" Value="SCM"/>
  <DEFINITION Label="SCM1" Value="SCM1"/>
  <DEFINITION Label="SCM1A" Value="SCM1A"/>
  <DEFINITION Label="SCM1AE" Value="SCM1AE"/>
  <DEFINITION Label="SCM1AEM" Value="SCM1AEM"/>
  <DEFINITION Label="SCM1D" Value="SCM1D"/>
  <DEFINITION Label="SCM1DE" Value="SCM1DE"/>
  <DEFINITION Label="SCM1DEM" Value="SCM1DEM"/>
  <DEFINITION Label="SCM1M" Value="SCM1M"/>
  <DEFINITION Label="SCM1ME" Value="SCM1ME"/>
  <DEFINITION Label="SCM1MEM" Value="SCM1MEM"/>
  <DEFINITION Label="SCM1P" Value="SCM1P"/>
  <DEFINITION Label="SCM1PE" Value="SCM1PE"/>
  <DEFINITION Label="SCM1PEM" Value="SCM1PEM"/>
  <DEFINITION Label="SCM1S" Value="SCM1S"/>
  <DEFINITION Label="SCM1SE" Value="SCM1SE"/>
  <DEFINITION Label="SCM1SEM" Value="SCM1SEM"/>
  <DEFINITION Label="SCM1T" Value="SCM1T"/>
  <DEFINITION Label="SCM1TE" Value="SCM1TE"/>
  <DEFINITION Label="SCM1TEM" Value="SCM1TEM"/>
  <DEFINITION Label="SCM2" Value="SCM2"/>
  <DEFINITION Label="SCM2A" Value="SCM2A"/>
  <DEFINITION Label="SCM2AE" Value="SCM2AE"/>
  <DEFINITION Label="SCM2AEM" Value="SCM2AEM"/>
  <DEFINITION Label="SCM2M" Value="SCM2M"/>
  <DEFINITION Label="SCM2ME" Value="SCM2ME"/>
  <DEFINITION Label="SCM2MEM" Value="SCM2MEM"/>
  <DEFINITION Label="SCM2P" Value="SCM2P"/>
  <DEFINITION Label="SCM2PE" Value="SCM2PE"/>
  <DEFINITION Label="SCM2PEM" Value="SCM2PEM"/>
  <DEFINITION Label="SCM2S" Value="SCM2S"/>
  <DEFINITION Label="SCM2SE" Value="SCM2SE"/>
  <DEFINITION Label="SCM2SEM" Value="SCM2SEM"/>
  <DEFINITION Label="SCMC" Value="SCMC"/>
  <DEFINITION Label="SCMCA" Value="SCMCA"/>
  <DEFINITION Label="SCMCAE" Value="SCMCAE"/>
  <DEFINITION Label="SCMCAEM" Value="SCMCAEM"/>
  <DEFINITION Label="SCR" Value="SCR"/>
  <DEFINITION Label="SCR1" Value="SCR1"/>
  <DEFINITION Label="SCR1P" Value="SCR1P"/>
  <DEFINITION Label="SCR1PE" Value="SCR1PE"/>
  <DEFINITION Label="SCR1PEM" Value="SCR1PEM"/>
  <DEFINITION Label="SCR2" Value="SCR2"/>
  <DEFINITION Label="SCR2A" Value="SCR2A"/>
  <DEFINITION Label="SCR2AE" Value="SCR2AE"/>
  <DEFINITION Label="SCR2AEM" Value="SCR2AEM"/>
  <DEFINITION Label="SCR2L" Value="SCR2L"/>
  <DEFINITION Label="SCR2LE" Value="SCR2LE"/>
  <DEFINITION Label="SCR2LEM" Value="SCR2LEM"/>
  <DEFINITION Label="SCR2R" Value="SCR2R"/>
  <DEFINITION Label="SCR2RE" Value="SCR2RE"/>
  <DEFINITION Label="SCR2REM" Value="SCR2REM"/>
</TYPE>
