<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Default="None" Version="0.1" State="modified">
  <DEFINITION Label="none" Value="None"/>
  <DEFINITION Label="SD" Value="SD"/>
  <DEFINITION Label="SDA" Value="SDA"/>
  <DEFINITION Label="SDAH" Value="SDAH"/>
  <DEFINITION Label="SDAHF" Value="SDAHF"/>
  <DEFINITION Label="SDAHFA" Value="SDAHFA"/>
  <DEFINITION Label="SDAHFAE" Value="SDAHFAE"/>
  <DEFINITION Label="SDAHM" Value="SDAHM"/>
  <DEFINITION Label="SDAHMA" Value="SDAHMA"/>
  <DEFINITION Label="SDAHMAE" Value="SDAHMAE"/>
  <DEFINITION Label="SDAHT" Value="SDAHT"/>
  <DEFINITION Label="SDAHTA" Value="SDAHTA"/>
  <DEFINITION Label="SDAHTAE" Value="SDAHTAE"/>
  <DEFINITION Label="SDAHZ" Value="SDAHZ"/>
  <DEFINITION Label="SDAHZA" Value="SDAHZA"/>
  <DEFINITION Label="SDAHZAE" Value="SDAHZAE"/>
  <DEFINITION Label="SDAL" Value="SDAL"/>
  <DEFINITION Label="SDALF" Value="SDALF"/>
  <DEFINITION Label="SDALFA" Value="SDALFA"/>
  <DEFINITION Label="SDALFAE" Value="SDALFAE"/>
  <DEFINITION Label="SDALM" Value="SDALM"/>
  <DEFINITION Label="SDALMA" Value="SDALMA"/>
  <DEFINITION Label="SDALMAE" Value="SDALMAE"/>
  <DEFINITION Label="SDALT" Value="SDALT"/>
  <DEFINITION Label="SDALTA" Value="SDALTA"/>
  <DEFINITION Label="SDALTAE" Value="SDALTAE"/>
  <DEFINITION Label="SDALZ" Value="SDALZ"/>
  <DEFINITION Label="SDALZA" Value="SDALZA"/>
  <DEFINITION Label="SDALZAE" Value="SDALZAE"/>
  <DEFINITION Label="SDAM" Value="SDAM"/>
  <DEFINITION Label="SDAMF" Value="SDAMF"/>
  <DEFINITION Label="SDAMFA" Value="SDAMFA"/>
  <DEFINITION Label="SDAMFAE" Value="SDAMFAE"/>
  <DEFINITION Label="SDAMM" Value="SDAMM"/>
  <DEFINITION Label="SDAMMA" Value="SDAMMA"/>
  <DEFINITION Label="SDAMMAE" Value="SDAMMAE"/>
  <DEFINITION Label="SDAMT" Value="SDAMT"/>
  <DEFINITION Label="SDAMTA" Value="SDAMTA"/>
  <DEFINITION Label="SDAMTAE" Value="SDAMTAE"/>
  <DEFINITION Label="SDAMZ" Value="SDAMZ"/>
  <DEFINITION Label="SDAMZA" Value="SDAMZA"/>
  <DEFINITION Label="SDAMZAE" Value="SDAMZAE"/>
  <DEFINITION Label="SDD" Value="SDD"/>
  <DEFINITION Label="SDDA" Value="SDDA"/>
  <DEFINITION Label="SDDAT" Value="SDDAT"/>
  <DEFINITION Label="SDDATM" Value="SDDATM"/>
  <DEFINITION Label="SDDATME" Value="SDDATME"/>
  <DEFINITION Label="SDS" Value="SDS"/>
  <DEFINITION Label="SDSB" Value="SDSB"/>
  <DEFINITION Label="SDSBF" Value="SDSBF"/>
  <DEFINITION Label="SDSBFA" Value="SDSBFA"/>
  <DEFINITION Label="SDSBFAE" Value="SDSBFAE"/>
  <DEFINITION Label="SDSBM" Value="SDSBM"/>
  <DEFINITION Label="SDSBMA" Value="SDSBMA"/>
  <DEFINITION Label="SDSBMAE" Value="SDSBMAE"/>
  <DEFINITION Label="SDSBT" Value="SDSBT"/>
  <DEFINITION Label="SDSBTA" Value="SDSBTA"/>
  <DEFINITION Label="SDSBTAE" Value="SDSBTAE"/>
  <DEFINITION Label="SDSBZ" Value="SDSBZ"/>
  <DEFINITION Label="SDSBZA" Value="SDSBZA"/>
  <DEFINITION Label="SDSBZAE" Value="SDSBZAE"/>
  <DEFINITION Label="SDSS" Value="SDSS"/>
  <DEFINITION Label="SDSSF" Value="SDSSF"/>
  <DEFINITION Label="SDSSFA" Value="SDSSFA"/>
  <DEFINITION Label="SDSSFAE" Value="SDSSFAE"/>
  <DEFINITION Label="SDSSM" Value="SDSSM"/>
  <DEFINITION Label="SDSSMA" Value="SDSSMA"/>
  <DEFINITION Label="SDSSMAE" Value="SDSSMAE"/>
  <DEFINITION Label="SDSST" Value="SDSST"/>
  <DEFINITION Label="SDSSTA" Value="SDSSTA"/>
  <DEFINITION Label="SDSSTAE" Value="SDSSTAE"/>
  <DEFINITION Label="SDSSZ" Value="SDSSZ"/>
  <DEFINITION Label="SDSSZA" Value="SDSSZA"/>
  <DEFINITION Label="SDSSZAE" Value="SDSSZAE"/>
</TYPE>
