<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Default="None" Version="0.1" State="modified">
  <DEFINITION Label="none" Value="None"/>
  <DEFINITION Label="SF" Value="SF"/>
  <DEFINITION Label="SFM" Value="SFM"/>
  <DEFINITION Label="SFM1" Value="SFM1"/>
  <DEFINITION Label="SFM1B" Value="SFM1B"/>
  <DEFINITION Label="SFM1BM" Value="SFM1BM"/>
  <DEFINITION Label="SFM1BMM" Value="SFM1BMM"/>
  <DEFINITION Label="SFM1BS" Value="SFM1BS"/>
  <DEFINITION Label="SFM1BSM" Value="SFM1BSM"/>
  <DEFINITION Label="SFM1P" Value="SFM1P"/>
  <DEFINITION Label="SFM1PS" Value="SFM1PS"/>
  <DEFINITION Label="SFM1PSM" Value="SFM1PSM"/>
  <DEFINITION Label="SFM1S" Value="SFM1S"/>
  <DEFINITION Label="SFM1SA" Value="SFM1SA"/>
  <DEFINITION Label="SFM1SAM" Value="SFM1SAM"/>
  <DEFINITION Label="SFM1SS" Value="SFM1SS"/>
  <DEFINITION Label="SFM1SSM" Value="SFM1SSM"/>
  <DEFINITION Label="SFM2" Value="SFM2"/>
  <DEFINITION Label="SFM2B" Value="SFM2B"/>
  <DEFINITION Label="SFM2BM" Value="SFM2BM"/>
  <DEFINITION Label="SFM2BMM" Value="SFM2BMM"/>
  <DEFINITION Label="SFM2P" Value="SFM2P"/>
  <DEFINITION Label="SFM2PP" Value="SFM2PP"/>
  <DEFINITION Label="SFM2PPM" Value="SFM2PPM"/>
  <DEFINITION Label="SFM2S" Value="SFM2S"/>
  <DEFINITION Label="SFM2SA" Value="SFM2SA"/>
  <DEFINITION Label="SFM2SAM" Value="SFM2SAM"/>
  <DEFINITION Label="SFM2SS" Value="SFM2SS"/>
  <DEFINITION Label="SFM2SSM" Value="SFM2SSM"/>
  <DEFINITION Label="SFMC" Value="SFMC"/>
  <DEFINITION Label="SFMCA" Value="SFMCA"/>
  <DEFINITION Label="SFMCAD" Value="SFMCAD"/>
  <DEFINITION Label="SFMCADM" Value="SFMCADM"/>
  <DEFINITION Label="SFMCAH" Value="SFMCAH"/>
  <DEFINITION Label="SFMCAHM" Value="SFMCAHM"/>
  <DEFINITION Label="SFR" Value="SFR"/>
  <DEFINITION Label="SFR1" Value="SFR1"/>
  <DEFINITION Label="SFR1A" Value="SFR1A"/>
  <DEFINITION Label="SFR1AP" Value="SFR1AP"/>
  <DEFINITION Label="SFR1APM" Value="SFR1APM"/>
  <DEFINITION Label="SFR2" Value="SFR2"/>
  <DEFINITION Label="SFR2A" Value="SFR2A"/>
  <DEFINITION Label="SFR2AA" Value="SFR2AA"/>
  <DEFINITION Label="SFR2AAM" Value="SFR2AAM"/>
  <DEFINITION Label="SFR2AL" Value="SFR2AL"/>
  <DEFINITION Label="SFR2ALM" Value="SFR2ALM"/>
  <DEFINITION Label="SFR2AR" Value="SFR2AR"/>
  <DEFINITION Label="SFR2ARM" Value="SFR2ARM"/>
</TYPE>
