<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Default="None" Version="0.1" State="modified">
  <DEFINITION Label="none" Value="None"/>
  <DEFINITION Label="SC" Value="SC"/>
  <DEFINITION Label="SCA" Value="SCA"/>
  <DEFINITION Label="SCAH" Value="SCAH"/>
  <DEFINITION Label="SCAHB" Value="SCAHB"/>
  <DEFINITION Label="SCAHBE" Value="SCAHBE"/>
  <DEFINITION Label="SCAHBEM" Value="SCAHBEM"/>
  <DEFINITION Label="SCAHG" Value="SCAHG"/>
  <DEFINITION Label="SCAHGE" Value="SCAHGE"/>
  <DEFINITION Label="SCAHGEM" Value="SCAHGEM"/>
  <DEFINITION Label="SCAHH" Value="SCAHH"/>
  <DEFINITION Label="SCAHHE" Value="SCAHHE"/>
  <DEFINITION Label="SCAHHEM" Value="SCAHHEM"/>
  <DEFINITION Label="SCAHP" Value="SCAHP"/>
  <DEFINITION Label="SCAHPE" Value="SCAHPE"/>
  <DEFINITION Label="SCAHPEM" Value="SCAHPEM"/>
  <DEFINITION Label="SCAHS" Value="SCAHS"/>
  <DEFINITION Label="SCAHSE" Value="SCAHSE"/>
  <DEFINITION Label="SCAHSEM" Value="SCAHSEM"/>
  <DEFINITION Label="SCAHV" Value="SCAHV"/>
  <DEFINITION Label="SCAHVE" Value="SCAHVE"/>
  <DEFINITION Label="SCAHVEM" Value="SCAHVEM"/>
  <DEFINITION Label="SCAL" Value="SCAL"/>
  <DEFINITION Label="SCALB" Value="SCALB"/>
  <DEFINITION Label="SCALBE" Value="SCALBE"/>
  <DEFINITION Label="SCALBEM" Value="SCALBEM"/>
  <DEFINITION Label="SCALG" Value="SCALG"/>
  <DEFINITION Label="SCALGE" Value="SCALGE"/>
  <DEFINITION Label="SCALGEM" Value="SCALGEM"/>
  <DEFINITION Label="SCALP" Value="SCALP"/>
  <DEFINITION Label="SCALPE" Value="SCALPE"/>
  <DEFINITION Label="SCALPEM" Value="SCALPEM"/>
  <DEFINITION Label="SCALS" Value="SCALS"/>
  <DEFINITION Label="SCALSE" Value="SCALSE"/>
  <DEFINITION Label="SCALSEM" Value="SCALSEM"/>
  <DEFINITION Label="SCALV" Value="SCALV"/>
  <DEFINITION Label="SCALVE" Value="SCALVE"/>
  <DEFINITION Label="SCALVEM" Value="SCALVEM"/>
  <DEFINITION Label="SCAM" Value="SCAM"/>
  <DEFINITION Label="SCAMB" Value="SCAMB"/>
  <DEFINITION Label="SCAMBE" Value="SCAMBE"/>
  <DEFINITION Label="SCAMBEM" Value="SCAMBEM"/>
  <DEFINITION Label="SCAMG" Value="SCAMG"/>
  <DEFINITION Label="SCAMGE" Value="SCAMGE"/>
  <DEFINITION Label="SCAMGEM" Value="SCAMGEM"/>
  <DEFINITION Label="SCAMP" Value="SCAMP"/>
  <DEFINITION Label="SCAMPE" Value="SCAMPE"/>
  <DEFINITION Label="SCAMPEM" Value="SCAMPEM"/>
  <DEFINITION Label="SCAMS" Value="SCAMS"/>
  <DEFINITION Label="SCAMSE" Value="SCAMSE"/>
  <DEFINITION Label="SCAMSEM" Value="SCAMSEM"/>
  <DEFINITION Label="SCAMV" Value="SCAMV"/>
  <DEFINITION Label="SCAMVE" Value="SCAMVE"/>
  <DEFINITION Label="SCAMVEM" Value="SCAMVEM"/>
  <DEFINITION Label="SCAS" Value="SCAS"/>
  <DEFINITION Label="SCASB" Value="SCASB"/>
  <DEFINITION Label="SCASBE" Value="SCASBE"/>
  <DEFINITION Label="SCASBEM" Value="SCASBEM"/>
  <DEFINITION Label="SCASS" Value="SCASS"/>
  <DEFINITION Label="SCASSE" Value="SCASSE"/>
  <DEFINITION Label="SCASSEM" Value="SCASSEM"/>
  <DEFINITION Label="SCJ" Value="SCJ"/>
  <DEFINITION Label="SCJA" Value="SCJA"/>
  <DEFINITION Label="SCJAA" Value="SCJAA"/>
  <DEFINITION Label="SCJAAE" Value="SCJAAE"/>
  <DEFINITION Label="SCJAAEM" Value="SCJAAEM"/>
  <DEFINITION Label="SCJB" Value="SCJB"/>
  <DEFINITION Label="SCJBA" Value="SCJBA"/>
  <DEFINITION Label="SCJBAE" Value="SCJBAE"/>
  <DEFINITION Label="SCJBAEM" Value="SCJBAEM"/>
  <DEFINITION Label="SCJD" Value="SCJD"/>
  <DEFINITION Label="SCJDA" Value="SCJDA"/>
  <DEFINITION Label="SCJDAE" Value="SCJDAE"/>
  <DEFINITION Label="SCJDAEM" Value="SCJDAEM"/>
  <DEFINITION Label="SCJE" Value="SCJE"/>
  <DEFINITION Label="SCJEA" Value="SCJEA"/>
  <DEFINITION Label="SCJEAE" Value="SCJEAE"/>
  <DEFINITION Label="SCJEAEM" Value="SCJEAEM"/>
  <DEFINITION Label="SCJP" Value="SCJP"/>
  <DEFINITION Label="SCJPA" Value="SCJPA"/>
  <DEFINITION Label="SCJPAE" Value="SCJPAE"/>
  <DEFINITION Label="SCJPAEM" Value="SCJPAEM"/>
  <DEFINITION Label="SCJR" Value="SCJR"/>
  <DEFINITION Label="SCJRA" Value="SCJRA"/>
  <DEFINITION Label="SCJRAE" Value="SCJRAE"/>
  <DEFINITION Label="SCJRAEM" Value="SCJRAEM"/>
  <DEFINITION Label="SCM" Value="SCM"/>
  <DEFINITION Label="SCM1" Value="SCM1"/>
  <DEFINITION Label="SCM1A" Value="SCM1A"/>
  <DEFINITION Label="SCM1AE" Value="SCM1AE"/>
  <DEFINITION Label="SCM1AEM" Value="SCM1AEM"/>
  <DEFINITION Label="SCM1D" Value="SCM1D"/>
  <DEFINITION Label="SCM1DE" Value="SCM1DE"/>
  <DEFINITION Label="SCM1DEM" Value="SCM1DEM"/>
  <DEFINITION Label="SCM1M" Value="SCM1M"/>
  <DEFINITION Label="SCM1ME" Value="SCM1ME"/>
  <DEFINITION Label="SCM1MEM" Value="SCM1MEM"/>
  <DEFINITION Label="SCM1P" Value="SCM1P"/>
  <DEFINITION Label="SCM1PE" Value="SCM1PE"/>
  <DEFINITION Label="SCM1PEM" Value="SCM1PEM"/>
  <DEFINITION Label="SCM1S" Value="SCM1S"/>
  <DEFINITION Label="SCM1SE" Value="SCM1SE"/>
  <DEFINITION Label="SCM1SEM" Value="SCM1SEM"/>
  <DEFINITION Label="SCM1T" Value="SCM1T"/>
  <DEFINITION Label="SCM1TE" Value="SCM1TE"/>
  <DEFINITION Label="SCM1TEM" Value="SCM1TEM"/>
  <DEFINITION Label="SCM2" Value="SCM2"/>
  <DEFINITION Label="SCM2A" Value="SCM2A"/>
  <DEFINITION Label="SCM2AE" Value="SCM2AE"/>
  <DEFINITION Label="SCM2AEM" Value="SCM2AEM"/>
  <DEFINITION Label="SCM2M" Value="SCM2M"/>
  <DEFINITION Label="SCM2ME" Value="SCM2ME"/>
  <DEFINITION Label="SCM2MEM" Value="SCM2MEM"/>
  <DEFINITION Label="SCM2P" Value="SCM2P"/>
  <DEFINITION Label="SCM2PE" Value="SCM2PE"/>
  <DEFINITION Label="SCM2PEM" Value="SCM2PEM"/>
  <DEFINITION Label="SCM2S" Value="SCM2S"/>
  <DEFINITION Label="SCM2SE" Value="SCM2SE"/>
  <DEFINITION Label="SCM2SEM" Value="SCM2SEM"/>
  <DEFINITION Label="SCMC" Value="SCMC"/>
  <DEFINITION Label="SCMCA" Value="SCMCA"/>
  <DEFINITION Label="SCMCAE" Value="SCMCAE"/>
  <DEFINITION Label="SCMCAEM" Value="SCMCAEM"/>
  <DEFINITION Label="SCR" Value="SCR"/>
  <DEFINITION Label="SCR1" Value="SCR1"/>
  <DEFINITION Label="SCR1P" Value="SCR1P"/>
  <DEFINITION Label="SCR1PE" Value="SCR1PE"/>
  <DEFINITION Label="SCR1PEM" Value="SCR1PEM"/>
  <DEFINITION Label="SCR2" Value="SCR2"/>
  <DEFINITION Label="SCR2A" Value="SCR2A"/>
  <DEFINITION Label="SCR2AE" Value="SCR2AE"/>
  <DEFINITION Label="SCR2AEM" Value="SCR2AEM"/>
  <DEFINITION Label="SCR2L" Value="SCR2L"/>
  <DEFINITION Label="SCR2LE" Value="SCR2LE"/>
  <DEFINITION Label="SCR2LEM" Value="SCR2LEM"/>
  <DEFINITION Label="SCR2R" Value="SCR2R"/>
  <DEFINITION Label="SCR2RE" Value="SCR2RE"/>
  <DEFINITION Label="SCR2REM" Value="SCR2REM"/>
  <DEFINITION Label="SF" Value="SF"/>
  <DEFINITION Label="SFM" Value="SFM"/>
  <DEFINITION Label="SFM1" Value="SFM1"/>
  <DEFINITION Label="SFM1B" Value="SFM1B"/>
  <DEFINITION Label="SFM1BM" Value="SFM1BM"/>
  <DEFINITION Label="SFM1BMM" Value="SFM1BMM"/>
  <DEFINITION Label="SFM1BS" Value="SFM1BS"/>
  <DEFINITION Label="SFM1BSM" Value="SFM1BSM"/>
  <DEFINITION Label="SFM1P" Value="SFM1P"/>
  <DEFINITION Label="SFM1PS" Value="SFM1PS"/>
  <DEFINITION Label="SFM1PSM" Value="SFM1PSM"/>
  <DEFINITION Label="SFM1S" Value="SFM1S"/>
  <DEFINITION Label="SFM1SA" Value="SFM1SA"/>
  <DEFINITION Label="SFM1SAM" Value="SFM1SAM"/>
  <DEFINITION Label="SFM1SS" Value="SFM1SS"/>
  <DEFINITION Label="SFM1SSM" Value="SFM1SSM"/>
  <DEFINITION Label="SFM2" Value="SFM2"/>
  <DEFINITION Label="SFM2B" Value="SFM2B"/>
  <DEFINITION Label="SFM2BM" Value="SFM2BM"/>
  <DEFINITION Label="SFM2BMM" Value="SFM2BMM"/>
  <DEFINITION Label="SFM2P" Value="SFM2P"/>
  <DEFINITION Label="SFM2PP" Value="SFM2PP"/>
  <DEFINITION Label="SFM2PPM" Value="SFM2PPM"/>
  <DEFINITION Label="SFM2S" Value="SFM2S"/>
  <DEFINITION Label="SFM2SA" Value="SFM2SA"/>
  <DEFINITION Label="SFM2SAM" Value="SFM2SAM"/>
  <DEFINITION Label="SFM2SS" Value="SFM2SS"/>
  <DEFINITION Label="SFM2SSM" Value="SFM2SSM"/>
  <DEFINITION Label="SFMC" Value="SFMC"/>
  <DEFINITION Label="SFMCA" Value="SFMCA"/>
  <DEFINITION Label="SFMCAD" Value="SFMCAD"/>
  <DEFINITION Label="SFMCADM" Value="SFMCADM"/>
  <DEFINITION Label="SFMCAH" Value="SFMCAH"/>
  <DEFINITION Label="SFMCAHM" Value="SFMCAHM"/>
  <DEFINITION Label="SFR" Value="SFR"/>
  <DEFINITION Label="SFR1" Value="SFR1"/>
  <DEFINITION Label="SFR1A" Value="SFR1A"/>
  <DEFINITION Label="SFR1AP" Value="SFR1AP"/>
  <DEFINITION Label="SFR1APM" Value="SFR1APM"/>
  <DEFINITION Label="SFR2" Value="SFR2"/>
  <DEFINITION Label="SFR2A" Value="SFR2A"/>
  <DEFINITION Label="SFR2AA" Value="SFR2AA"/>
  <DEFINITION Label="SFR2AAM" Value="SFR2AAM"/>
  <DEFINITION Label="SFR2AL" Value="SFR2AL"/>
  <DEFINITION Label="SFR2ALM" Value="SFR2ALM"/>
  <DEFINITION Label="SFR2AR" Value="SFR2AR"/>
  <DEFINITION Label="SFR2ARM" Value="SFR2ARM"/>
  <DEFINITION Label="SH" Value="SH"/>
  <DEFINITION Label="SHF" Value="SHF"/>
  <DEFINITION Label="SHFD" Value="SHFD"/>
  <DEFINITION Label="SHFDA" Value="SHFDA"/>
  <DEFINITION Label="SHFDAE" Value="SHFDAE"/>
  <DEFINITION Label="SHFDAEM" Value="SHFDAEM"/>
  <DEFINITION Label="SHFF" Value="SHFF"/>
  <DEFINITION Label="SHFFA" Value="SHFFA"/>
  <DEFINITION Label="SHFFAE" Value="SHFFAE"/>
  <DEFINITION Label="SHFFAEM" Value="SHFFAEM"/>
  <DEFINITION Label="SHFJ" Value="SHFJ"/>
  <DEFINITION Label="SHFJA" Value="SHFJA"/>
  <DEFINITION Label="SHFJAE" Value="SHFJAE"/>
  <DEFINITION Label="SHFJAEM" Value="SHFJAEM"/>
  <DEFINITION Label="SHFL" Value="SHFL"/>
  <DEFINITION Label="SHFLA" Value="SHFLA"/>
  <DEFINITION Label="SHFLAE" Value="SHFLAE"/>
  <DEFINITION Label="SHFLAEM" Value="SHFLAEM"/>
  <DEFINITION Label="SHFP" Value="SHFP"/>
  <DEFINITION Label="SHFPA" Value="SHFPA"/>
  <DEFINITION Label="SHFPAE" Value="SHFPAE"/>
  <DEFINITION Label="SHFPAEM" Value="SHFPAEM"/>
  <DEFINITION Label="SM" Value="SM"/>
  <DEFINITION Label="SMD" Value="SMD"/>
  <DEFINITION Label="SMDA" Value="SMDA"/>
  <DEFINITION Label="SMDAA" Value="SMDAA"/>
  <DEFINITION Label="SMDAAE" Value="SMDAAE"/>
  <DEFINITION Label="SMDAAEM" Value="SMDAAEM"/>
  <DEFINITION Label="SMDH" Value="SMDH"/>
  <DEFINITION Label="SMDHA" Value="SMDHA"/>
  <DEFINITION Label="SMDHAE" Value="SMDHAE"/>
  <DEFINITION Label="SMDHAEM" Value="SMDHAEM"/>
  <DEFINITION Label="SMO" Value="SMO"/>
  <DEFINITION Label="SMOA" Value="SMOA"/>
  <DEFINITION Label="SMOAA" Value="SMOAA"/>
  <DEFINITION Label="SMOAAE" Value="SMOAAE"/>
  <DEFINITION Label="SMOAAEM" Value="SMOAAEM"/>
  <DEFINITION Label="SMOE" Value="SMOE"/>
  <DEFINITION Label="SMOEA" Value="SMOEA"/>
  <DEFINITION Label="SMOEAE" Value="SMOEAE"/>
  <DEFINITION Label="SMOEAEM" Value="SMOEAEM"/>
</TYPE>
