<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Default="Refugee" Revision="$Revision: 1.22 $" State="modified">
  <DEFINITION Label="Refugee" Value="Refugee"/>
  <DEFINITION Label="Homin" Value="Homin"/>
  <DEFINITION Label="Novice_Artisan" Value="Novice_Artisan"/>
  <DEFINITION Label="Novice_Warrior" Value="Novice_Warrior"/>
  <DEFINITION Label="Novice_Harvester" Value="Novice_Harvester"/>
  <DEFINITION Label="Novice_Magician" Value="Novice_Magician"/>
  <DEFINITION Label="Artisan_Apprentice" Value="Artisan_Apprentice"/>
  <DEFINITION Label="Magician_Apprentice" Value="Magician_Apprentice"/>
  <DEFINITION Label="Fyros_Artisan_Apprentice" Value="Fyros_Artisan_Apprentice"/>
  <DEFINITION Label="Matis_Artisan_Apprentice" Value="Matis_Artisan_Apprentice"/>
  <DEFINITION Label="Tryker_Artisan_Apprentice" Value="Tryker_Artisan_Apprentice"/>
  <DEFINITION Label="Zorai_Artisan_Apprentice" Value="Zorai_Artisan_Apprentice"/>
  <DEFINITION Label="Melee_Warrior_Apprentice" Value="Melee_Warrior_Apprentice"/>
  <DEFINITION Label="Fyros_Armorer_Apprentice" Value="Fyros_Armorer_Apprentice"/>
  <DEFINITION Label="Fyros_Jeweler_Apprentice" Value="Fyros_Jeweler_Apprentice"/>
  <DEFINITION Label="Fyros_Weapon_Smith_Apprentice" Value="Fyros_Weapon_Smith_Apprentice"/>
  <DEFINITION Label="Fyros_Munitioner_Apprentice" Value="Fyros_Munitioner_Apprentice"/>
  <DEFINITION Label="Fyros_Gun_Smith_Apprentice" Value="Fyros_Gun_Smith_Apprentice"/>
  <DEFINITION Label="Fyros_Shield_Smith_Apprentice" Value="Fyros_Shield_Smith_Apprentice"/>
  <DEFINITION Label="Matis_Armorer_Apprentice" Value="Matis_Armorer_Apprentice"/>
  <DEFINITION Label="Matis_Jeweler_Apprentice" Value="Matis_Jeweler_Apprentice"/>
  <DEFINITION Label="Matis_Weapon_Smith_Apprentice" Value="Matis_Weapon_Smith_Apprentice"/>
  <DEFINITION Label="Matis_Munitioner_Apprentice" Value="Matis_Munitioner_Apprentice"/>
  <DEFINITION Label="Matis_Gun_Smith_Apprentice" Value="Matis_Gun_Smith_Apprentice"/>
  <DEFINITION Label="Matis_Shield_Smith_Apprentice" Value="Matis_Shield_Smith_Apprentice"/>
  <DEFINITION Label="Tryker_Armorer_Apprentice" Value="Tryker_Armorer_Apprentice"/>
  <DEFINITION Label="Tryker_Jeweler_Apprentice" Value="Tryker_Jeweler_Apprentice"/>
  <DEFINITION Label="Tryker_Weapon_Smith_Apprentice" Value="Tryker_Weapon_Smith_Apprentice"/>
  <DEFINITION Label="Tryker_Munitioner_Apprentice" Value="Tryker_Munitioner_Apprentice"/>
  <DEFINITION Label="Tryker_Gun_Smith_Apprentice" Value="Tryker_Gun_Smith_Apprentice"/>
  <DEFINITION Label="Tryker_Shield_Smith_Apprentice" Value="Tryker_Shield_Smith_Apprentice"/>
  <DEFINITION Label="Zorai_Armorer_Apprentice" Value="Zorai_Armorer_Apprentice"/>
  <DEFINITION Label="Zorai_Jeweler_Apprentice" Value="Zorai_Jeweler_Apprentice"/>
  <DEFINITION Label="Zorai_Weapon_Smith_Apprentice" Value="Zorai_Weapon_Smith_Apprentice"/>
  <DEFINITION Label="Zorai_Munitioner_Apprentice" Value="Zorai_Munitioner_Apprentice"/>
  <DEFINITION Label="Zorai_Gun_Smith_Apprentice" Value="Zorai_Gun_Smith_Apprentice"/>
  <DEFINITION Label="Zorai_Shield_Smith_Apprentice" Value="Zorai_Shield_Smith_Apprentice"/>
  <DEFINITION Label="Apprentice_Healer" Value="Apprentice_Healer"/>
  <DEFINITION Label="Defensive_Magician" Value="Defensive_Magician"/>
  <DEFINITION Label="Offensive_Magician" Value="Offensive_Magician"/>
  <DEFINITION Label="Mentalist" Value="Mentalist"/>
  <DEFINITION Label="Summoner" Value="Summoner"/>
  <DEFINITION Label="Master_Of_Illusion" Value="Master_Of_Illusion"/>
  <DEFINITION Label="Mind_Lord" Value="Mind_Lord"/>
  <DEFINITION Label="Healer" Value="Healer"/>
  <DEFINITION Label="Priest" Value="Priest"/>
  <DEFINITION Label="Master_Of_Life" Value="Master_Of_Life"/>
  <DEFINITION Label="Celestial_Guardian" Value="Celestial_Guardian"/>
  <DEFINITION Label="Disturber" Value="Disturber"/>
  <DEFINITION Label="Affliction_Bringer" Value="Affliction_Bringer"/>
  <DEFINITION Label="Master_Of_Torment" Value="Master_Of_Torment"/>
  <DEFINITION Label="Avatar_Of_Sorrow" Value="Avatar_Of_Sorrow"/>
  <DEFINITION Label="Destroyer" Value="Destroyer"/>
  <DEFINITION Label="Archmage" Value="Archmage"/>
  <DEFINITION Label="Master_Of_Pain" Value="Master_Of_Pain"/>
  <DEFINITION Label="Avatar_Of_Destruction" Value="Avatar_Of_Destruction"/>
  <DEFINITION Label="Elementalist" Value="Elementalist"/>
  <DEFINITION Label="Alchemist" Value="Alchemist"/>
  <DEFINITION Label="Biomancer" Value="Biomancer"/>
  <DEFINITION Label="Master_Of_Energies" Value="Master_Of_Energies"/>
  <DEFINITION Label="Chosen_Of_Atys" Value="Chosen_Of_Atys"/>
  <DEFINITION Label="Warrior_Apprentice" Value="Warrior_Apprentice"/>
  <DEFINITION Label="Melee_Warrior" Value="Melee_Warrior"/>
  <DEFINITION Label="Range_Fighter" Value="Range_Fighter"/>
  <DEFINITION Label="Light_Armsman" Value="Light_Armsman"/>
  <DEFINITION Label="Heavy_Armsman" Value="Heavy_Armsman"/>
  <DEFINITION Label="Close_Fighter" Value="Close_Fighter"/>
  <DEFINITION Label="Gunman" Value="Gunman"/>
  <DEFINITION Label="Heavy_Gunman" Value="Heavy_Gunman"/>
  <DEFINITION Label="Advanced_Gunman" Value="Advanced_Gunman"/>
  <DEFINITION Label="Advanced_Heavy_Gunman" Value="Advanced_Heavy_Gunman"/>
  <DEFINITION Label="Bludgeoner" Value="Bludgeoner"/>
  <DEFINITION Label="Skewerer" Value="Skewerer"/>
  <DEFINITION Label="Slasher" Value="Slasher"/>
  <DEFINITION Label="Smasher" Value="Smasher"/>
  <DEFINITION Label="Impaler" Value="Impaler"/>
  <DEFINITION Label="Cleaver" Value="Cleaver"/>
  <DEFINITION Label="Advanced_Close_Fighter" Value="Advanced_Close_Fighter"/>
  <DEFINITION Label="Maceman" Value="Maceman"/>
  <DEFINITION Label="Brute" Value="Brute"/>
  <DEFINITION Label="Spearman" Value="Spearman"/>
  <DEFINITION Label="Axeman" Value="Axeman"/>
  <DEFINITION Label="Swordsman" Value="Swordsman"/>
  <DEFINITION Label="Heavy_Maceman" Value="Heavy_Maceman"/>
  <DEFINITION Label="Pikeman" Value="Pikeman"/>
  <DEFINITION Label="Heavy_Axeman" Value="Heavy_Axeman"/>
  <DEFINITION Label="Heavy_Swordsman" Value="Heavy_Swordsman"/>
  <DEFINITION Label="Knifeman" Value="Knifeman"/>
  <DEFINITION Label="Hand_To_Hand_Fighter" Value="Hand_To_Hand_Fighter"/>
  <DEFINITION Label="Bowman" Value="Bowman"/>
  <DEFINITION Label="Pistoleer" Value="Pistoleer"/>
  <DEFINITION Label="Machine_Gunner" Value="Machine_Gunner"/>
  <DEFINITION Label="Heavy_Bowman" Value="Heavy_Bowman"/>
  <DEFINITION Label="Artilleryman" Value="Artilleryman"/>
  <DEFINITION Label="Rifleman" Value="Rifleman"/>
  <DEFINITION Label="Master_Maceman" Value="Master_Maceman"/>
  <DEFINITION Label="Master_Brute" Value="Master_Brute"/>
  <DEFINITION Label="Master_Spearman" Value="Master_Spearman"/>
  <DEFINITION Label="Master_Axeman" Value="Master_Axeman"/>
  <DEFINITION Label="Master_Swordsman" Value="Master_Swordsman"/>
  <DEFINITION Label="Master_Heavy_Maceman" Value="Master_Heavy_Maceman"/>
  <DEFINITION Label="Master_Pikeman" Value="Master_Pikeman"/>
  <DEFINITION Label="Master_Heavy_Axeman" Value="Master_Heavy_Axeman"/>
  <DEFINITION Label="Master_Heavy_Swordsman" Value="Master_Heavy_Swordsman"/>
  <DEFINITION Label="Master_Knifeman" Value="Master_Knifeman"/>
  <DEFINITION Label="Master_Hand_To_Hand_Fighter" Value="Master_Hand_To_Hand_Fighter"/>
  <DEFINITION Label="Master_Bowman" Value="Master_Bowman"/>
  <DEFINITION Label="Master_Pistoleer" Value="Master_Pistoleer"/>
  <DEFINITION Label="Master_Heavy_Bowman" Value="Master_Heavy_Bowman"/>
  <DEFINITION Label="Master_Artilleryman" Value="Master_Artilleryman"/>
  <DEFINITION Label="Master_Rifleman" Value="Master_Rifleman"/>
  <DEFINITION Label="FBT" Value="FBT"/>
  <DEFINITION Label="SGM" Value="SGM"/>
  <DEFINITION Label="GM" Value="GM"/>
  <DEFINITION Label="SG" Value="SG"/>
  <DEFINITION Label="G" Value="G"/>
  <DEFINITION Label="CM" Value="CM"/>
  <DEFINITION Label="EM" Value="EM"/>
  <DEFINITION Label="EG" Value="EG"/>
  <DEFINITION Label="OBSERVER" Value="OBSERVER"/>
  <DEFINITION Label="Armorer_Apprentice" Value="Armorer_Apprentice"/>
  <DEFINITION Label="Jeweler_Apprentice" Value="Jeweler_Apprentice"/>
  <DEFINITION Label="Melee_Weapon_Smith_Apprentice" Value="Melee_Weapon_Smith_Apprentice"/>
  <DEFINITION Label="Range_Weapon_Smith_Apprentice" Value="Range_Weapon_Smith_Apprentice"/>
  <DEFINITION Label="Heavy_Armorer" Value="Heavy_Armorer"/>
  <DEFINITION Label="Light_Armorer" Value="Light_Armorer"/>
  <DEFINITION Label="Medium_Armorer" Value="Medium_Armorer"/>
  <DEFINITION Label="Shield_Smith" Value="Shield_Smith"/>
  <DEFINITION Label="Jeweler" Value="Jeweler"/>
  <DEFINITION Label="Melee_Weapon_Smith" Value="Melee_Weapon_Smith"/>
  <DEFINITION Label="Melee_Heavy_Weapon_Smith" Value="Melee_Heavy_Weapon_Smith"/>
  <DEFINITION Label="Melee_Light_Weapon_Smith" Value="Melee_Light_Weapon_Smith"/>
  <DEFINITION Label="Range_Weapon_Smith" Value="Range_Weapon_Smith"/>
  <DEFINITION Label="Range_Heavy_Weapon_Smith" Value="Range_Heavy_Weapon_Smith"/>
  <DEFINITION Label="Advanced_Heavy_Armorer" Value="Advanced_Heavy_Armorer"/>
  <DEFINITION Label="Advanced_Light_Armorer" Value="Advanced_Light_Armorer"/>
  <DEFINITION Label="Advanced_Medium_Armorer" Value="Advanced_Medium_Armorer"/>
  <DEFINITION Label="Advanced_Shield_Smith" Value="Advanced_Shield_Smith"/>
  <DEFINITION Label="Advanced_Jeweler" Value="Advanced_Jeweler"/>
  <DEFINITION Label="Advanced_Melee_Weapon_Smith" Value="Advanced_Melee_Weapon_Smith"/>
  <DEFINITION Label="Advanced_Melee_Heavy_Weapon_Smith" Value="Advanced_Melee_Heavy_Weapon_Smith"/>
  <DEFINITION Label="Advanced_Melee_Light_Weapon_Smith" Value="Advanced_Melee_Light_Weapon_Smith"/>
  <DEFINITION Label="Advanced_Range_Weapon_Smith" Value="Advanced_Range_Weapon_Smith"/>
  <DEFINITION Label="Advanced_Range_Heavy_Weapon_Smith" Value="Advanced_Range_Heavy_Weapon_Smith"/>
  <DEFINITION Label="Expert_Heavy_Armorer" Value="Expert_Heavy_Armorer"/>
  <DEFINITION Label="Expert_Light_Armorer" Value="Expert_Light_Armorer"/>
  <DEFINITION Label="Expert_Medium_Armorer" Value="Expert_Medium_Armorer"/>
  <DEFINITION Label="Expert_Shield_Smith" Value="Expert_Shield_Smith"/>
  <DEFINITION Label="Expert_Jeweler" Value="Expert_Jeweler"/>
  <DEFINITION Label="Expert_Melee_Weapon_Smith" Value="Expert_Melee_Weapon_Smith"/>
  <DEFINITION Label="Expert_Melee_Heavy_Weapon_Smith" Value="Expert_Melee_Heavy_Weapon_Smith"/>
  <DEFINITION Label="Expert_Melee_Light_Weapon_Smith" Value="Expert_Melee_Light_Weapon_Smith"/>
  <DEFINITION Label="Expert_Range_Weapon_Smith" Value="Expert_Range_Weapon_Smith"/>
  <DEFINITION Label="Expert_Range_Heavy_Weapon_Smith" Value="Expert_Range_Heavy_Weapon_Smith"/>
  <DEFINITION Label="Heavy_Armorer_Master" Value="Heavy_Armorer_Master"/>
  <DEFINITION Label="Light_Armorer_Master" Value="Light_Armorer_Master"/>
  <DEFINITION Label="Medium_Armorer_Master" Value="Medium_Armorer_Master"/>
  <DEFINITION Label="Shield_Smith_Master" Value="Shield_Smith_Master"/>
  <DEFINITION Label="Jeweler_Master" Value="Jeweler_Master"/>
  <DEFINITION Label="Melee_Weapon_Smith_Master" Value="Melee_Weapon_Smith_Master"/>
  <DEFINITION Label="Melee_Heavy_Weapon_Smith_Master" Value="Melee_Heavy_Weapon_Smith_Master"/>
  <DEFINITION Label="Melee_Light_Weapon_Smith_Master" Value="Melee_Light_Weapon_Smith_Master"/>
  <DEFINITION Label="Range_Weapon_Smith_Master" Value="Range_Weapon_Smith_Master"/>
  <DEFINITION Label="Range_Heavy_Weapon_Smith_Master" Value="Range_Heavy_Weapon_Smith_Master"/>
  <DEFINITION Label="Forager_Apprentice" Value="Forager_Apprentice"/>
  <DEFINITION Label="Forager" Value="Forager"/>
  <DEFINITION Label="Desert_Forager" Value="Desert_Forager"/>
  <DEFINITION Label="Forest_Forager" Value="Forest_Forager"/>
  <DEFINITION Label="Jungle_Forager" Value="Jungle_Forager"/>
  <DEFINITION Label="Lacustre_Forager" Value="Lacustre_Forager"/>
  <DEFINITION Label="Prime_Roots_Forager" Value="Prime_Roots_Forager"/>
  <DEFINITION Label="Advanced_Desert_Forager" Value="Advanced_Desert_Forager"/>
  <DEFINITION Label="Advanced_Forest_Forager" Value="Advanced_Forest_Forager"/>
  <DEFINITION Label="Advanced_Jungle_Forager" Value="Advanced_Jungle_Forager"/>
  <DEFINITION Label="Advanced_Lacustre_Forager" Value="Advanced_Lacustre_Forager"/>
  <DEFINITION Label="Advanced_Prime_Roots_Forager" Value="Advanced_Prime_Roots_Forager"/>
  <DEFINITION Label="Expert_Desert_Forager" Value="Expert_Desert_Forager"/>
  <DEFINITION Label="Expert_Forest_Forager" Value="Expert_Forest_Forager"/>
  <DEFINITION Label="Expert_Jungle_Forager" Value="Expert_Jungle_Forager"/>
  <DEFINITION Label="Expert_Lacustre_Forager" Value="Expert_Lacustre_Forager"/>
  <DEFINITION Label="Expert_Prime_Roots_Forager" Value="Expert_Prime_Roots_Forager"/>
  <DEFINITION Label="Master_Desert_Forager" Value="Master_Desert_Forager"/>
  <DEFINITION Label="Master_Forest_Forager" Value="Master_Forest_Forager"/>
  <DEFINITION Label="Master_Jungle_Forager" Value="Master_Jungle_Forager"/>
  <DEFINITION Label="Master_Lacustre_Forager" Value="Master_Lacustre_Forager"/>
  <DEFINITION Label="Master_Prime_Roots_Forager" Value="Master_Prime_Roots_Forager"/>
  <DEFINITION Label="Kami_Ally" Value="Kami_Ally"/>
  <DEFINITION Label="Karavan_Ally" Value="Karavan_Ally"/>

  <DEFINITION Label="Title00000" Value="Title00000"/>
  <DEFINITION Label="Title00001" Value="Title00001"/>
  <DEFINITION Label="Title00002" Value="Title00002"/>
  <DEFINITION Label="Title00003" Value="Title00003"/>
  <DEFINITION Label="Title00004" Value="Title00004"/>
  <DEFINITION Label="Title00005" Value="Title00005"/>
  <DEFINITION Label="Title00006" Value="Title00006"/>
  <DEFINITION Label="Title00007" Value="Title00007"/>
  <DEFINITION Label="Title00008" Value="Title00008"/>
  <DEFINITION Label="Title00009" Value="Title00009"/>
  <DEFINITION Label="Title00010" Value="Title00010"/>
  <DEFINITION Label="Title00011" Value="Title00011"/>
  <DEFINITION Label="Title00012" Value="Title00012"/>
  <DEFINITION Label="Title00013" Value="Title00013"/>
  <DEFINITION Label="Title00014" Value="Title00014"/>
  <DEFINITION Label="Title00015" Value="Title00015"/>
  <DEFINITION Label="Title00016" Value="Title00016"/>
  <DEFINITION Label="Title00017" Value="Title00017"/>
  <DEFINITION Label="Title00018" Value="Title00018"/>
  <DEFINITION Label="Title00019" Value="Title00019"/>
  <DEFINITION Label="Title00020" Value="Title00020"/>
  <DEFINITION Label="Title00021" Value="Title00021"/>
  <DEFINITION Label="Title00022" Value="Title00022"/>
  <DEFINITION Label="Title00023" Value="Title00023"/>
  <DEFINITION Label="Title00024" Value="Title00024"/>
  <DEFINITION Label="Title00025" Value="Title00025"/>
  <DEFINITION Label="Title00026" Value="Title00026"/>
  <DEFINITION Label="Title00027" Value="Title00027"/>
  <DEFINITION Label="Title00028" Value="Title00028"/>
  <DEFINITION Label="Title00029" Value="Title00029"/>
  <DEFINITION Label="Title00030" Value="Title00030"/>
  <DEFINITION Label="Title00031" Value="Title00031"/>
  <DEFINITION Label="Title00032" Value="Title00032"/>
  <DEFINITION Label="Title00033" Value="Title00033"/>
  <DEFINITION Label="Title00034" Value="Title00034"/>
  <DEFINITION Label="Title00035" Value="Title00035"/>
  <DEFINITION Label="Title00036" Value="Title00036"/>
  <DEFINITION Label="Title00037" Value="Title00037"/>
  <DEFINITION Label="Title00038" Value="Title00038"/>
  <DEFINITION Label="Title00039" Value="Title00039"/>
  <DEFINITION Label="Title00040" Value="Title00040"/>
  <DEFINITION Label="Title00041" Value="Title00041"/>
  <DEFINITION Label="Title00042" Value="Title00042"/>
  <DEFINITION Label="Title00043" Value="Title00043"/>
  <DEFINITION Label="Title00044" Value="Title00044"/>
  <DEFINITION Label="Title00045" Value="Title00045"/>
  <DEFINITION Label="Title00046" Value="Title00046"/>
  <DEFINITION Label="Title00047" Value="Title00047"/>
  <DEFINITION Label="Title00048" Value="Title00048"/>
  <DEFINITION Label="Title00049" Value="Title00049"/>
  <DEFINITION Label="Title00050" Value="Title00050"/>
  <DEFINITION Label="Title00051" Value="Title00051"/>
  <DEFINITION Label="Title00052" Value="Title00052"/>
  <DEFINITION Label="Title00053" Value="Title00053"/>
  <DEFINITION Label="Title00054" Value="Title00054"/>
  <DEFINITION Label="Title00055" Value="Title00055"/>
  <DEFINITION Label="Title00056" Value="Title00056"/>
  <DEFINITION Label="Title00057" Value="Title00057"/>
  <DEFINITION Label="Title00058" Value="Title00058"/>
  <DEFINITION Label="Title00059" Value="Title00059"/>
  <DEFINITION Label="Title00060" Value="Title00060"/>
  <DEFINITION Label="Title00061" Value="Title00061"/>
  <DEFINITION Label="Title00062" Value="Title00062"/>
  <DEFINITION Label="Title00063" Value="Title00063"/>
  <DEFINITION Label="Title00064" Value="Title00064"/>
  <DEFINITION Label="Title00065" Value="Title00065"/>
  <DEFINITION Label="Title00066" Value="Title00066"/>
  <DEFINITION Label="Title00067" Value="Title00067"/>
  <DEFINITION Label="Title00068" Value="Title00068"/>
  <DEFINITION Label="Title00069" Value="Title00069"/>
  <DEFINITION Label="Title00070" Value="Title00070"/>
  <DEFINITION Label="Title00071" Value="Title00071"/>
  <DEFINITION Label="Title00072" Value="Title00072"/>
  <DEFINITION Label="Title00073" Value="Title00073"/>
  <DEFINITION Label="Title00074" Value="Title00074"/>
  <DEFINITION Label="Title00075" Value="Title00075"/>
  <DEFINITION Label="Title00076" Value="Title00076"/>
  <DEFINITION Label="Title00077" Value="Title00077"/>
  <DEFINITION Label="Title00078" Value="Title00078"/>
  <DEFINITION Label="Title00079" Value="Title00079"/>
  <LOG>Wed Oct 15 12:22:53 2003 (besson) Type Default = Refugee
Wed Oct 15 12:22:53 2003 (besson) Type Predef = 
Wed Oct 15 12:22:53 2003 (besson) Type Type = String
Wed Oct 15 12:22:53 2003 (besson) Type UI = NonEditableCombo
Wed Oct 29 14:02:53 2003 (besson) Type Predef = 
Mon Apr 05 17:14:16 2004 (nouveau) Type Predef = </LOG>
</TYPE>
