<?xml version="1.0"?>
<TYPE Type="String" UI="Edit" Version="0.5" State="modified">
  <DEFINITION Label="BaseStrength" Value="BaseStrength"/>
  <DEFINITION Label="MaxStrength" Value="MaxStrength"/>
  <DEFINITION Label="StrengthModifier" Value="StrengthModifier"/>
  <DEFINITION Label="CurrentStrength" Value="CurrentStrength"/>
  <DEFINITION Label="BaseStrengthRegenerate" Value="BaseStrengthRegenerate"/>
  <DEFINITION Label="StrengthRegenerateModifier" Value="StrengthRegenerateModifier"/>
  <DEFINITION Label="CurrentStrengthRegenerate" Value="CurrentStrengthRegenerate"/>
  <DEFINITION Label="BaseStrengthRegenerateRate" Value="BaseStrengthRegenerateRate"/>
  <DEFINITION Label="StrengthRegenerateModifierRate" Value="StrengthRegenerateModifierRate"/>
  <DEFINITION Label="CurrentStrengthRegenerateRate" Value="CurrentStrengthRegenerateRate"/>
  <DEFINITION Label="BaseConstitution" Value="BaseConstitution"/>
  <DEFINITION Label="MaxConstitution" Value="MaxConstitution"/>
  <DEFINITION Label="ConstitutionModifier" Value="ConstitutionModifier"/>
  <DEFINITION Label="CurrentConstitution" Value="CurrentConstitution"/>
  <DEFINITION Label="BaseConstitutionRegenerate" Value="BaseConstitutionRegenerate"/>
  <DEFINITION Label="ConstitutionRegenerateModifier" Value="ConstitutionRegenerateModifier"/>
  <DEFINITION Label="CurrentConstitutionRegenerate" Value="CurrentConstitutionRegenerate"/>
  <DEFINITION Label="BaseConstitutionRegenerateRate" Value="BaseConstitutionRegenerateRate"/>
  <DEFINITION Label="ConstitutionRegenerateModifierRate" Value="ConstitutionRegenerateModifierRate"/>
  <DEFINITION Label="CurrentConstitutionRegenerateRate" Value="CurrentConstitutionRegenerateRate"/>
  <DEFINITION Label="BaseAgility" Value="BaseAgility"/>
  <DEFINITION Label="MaxAgility" Value="MaxAgility"/>
  <DEFINITION Label="AgilityModifier" Value="AgilityModifier"/>
  <DEFINITION Label="CurrentAgility" Value="CurrentAgility"/>
  <DEFINITION Label="BaseAgilityRegenerate" Value="BaseAgilityRegenerate"/>
  <DEFINITION Label="AgilityRegenerateModifier" Value="AgilityRegenerateModifier"/>
  <DEFINITION Label="CurrentAgilityRegenerate" Value="CurrentAgilityRegenerate"/>
  <DEFINITION Label="BaseAgilityRegenerateRate" Value="BaseAgilityRegenerateRate"/>
  <DEFINITION Label="AgilityRegenerateModifierRate" Value="AgilityRegenerateModifierRate"/>
  <DEFINITION Label="CurrentAgilityRegenerateRate" Value="CurrentAgilityRegenerateRate"/>
  <DEFINITION Label="BaseWill" Value="BaseWill"/>
  <DEFINITION Label="MaxWill" Value="MaxWill"/>
  <DEFINITION Label="WillModifier" Value="WillModifier"/>
  <DEFINITION Label="CurrentWill" Value="CurrentWill"/>
  <DEFINITION Label="BaseWillRegenerate" Value="BaseWillRegenerate"/>
  <DEFINITION Label="WillRegenerateModifier" Value="WillRegenerateModifier"/>
  <DEFINITION Label="CurrentWillRegenerate" Value="CurrentWillRegenerate"/>
  <DEFINITION Label="BaseWillRegenerateRate" Value="BaseWillRegenerateRate"/>
  <DEFINITION Label="WillRegenerateModifierRate" Value="WillRegenerateModifierRate"/>
  <DEFINITION Label="CurrentWillRegenerateRate" Value="CurrentWillRegenerateRate"/>
  <DEFINITION Label="BaseWellBalanced" Value="BaseWellBalanced"/>
  <DEFINITION Label="MaxWellBalanced" Value="MaxWellBalanced"/>
  <DEFINITION Label="WellBalancedModifier" Value="WellBalancedModifier"/>
  <DEFINITION Label="CurrentWellBalanced" Value="CurrentWellBalanced"/>
  <DEFINITION Label="BaseWellBalancedRegenerate" Value="BaseWellBalancedRegenerate"/>
  <DEFINITION Label="WellBalancedRegenerateModifier" Value="WellBalancedRegenerateModifier"/>
  <DEFINITION Label="CurrentWellBalancedRegenerate" Value="CurrentWellBalancedRegenerate"/>
  <DEFINITION Label="BaseWellBalancedRegenerateRate" Value="BaseWellBalancedRegenerateRate"/>
  <DEFINITION Label="WellBalancedRegenerateModifierRate" Value="WellBalancedRegenerateModifierRate"/>
  <DEFINITION Label="CurrentWellBalancedRegenerateRate" Value="CurrentWellBalancedRegenerateRate"/>
  <DEFINITION Label="BaseIntelligence" Value="BaseIntelligence"/>
  <DEFINITION Label="MaxIntelligence" Value="MaxIntelligence"/>
  <DEFINITION Label="IntelligenceModifier" Value="IntelligenceModifier"/>
  <DEFINITION Label="CurrentIntelligence" Value="CurrentIntelligence"/>
  <DEFINITION Label="BaseIntelligenceRegenerate" Value="BaseIntelligenceRegenerate"/>
  <DEFINITION Label="IntelligenceRegenerateModifier" Value="IntelligenceRegenerateModifier"/>
  <DEFINITION Label="CurrentIntelligenceRegenerate" Value="CurrentIntelligenceRegenerate"/>
  <DEFINITION Label="BaseIntelligenceRegenerateRate" Value="BaseIntelligenceRegenerateRate"/>
  <DEFINITION Label="IntelligenceRegenerateModifierRate" Value="IntelligenceRegenerateModifierRate"/>
  <DEFINITION Label="CurrentIntelligenceRegenerateRate" Value="CurrentIntelligenceRegenerateRate"/>
  <DEFINITION Label="BaseCharisme" Value="BaseCharisme"/>
  <DEFINITION Label="MaxCharisme" Value="MaxCharisme"/>
  <DEFINITION Label="CharismeModifier" Value="CharismeModifier"/>
  <DEFINITION Label="CurrentCharisme" Value="CurrentCharisme"/>
  <DEFINITION Label="BaseCharismeRegenerate" Value="BaseCharismeRegenerate"/>
  <DEFINITION Label="CharismeRegenerateModifier" Value="CharismeRegenerateModifier"/>
  <DEFINITION Label="CurrentCharismeRegenerate" Value="CurrentCharismeRegenerate"/>
  <DEFINITION Label="BaseCharismeRegenerateRate" Value="BaseCharismeRegenerateRate"/>
  <DEFINITION Label="CharismeRegenerateModifierRate" Value="CharismeRegenerateModifierRate"/>
  <DEFINITION Label="CurrentCharismeRegenerateRate" Value="CurrentCharismeRegenerateRate"/>
  <DEFINITION Label="BaseEmpathie" Value="BaseEmpathie"/>
  <DEFINITION Label="MaxEmpathie" Value="MaxEmpathie"/>
  <DEFINITION Label="EmpathieModifier" Value="EmpathieModifier"/>
  <DEFINITION Label="CurrentEmpathie" Value="CurrentEmpathie"/>
  <DEFINITION Label="BaseEmpathieRegenerate" Value="BaseEmpathieRegenerate"/>
  <DEFINITION Label="EmpathieRegenerateModifier" Value="EmpathieRegenerateModifier"/>
  <DEFINITION Label="CurrentEmpathieRegenerate" Value="CurrentEmpathieRegenerate"/>
  <DEFINITION Label="BaseEmpathieRegenerateRate" Value="BaseEmpathieRegenerateRate"/>
  <DEFINITION Label="EmpathieRegenerateModifierRate" Value="EmpathieRegenerateModifierRate"/>
  <DEFINITION Label="CurrentEmpathieRegenerateRate" Value="CurrentEmpathieRegenerateRate"/>
  <DEFINITION Label="BasePerception" Value="BasePerception"/>
  <DEFINITION Label="MaxPerception" Value="MaxPerception"/>
  <DEFINITION Label="PerceptionModifier" Value="PerceptionModifier"/>
  <DEFINITION Label="CurrentPerception" Value="CurrentPerception"/>
  <DEFINITION Label="BasePerceptionRegenerate" Value="BasePerceptionRegenerate"/>
  <DEFINITION Label="PerceptionRegenerateModifier" Value="PerceptionRegenerateModifier"/>
  <DEFINITION Label="CurrentPerceptionRegenerate" Value="CurrentPerceptionRegenerate"/>
  <DEFINITION Label="BasePerceptionRegenerateRate" Value="BasePerceptionRegenerateRate"/>
  <DEFINITION Label="PerceptionRegenerateModifierRate" Value="PerceptionRegenerateModifierRate"/>
  <DEFINITION Label="CurrentPerceptionRegenerateRate" Value="CurrentPerceptionRegenerateRate"/>
  <DEFINITION Label="SpeedVariationModifier" Value="SpeedVariationModifier"/>
  <DEFINITION Label="WalkSpeed" Value="WalkSpeed"/>
  <DEFINITION Label="RunSpeed" Value="RunSpeed"/>
  <DEFINITION Label="Scores physiques" Value="Scores physiques"/>
  <DEFINITION Label="BaseHitPoints" Value="BaseHitPoints"/>
  <DEFINITION Label="MaxHitPoints" Value="MaxHitPoints"/>
  <DEFINITION Label="HitPointsModifier" Value="HitPointsModifier"/>
  <DEFINITION Label="CurrentHitPoints" Value="CurrentHitPoints"/>
  <DEFINITION Label="BaseHitPointsRegenerate" Value="BaseHitPointsRegenerate"/>
  <DEFINITION Label="HitPointsRegenerateModifier" Value="HitPointsRegenerateModifier"/>
  <DEFINITION Label="CurrentHitPointsRegenerate" Value="CurrentHitPointsRegenerate"/>
  <DEFINITION Label="BaseHitPointsRegenerateRate" Value="BaseHitPointsRegenerateRate"/>
  <DEFINITION Label="HitPointsRegenerateModifierRate" Value="HitPointsRegenerateModifierRate"/>
  <DEFINITION Label="CurrentHitPointsRegenerateRate" Value="CurrentHitPointsRegenerateRate"/>
  <DEFINITION Label="BaseSap" Value="BaseSap"/>
  <DEFINITION Label="MaxSap" Value="MaxSap"/>
  <DEFINITION Label="SapModifier" Value="SapModifier"/>
  <DEFINITION Label="CurrentSap" Value="CurrentSap"/>
  <DEFINITION Label="BaseSapRegenerate" Value="BaseSapRegenerate"/>
  <DEFINITION Label="SapRegenerateModifier" Value="SapRegenerateModifier"/>
  <DEFINITION Label="CurrentSapRegenerate" Value="CurrentSapRegenerate"/>
  <DEFINITION Label="BaseSapRegenerateRate" Value="BaseSapRegenerateRate"/>
  <DEFINITION Label="SapRegenerateModifierRate" Value="SapRegenerateModifierRate"/>
  <DEFINITION Label="CurrentSapRegenerateRate" Value="CurrentSapRegenerateRate"/>
  <DEFINITION Label="BaseStamina" Value="BaseStamina"/>
  <DEFINITION Label="MaxStamina" Value="MaxStamina"/>
  <DEFINITION Label="StaminaModifier" Value="StaminaModifier"/>
  <DEFINITION Label="CurrentStamina" Value="CurrentStamina"/>
  <DEFINITION Label="BaseStaminaRegenerate" Value="BaseStaminaRegenerate"/>
  <DEFINITION Label="StaminaRegenerateModifier" Value="StaminaRegenerateModifier"/>
  <DEFINITION Label="CurrentStaminaRegenerate" Value="CurrentStaminaRegenerate"/>
  <DEFINITION Label="BaseStaminaRegenerateRate" Value="BaseStaminaRegenerateRate"/>
  <DEFINITION Label="StaminaRegenerateModifierRate" Value="StaminaRegenerateModifierRate"/>
  <DEFINITION Label="CurrentStaminaRegenerateRate" Value="CurrentStaminaRegenerateRate"/>
  <DEFINITION Label="BaseWeight" Value="BaseWeight"/>
  <DEFINITION Label="MaxWeight" Value="MaxWeight"/>
  <DEFINITION Label="WeightModifier" Value="WeightModifier"/>
  <DEFINITION Label="CurrentWeight" Value="CurrentWeight"/>
  <DEFINITION Label="BaseWeightRegenerate" Value="BaseWeightRegenerate"/>
  <DEFINITION Label="WeightRegenerateModifier" Value="WeightRegenerateModifier"/>
  <DEFINITION Label="CurrentWeightRegenerate" Value="CurrentWeightRegenerate"/>
  <DEFINITION Label="BaseWeightRegenerateRate" Value="BaseWeightRegenerateRate"/>
  <DEFINITION Label="WeightRegenerateModifierRate" Value="WeightRegenerateModifierRate"/>
  <DEFINITION Label="CurrentWeightRegenerateRate" Value="CurrentWeightRegenerateRate"/>
  <DEFINITION Label="BaseDiseaseResist" Value="BaseDiseaseResist"/>
  <DEFINITION Label="MaxDiseaseResist" Value="MaxDiseaseResist"/>
  <DEFINITION Label="DiseaseResistModifier" Value="DiseaseResistModifier"/>
  <DEFINITION Label="CurrentDiseaseResist" Value="CurrentDiseaseResist"/>
  <DEFINITION Label="BaseDiseaseResistRegenerate" Value="BaseDiseaseResistRegenerate"/>
  <DEFINITION Label="DiseaseResistRegenerateModifier" Value="DiseaseResistRegenerateModifier"/>
  <DEFINITION Label="CurrentDiseaseResistRegenerate" Value="CurrentDiseaseResistRegenerate"/>
  <DEFINITION Label="BaseDiseaseResistRegenerateRate" Value="BaseDiseaseResistRegenerateRate"/>
  <DEFINITION Label="DiseaseResistRegenerateModifierRate" Value="DiseaseResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentDiseaseResistRegenerateRate" Value="CurrentDiseaseResistRegenerateRate"/>
  <DEFINITION Label="BaseMagicResist" Value="BaseMagicResist"/>
  <DEFINITION Label="MaxMagicResist" Value="MaxMagicResist"/>
  <DEFINITION Label="MagicResistModifier" Value="MagicResistModifier"/>
  <DEFINITION Label="CurrentMagicResist" Value="CurrentMagicResist"/>
  <DEFINITION Label="BaseMagicResistRegenerate" Value="BaseMagicResistRegenerate"/>
  <DEFINITION Label="MagicResistRegenerateModifier" Value="MagicResistRegenerateModifier"/>
  <DEFINITION Label="CurrentMagicResistRegenerate" Value="CurrentMagicResistRegenerate"/>
  <DEFINITION Label="BaseMagicResistRegenerateRate" Value="BaseMagicResistRegenerateRate"/>
  <DEFINITION Label="MagicResistRegenerateModifierRate" Value="MagicResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentMagicResistRegenerateRate" Value="CurrentMagicResistRegenerateRate"/>
  <DEFINITION Label="BaseTechnoResist" Value="BaseTechnoResist"/>
  <DEFINITION Label="MaxTechnoResist" Value="MaxTechnoResist"/>
  <DEFINITION Label="TechnoResistModifier" Value="TechnoResistModifier"/>
  <DEFINITION Label="CurrentTechnoResist" Value="CurrentTechnoResist"/>
  <DEFINITION Label="BaseTechnoResistRegenerate" Value="BaseTechnoResistRegenerate"/>
  <DEFINITION Label="TechnoResistRegenerateModifier" Value="TechnoResistRegenerateModifier"/>
  <DEFINITION Label="CurrentTechnoResistRegenerate" Value="CurrentTechnoResistRegenerate"/>
  <DEFINITION Label="BaseTechnoResistRegenerateRate" Value="BaseTechnoResistRegenerateRate"/>
  <DEFINITION Label="TechnoResistRegenerateModifierRate" Value="TechnoResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentTechnoResistRegenerateRate" Value="CurrentTechnoResistRegenerateRate"/>
  <DEFINITION Label="BaseImpactResist" Value="BaseImpactResist"/>
  <DEFINITION Label="MaxImpactResist" Value="MaxImpactResist"/>
  <DEFINITION Label="ImpactResistModifier" Value="ImpactResistModifier"/>
  <DEFINITION Label="CurrentImpactResist" Value="CurrentImpactResist"/>
  <DEFINITION Label="BaseImpactResistRegenerate" Value="BaseImpactResistRegenerate"/>
  <DEFINITION Label="ImpactResistRegenerateModifier" Value="ImpactResistRegenerateModifier"/>
  <DEFINITION Label="CurrentImpactResistRegenerate" Value="CurrentImpactResistRegenerate"/>
  <DEFINITION Label="BaseImpactResistRegenerateRate" Value="BaseImpactResistRegenerateRate"/>
  <DEFINITION Label="ImpactResistRegenerateModifierRate" Value="ImpactResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentImpactResistRegenerateRate" Value="CurrentImpactResistRegenerateRate"/>
  <DEFINITION Label="BaseFearResist" Value="BaseFearResist"/>
  <DEFINITION Label="MaxFearResist" Value="MaxFearResist"/>
  <DEFINITION Label="FearResistModifier" Value="FearResistModifier"/>
  <DEFINITION Label="CurrentFearResist" Value="CurrentFearResist"/>
  <DEFINITION Label="BaseFearResistRegenerate" Value="BaseFearResistRegenerate"/>
  <DEFINITION Label="FearResistRegenerateModifier" Value="FearResistRegenerateModifier"/>
  <DEFINITION Label="CurrentFearResistRegenerate" Value="CurrentFearResistRegenerate"/>
  <DEFINITION Label="BaseFearResistRegenerateRate" Value="BaseFearResistRegenerateRate"/>
  <DEFINITION Label="FearResistRegenerateModifierRate" Value="FearResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentFearResistRegenerateRate" Value="CurrentFearResistRegenerateRate"/>
  <DEFINITION Label="Harvest" Value="Harvest"/>
  <DEFINITION Label="Quartering" Value="Quartering"/>
  <DEFINITION Label="Fishing" Value="Fishing"/>
  <DEFINITION Label="Diving" Value="Diving"/>
  <DEFINITION Label="Digging" Value="Digging"/>
  <DEFINITION Label="Desert" Value="Desert"/>
  <DEFINITION Label="Jungle" Value="Jungle"/>
  <DEFINITION Label="Lake" Value="Lake"/>
  <DEFINITION Label="PrimaryRoots" Value="PrimaryRoots"/>
  <DEFINITION Label="FirstAid" Value="FirstAid"/>
  <DEFINITION Label="HominOpponentConsider" Value="HominOpponentConsider"/>
  <DEFINITION Label="Camouflage" Value="Camouflage"/>
  <DEFINITION Label="Fyros" Value="Fyros"/>
  <DEFINITION Label="Tryker" Value="Tryker"/>
  <DEFINITION Label="Matis" Value="Matis"/>
  <DEFINITION Label="Zorai" Value="Zorai"/>
  <DEFINITION Label="Kitin" Value="Kitin"/>
  <DEFINITION Label="Dragon" Value="Dragon"/>
  <DEFINITION Label="TrainingStrength" Value="TrainingStrength"/>
  <DEFINITION Label="TrainingConstitution" Value="TrainingConstitution"/>
  <DEFINITION Label="TrainingAgility" Value="TrainingAgility"/>
  <DEFINITION Label="TrainingPerception" Value="TrainingPerception"/>
  <DEFINITION Label="TrainingWill" Value="TrainingWill"/>
  <DEFINITION Label="TrainingWellBalanced" Value="TrainingWellBalanced"/>
  <DEFINITION Label="TrainingIntelligence" Value="TrainingIntelligence"/>
  <DEFINITION Label="TrainingEmpathie" Value="TrainingEmpathie"/>
  <DEFINITION Label="TrainingHp" Value="TrainingHp"/>
  <DEFINITION Label="TrainingSeve" Value="TrainingSeve"/>
  <DEFINITION Label="TrainingStamina" Value="TrainingStamina"/>
  <DEFINITION Label="TrainingMagicResist" Value="TrainingMagicResist"/>
  <DEFINITION Label="TrainingImpactResist" Value="TrainingImpactResist"/>
  <DEFINITION Label="TrainingDiseaseResist" Value="TrainingDiseaseResist"/>
  <DEFINITION Label="TrainingTechnoResist" Value="TrainingTechnoResist"/>
  <DEFINITION Label="TrainingFearResist" Value="TrainingFearResist"/>
  <DEFINITION Label="Caravan" Value="Caravan"/>
  <DEFINITION Label="Rocktabou" Value="Rocktabou"/>
  <DEFINITION Label="Goo" Value="Goo"/>
  <DEFINITION Label="Kami" Value="Kami"/>
  <DEFINITION Label="TrykerMystery" Value="TrykerMystery"/>
  <DEFINITION Label="MatisMystery" Value="MatisMystery"/>
  <DEFINITION Label="ZoraiMystery" Value="ZoraiMystery"/>
  <DEFINITION Label="Dagger" Value="Dagger"/>
  <DEFINITION Label="Sword" Value="Sword"/>
  <DEFINITION Label="LongSword" Value="LongSword"/>
  <DEFINITION Label="TwoHandsSword" Value="TwoHandsSword"/>
  <DEFINITION Label="Saber" Value="Saber"/>
  <DEFINITION Label="Axe" Value="Axe"/>
  <DEFINITION Label="Mass" Value="Mass"/>
  <DEFINITION Label="Stick" Value="Stick"/>
  <DEFINITION Label="GreatAxe" Value="GreatAxe"/>
  <DEFINITION Label="GreatMass" Value="GreatMass"/>
  <DEFINITION Label="Pike" Value="Pike"/>
  <DEFINITION Label="HandToHand" Value="HandToHand"/>
  <DEFINITION Label="BersekAttack" Value="BersekAttack"/>
  <DEFINITION Label="Kick" Value="Kick"/>
  <DEFINITION Label="OnHorseBackMelee" Value="OnHorseBackMelee"/>
  <DEFINITION Label="Rondache" Value="Rondache"/>
  <DEFINITION Label="Shield" Value="Shield"/>
  <DEFINITION Label="DualWield" Value="DualWield"/>
  <DEFINITION Label="Dodging" Value="Dodging"/>
  <DEFINITION Label="HeavyArmourWear" Value="HeavyArmourWear"/>
  <DEFINITION Label="MediumArmourWear" Value="MediumArmourWear"/>
  <DEFINITION Label="LightArmourWear" Value="LightArmourWear"/>
  <DEFINITION Label="FyrosSword" Value="FyrosSword"/>
  <DEFINITION Label="FyrosLongSword" Value="FyrosLongSword"/>
  <DEFINITION Label="FyrosTwoHandSword" Value="FyrosTwoHandSword"/>
  <DEFINITION Label="FyrosSaber" Value="FyrosSaber"/>
  <DEFINITION Label="FyrosDagger" Value="FyrosDagger"/>
  <DEFINITION Label="FyrosHeavyArmourWear" Value="FyrosHeavyArmourWear"/>
  <DEFINITION Label="FyrosMediumArmourWear" Value="FyrosMediumArmourWear"/>
  <DEFINITION Label="FyrosLightArmourWear" Value="FyrosLightArmourWear"/>
  <DEFINITION Label="FyrosShield" Value="FyrosShield"/>
  <DEFINITION Label="FyrosRondach" Value="FyrosRondach"/>
  <DEFINITION Label="BowPistol" Value="BowPistol"/>
  <DEFINITION Label="BowRifle" Value="BowRifle"/>
  <DEFINITION Label="Pistol" Value="Pistol"/>
  <DEFINITION Label="Rifle" Value="Rifle"/>
  <DEFINITION Label="HeavyWeapon" Value="HeavyWeapon"/>
  <DEFINITION Label="Rocket" Value="Rocket"/>
  <DEFINITION Label="Grenade" Value="Grenade"/>
  <DEFINITION Label="OnHorseBackShoot" Value="OnHorseBackShoot"/>
  <DEFINITION Label="FyrosBowPistol" Value="FyrosBowPistol"/>
  <DEFINITION Label="FyrosRifle" Value="FyrosRifle"/>
  <DEFINITION Label="FyrosPistol" Value="FyrosPistol"/>
  <DEFINITION Label="Mandragore" Value="Mandragore"/>
  <DEFINITION Label="Dryade" Value="Dryade"/>
  <DEFINITION Label="Sylve" Value="Sylve"/>
  <DEFINITION Label="MajorMandragore" Value="MajorMandragore"/>
  <DEFINITION Label="MajorDryade" Value="MajorDryade"/>
  <DEFINITION Label="MajorSylve" Value="MajorSylve"/>
  <DEFINITION Label="MagicTransfert" Value="MagicTransfert"/>
  <DEFINITION Label="MagicObjects" Value="MagicObjects"/>
  <DEFINITION Label="MandragoreSpring" Value="MandragoreSpring"/>
  <DEFINITION Label="MandragoreSummer" Value="MandragoreSummer"/>
  <DEFINITION Label="MandragoreAutomn" Value="MandragoreAutomn"/>
  <DEFINITION Label="MandragoreWinter" Value="MandragoreWinter"/>
  <DEFINITION Label="SylveSpring" Value="SylveSpring"/>
  <DEFINITION Label="SylveSummer" Value="SylveSummer"/>
  <DEFINITION Label="SylveAutomn" Value="SylveAutomn"/>
  <DEFINITION Label="SylveWinter" Value="SylveWinter"/>
  <DEFINITION Label="DryadeSpring" Value="DryadeSpring"/>
  <DEFINITION Label="DryadeSummer" Value="DryadeSummer"/>
  <DEFINITION Label="DryadeAutomn" Value="DryadeAutomn"/>
  <DEFINITION Label="DryadeWinter" Value="DryadeWinter"/>
  <DEFINITION Label="MajorMandragoreSpring" Value="MajorMandragoreSpring"/>
  <DEFINITION Label="MajorMandragoreSummer" Value="MajorMandragoreSummer"/>
  <DEFINITION Label="MajorMandragoreAutomn" Value="MajorMandragoreAutomn"/>
  <DEFINITION Label="MajorMandragoreWinter" Value="MajorMandragoreWinter"/>
  <DEFINITION Label="MajorSylveSpring" Value="MajorSylveSpring"/>
  <DEFINITION Label="MajorSylveSummer" Value="MajorSylveSummer"/>
  <DEFINITION Label="MajorSylveAutomn" Value="MajorSylveAutomn"/>
  <DEFINITION Label="MajorSylveWinter" Value="MajorSylveWinter"/>
  <DEFINITION Label="MajorDryadeSpring" Value="MajorDryadeSpring"/>
  <DEFINITION Label="MajorDryadeSummer" Value="MajorDryadeSummer"/>
  <DEFINITION Label="MajorDryadeAutomn" Value="MajorDryadeAutomn"/>
  <DEFINITION Label="MajorDryadeWinter" Value="MajorDryadeWinter"/>
  <DEFINITION Label="Running" Value="Running"/>
  <DEFINITION Label="Swimming" Value="Swimming"/>
  <DEFINITION Label="Riding" Value="Riding"/>
  <DEFINITION Label="TrainAnimal" Value="TrainAnimal"/>
  <DEFINITION Label="LeadAnimal" Value="LeadAnimal"/>
  <DEFINITION Label="WeaponsCutting" Value="WeaponsCutting"/>
  <DEFINITION Label="MakeThrowingWeapons" Value="MakeThrowingWeapons"/>
  <DEFINITION Label="Blacksmithing" Value="Blacksmithing"/>
  <DEFINITION Label="ClothTailoring" Value="ClothTailoring"/>
  <DEFINITION Label="LeatherTailoring" Value="LeatherTailoring"/>
  <DEFINITION Label="Jewellery" Value="Jewellery"/>
  <DEFINITION Label="Cooking" Value="Cooking"/>
  <DEFINITION Label="Mechanic" Value="Mechanic"/>
  <DEFINITION Label="Building" Value="Building"/>
  <DEFINITION Label="Apothecary" Value="Apothecary"/>
  <DEFINITION Label="MakeShiftRepair" Value="MakeShiftRepair"/>
  <DEFINITION Label="ArmorAndWeaponSmithing" Value="ArmorAndWeaponSmithing"/>
  <DEFINITION Label="Slots d'equipements" Value="Slots d'equipements"/>
  <DEFINITION Label="Headdress" Value="Headdress"/>
  <DEFINITION Label="Head" Value="Head"/>
  <DEFINITION Label="Face" Value="Face"/>
  <DEFINITION Label="EarL" Value="EarL"/>
  <DEFINITION Label="EarR" Value="EarR"/>
  <DEFINITION Label="Neck" Value="Neck"/>
  <DEFINITION Label="Shoulders" Value="Shoulders"/>
  <DEFINITION Label="Back" Value="Back"/>
  <DEFINITION Label="Chest" Value="Chest"/>
  <DEFINITION Label="Arms" Value="Arms"/>
  <DEFINITION Label="WristL" Value="WristL"/>
  <DEFINITION Label="WristR" Value="WristR"/>
  <DEFINITION Label="Hands" Value="Hands"/>
  <DEFINITION Label="HandL" Value="HandL"/>
  <DEFINITION Label="HandR" Value="HandR"/>
  <DEFINITION Label="FingerL" Value="FingerL"/>
  <DEFINITION Label="FingerR" Value="FingerR"/>
  <DEFINITION Label="Legs" Value="Legs"/>
  <DEFINITION Label="AnkleL" Value="AnkleL"/>
  <DEFINITION Label="AnkleR" Value="AnkleR"/>
  <DEFINITION Label="Feets" Value="Feets"/>
  <DEFINITION Label="HitPoints" Value="HitPoints"/>
  <LOG>Mon Jun 17 18:07:16 2002 (miller) Type Predef = 
Mon Jun 17 18:07:16 2002 (miller) Type Type = String
Mon Jun 17 18:07:16 2002 (miller) Type UI = NonEditableCombo
Wed Jul 24 15:22:26 2002 (chafik) Type UI = Edit
Fri Jul 26 14:03:31 2002 (chafik) Type Predef = 
Fri Jul 26 14:03:35 2002 (chafik) Type Predef = 
Fri Jul 26 14:35:23 2002 (chafik) Type Predef = </LOG>
</TYPE>
