// Ryzom - MMORPG Framework <http://dev.ryzom.com/projects/ryzom/>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#ifndef CL_EMOJI_MANAGER_H
#define CL_EMOJI_MANAGER_H

#include "nel/misc/types_nl.h"

#include <map>
#include <string>
#include <vector>

/** Emoji table of the chat, generated by ryzom/tools/emoji.
  */
class CEmojiManager
{
public:
	struct CEntry
	{
		// Name matched for this entry, without colons; shown as hover tooltip.
		std::string		Name;
		std::string		Utf8;
		// Atlas tile name, empty if none.
		std::string		Texture;
		// Unicode short name, only for emoji listed by the picker.
		std::string		Desc;
	};

	// One tab of the emoji picker.
	struct CGroup
	{
		std::string						Label;
		std::vector<const CEntry *>		Emoji;
	};

	static CEmojiManager &getInstance();
	static void releaseInstance();

	void init();

	// False when the text has neither a colon nor a byte that can start an emoji.
	bool mayContainEmoji(const std::string &text) const;
	// Replace every known ":name:", stepping over format tags.
	std::string substituteShortcodes(const std::string &text) const;
	// Emoji written as ":name:" or as literal unicode at index, longest sequence first.
	bool matchAt(const std::string &text, std::string::size_type index,
				 std::string::size_type to,
				 std::string::size_type &len, const CEntry *&entry) const;

	const std::vector<CGroup> &getGroups() const { return _Groups; }

	static const uint MaxNameBytes = 64;

private:

	CEmojiManager();

	static CEmojiManager *_Instance;

	void loadTable(const std::string &filename, bool required);
	// Must run after the reverse index is built: the picker's canonical names
	// replace the first alias in it.
	void loadPicker(const std::string &filename);

	// Keyed by the raw bytes between the colons; Zulip names are not all ASCII.
	std::map<std::string, CEntry>			_ByName;
	std::map<std::string, const CEntry *>	_ByUtf8;
	// Bytes that can start a literal emoji, checked for every chat line.
	bool									_CanStartUtf8[256];
	// Distinct byte lengths of literal emoji, longest first.
	std::vector<std::string::size_type>		_Utf8Lengths;
	// Points into _ByName.
	std::vector<CGroup>						_Groups;
	bool									_Loaded;
};

#endif // CL_EMOJI_MANAGER_H
