<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Default="UNKNOWN" Revision="$Revision: 1.13 $" State="modified">
  <DEFINITION Label="UNKNOWN" Value="UNKNOWN"/>
  <DEFINITION Label="BUFF_HP" Value="BUFF_HP"/>
  <DEFINITION Label="DEBUFF_HP" Value="DEBUFF_HP"/>
  <DEFINITION Label="BUFF_HP_REGEN" Value="BUFF_HP_REGEN"/>
  <DEFINITION Label="DEBUFF_HP_REGEN" Value="DEBUFF_HP_REGEN"/>
  <DEFINITION Label="BUFF_STAMINA" Value="BUFF_STAMINA"/>
  <DEFINITION Label="DEBUFF_STAMINA" Value="DEBUFF_STAMINA"/>
  <DEFINITION Label="BUFF_STAMINA_REGEN" Value="BUFF_STAMINA_REGEN"/>
  <DEFINITION Label="DEBUFF_STAMINA_REGEN" Value="DEBUFF_STAMINA_REGEN"/>
  <DEFINITION Label="BUFF_SAP" Value="BUFF_SAP"/>
  <DEFINITION Label="DEBUFF_SAP" Value="DEBUFF_SAP"/>
  <DEFINITION Label="BUFF_SAP_REGEN" Value="BUFF_SAP_REGEN"/>
  <DEFINITION Label="DEBUFF_SAP_REGEN" Value="DEBUFF_SAP_REGEN"/>
  <DEFINITION Label="BUFF_SPEED" Value="BUFF_SPEED"/>
  <DEFINITION Label="DEBUFF_SPEED" Value="DEBUFF_SPEED"/>
  <DEFINITION Label="DEBUFF_SKILL" Value="DEBUFF_SKILL"/>
  <DEFINITION Label="SLOW_WOUNDED" Value="SLOW_WOUNDED"/>
  <DEFINITION Label="BLEED" Value="BLEED"/>
  <DEFINITION Label="SLOW" Value="SLOW"/>
  <DEFINITION Label="POISON" Value="POISON"/>
  <DEFINITION Label="STUN" Value="STUN"/>
  <DEFINITION Label="FEAR" Value="FEAR"/>
  <DEFINITION Label="PROTECT_FROM_SLOW" Value="PROTECT_FROM_SLOW"/>
  <DEFINITION Label="PROTECT_FROM_POISON" Value="PROTECT_FROM_POISON"/>
  <DEFINITION Label="DEFENSE_AGAINST_COMBAT" Value="DEFENSE_AGAINST_COMBAT"/>
  <DEFINITION Label="SPELL_MAY_FAIL" Value="SPELL_MAY_FAIL"/>
  <DEFINITION Label="FABER_MAY_FAIL" Value="FABER_MAY_FAIL"/>
  <DEFINITION Label="STRATEGY_MAY_FAIL" Value="STRATEGY_MAY_FAIL"/>
  <DEFINITION Label="ENTITY_MELEE_DEFENSE" Value="ENTITY_MELEE_DEFENSE"/>
  <DEFINITION Label="GLOBAL_MELEE_DEFENSE" Value="GLOBAL_MELEE_DEFENSE"/>
  <DEFINITION Label="GLOBAL_MELEE_DEFENSE_HOMINS" Value="GLOBAL_MELEE_DEFENSE_HOMINS"/>
  <DEFINITION Label="GLOBAL_MELEE_DEFENSE_CREATURES" Value="GLOBAL_MELEE_DEFENSE_CREATURES"/>
  <DEFINITION Label="ENTITY_RANGE_DEFENSE" Value="ENTITY_RANGE_DEFENSE"/>
  <DEFINITION Label="GLOBAL_RANGE_DEFENSE" Value="GLOBAL_RANGE_DEFENSE"/>
  <DEFINITION Label="GLOBAL_RANGE_DEFENSE_HOMINS" Value="GLOBAL_RANGE_DEFENSE_HOMINS"/>
  <DEFINITION Label="GLOBAL_RANGE_DEFENSE_CREATURES" Value="GLOBAL_RANGE_DEFENSE_CREATURES"/>
  <DEFINITION Label="BUFF_MELEE_SLASHING_ARMOR" Value="BUFF_MELEE_SLASHING_ARMOR"/>
  <DEFINITION Label="BUFF_MELEE_BLUNT_ARMOR" Value="BUFF_MELEE_BLUNT_ARMOR"/>
  <DEFINITION Label="BUFF_MELEE_PIERCING_ARMOR" Value="BUFF_MELEE_PIERCING_ARMOR"/>
  <DEFINITION Label="MELEE_ATTACK_SLOW" Value="MELEE_ATTACK_SLOW"/>
  <DEFINITION Label="REDUCE_COMBAT_SKILLS" Value="REDUCE_COMBAT_SKILLS"/>
  <DEFINITION Label="REDUCE_MAGIC_SKILLS" Value="REDUCE_MAGIC_SKILLS"/>
  <DEFINITION Label="DECAY_SAP" Value="DECAY_SAP"/>
  <DEFINITION Label="DECAY_STAMINA" Value="DECAY_STAMINA"/>
  <DEFINITION Label="MAGIC_SHIELD_VS_MELEE" Value="MAGIC_SHIELD_VS_MELEE"/>
  <DEFINITION Label="MAGIC_SHIELD_VS_RANGE" Value="MAGIC_SHIELD_VS_RANGE"/>
  <DEFINITION Label="MULTIPLY_MAGIC_BRICK_LATENCY" Value="MULTIPLY_MAGIC_BRICK_LATENCY"/>
  <DEFINITION Label="MULTIPLY_COMBAT_BRICK_LATENCY" Value="MULTIPLY_COMBAT_BRICK_LATENCY"/>
  <DEFINITION Label="CURSE" Value="CURSE"/>
  <DEFINITION Label="MADNESS" Value="MADNESS"/>
  <DEFINITION Label="PROTECT_FROM_BASIC_MAGIC" Value="PROTECT_FROM_BASIC_MAGIC"/>
  <DEFINITION Label="PROTECT_FROM_BASIC_SHOOT" Value="PROTECT_FROM_BASIC_SHOOT"/>
  <DEFINITION Label="BUFF_MAGIC_RESIST" Value="BUFF_MAGIC_RESIST"/>
  <DEFINITION Label="PROTECT_FROM_MUSCLE_FEVER" Value="PROTECT_FROM_MUSCLE_FEVER"/>
  <DEFINITION Label="MUSCLE_FEVER" Value="MUSCLE_FEVER"/>
  <DEFINITION Label="PROTECT_FROM_MADNESS" Value="PROTECT_FROM_MADNESS"/>
  <DEFINITION Label="WAR_GIFT" Value="WAR_GIFT"/>
  <DEFINITION Label="RANGE_ARMOR" Value="RANGE_ARMOR"/>
  <DEFINITION Label="MELEE_ARMOR" Value="MELEE_ARMOR"/>
  <DEFINITION Label="COMBAT_ARMOR" Value="COMBAT_ARMOR"/>
  <DEFINITION Label="CREATURE_ARMOR" Value="CREATURE_ARMOR"/>
  <DEFINITION Label="WIND_GIFT" Value="WIND_GIFT"/>
  <DEFINITION Label="MAGIC_MIRROR" Value="MAGIC_MIRROR"/>
  <DEFINITION Label="SHOOT_MIRROR" Value="SHOOT_MIRROR"/>
  <DEFINITION Label="STRENGTH_GIFT" Value="STRENGTH_GIFT"/>
  <DEFINITION Label="MINOR_ALCHEMY_LIFE" Value="MINOR_ALCHEMY_LIFE"/>
  <DEFINITION Label="MINOR_ALCHEMY_STAMINA" Value="MINOR_ALCHEMY_STAMINA"/>
  <DEFINITION Label="MINOR_ALCHEMY_SAP" Value="MINOR_ALCHEMY_SAP"/>
  <DEFINITION Label="MAJOR_ALCHEMY_LIFE" Value="MAJOR_ALCHEMY_LIFE"/>
  <DEFINITION Label="MAJOR_ALCHEMY_STAMINA" Value="MAJOR_ALCHEMY_STAMINA"/>
  <DEFINITION Label="MAJOR_ALCHEMY_SAP" Value="MAJOR_ALCHEMY_SAP"/>
  <DEFINITION Label="MAJOR_STEAL_STAMINA_REGEN" Value="MAJOR_STEAL_STAMINA_REGEN"/>
  <DEFINITION Label="MAJOR_STEAL_LIFE_REGEN" Value="MAJOR_STEAL_LIFE_REGEN"/>
  <DEFINITION Label="MAJOR_STEAL_SAP_REGEN" Value="MAJOR_STEAL_SAP_REGEN"/>
  <DEFINITION Label="VISUAL_WITHERING" Value="VISUAL_WITHERING"/>
  <DEFINITION Label="HEAR_WITHERING" Value="HEAR_WITHERING"/>
  <DEFINITION Label="TACTILE_WITHERING" Value="TACTILE_WITHERING"/>
  <DEFINITION Label="CAMOUFLAGE" Value="CAMOUFLAGE"/>
  <LOG>Tue Dec 03 17:35:51 2002 (fleury) Type Predef = 
Tue Dec 03 17:35:51 2002 (fleury) Type Type = String
Tue Dec 03 17:35:51 2002 (fleury) Type UI = NonEditableCombo
Tue Dec 03 17:40:51 2002 (fleury) Type Predef = 
Tue Dec 03 17:41:12 2002 (fleury) Type Default = UNKNOWN
Tue Dec 03 17:41:12 2002 (fleury) Type Predef = 
Thu Dec 05 11:00:14 2002 (brigand) Type Predef = 
Thu Dec 05 11:22:00 2002 (brigand) Type Predef = 
Thu Dec 05 11:51:06 2002 (brigand) Type Predef = 
Fri Dec 06 15:15:15 2002 (fleury) Type Predef = 
Mon Jan 06 14:35:59 2003 (brigand) Type Predef = 
Fri Jan 10 15:12:41 2003 (fleury) Type Predef = 
Mon Jan 13 18:30:46 2003 (brigand) Type Predef = 
Wed Jan 15 18:18:06 2003 (brigand) Type Predef = 
Mon Jan 27 19:17:35 2003 (brigand) Type Predef = 
Tue Jan 28 11:19:57 2003 (brigand) Type Predef = 
Tue Jan 28 12:14:29 2003 (brigand) Type Predef = 
Tue Jan 28 12:19:31 2003 (brigand) Type Predef = 
Tue Jan 28 12:23:13 2003 (brigand) Type Predef = 
Tue Jan 28 15:21:45 2003 (brigand) Type Predef = 
Tue Jan 28 17:16:01 2003 (brigand) Type Predef = 
Tue Jan 28 19:40:40 2003 (brigand) Type Predef = 
Tue Jan 28 19:44:09 2003 (brigand) Type Predef = 
Wed Jan 29 11:43:20 2003 (brigand) Type Predef = 
Wed Jan 29 13:45:17 2003 (brigand) Type Predef = 
Wed Jan 29 14:03:04 2003 (brigand) Type Predef = 
Mon Mar 24 12:03:14 2003 (fleury) Type Predef = </LOG>
</TYPE>
