<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Revision="$Revision: 1.1 $" State="modified">
  <DEFINITION Label="matis" Value="matis"/>
  <DEFINITION Label="fyros" Value="fyros"/>
  <DEFINITION Label="tryker" Value="tryker"/>
  <DEFINITION Label="zorai" Value="zorai"/>
  <DEFINITION Label="kami" Value="kami"/>
  <DEFINITION Label="black_kami" Value="black_kami"/>
  <DEFINITION Label="karavan" Value="karavan"/>
  <DEFINITION Label="white_karavan" Value="white_karavan"/>
  <DEFINITION Label="tribe_ancient_dryads" Value="tribe_ancient_dryads"/>
  <DEFINITION Label="tribe_antikamis" Value="tribe_antikamis"/>
  <DEFINITION Label="tribe_barkers" Value="tribe_barkers"/>
  <DEFINITION Label="tribe_beachcombers" Value="tribe_beachcombers"/>
  <DEFINITION Label="tribe_black_circle" Value="tribe_black_circle"/>
  <DEFINITION Label="tribe_cholorogoos" Value="tribe_cholorogoos"/>
  <DEFINITION Label="tribe_cockroaches" Value="tribe_cockroaches"/>
  <DEFINITION Label="tribe_company_of_the_eternal_tree" Value="tribe_company_of_the_eternal_tree"/>
  <DEFINITION Label="tribe_corsair" Value="tribe_corsair"/>
  <DEFINITION Label="tribe_cute" Value="tribe_cute"/>
  <DEFINITION Label="tribe_darkening_sap" Value="tribe_darkening_sap"/>
  <DEFINITION Label="tribe_dune_riders" Value="tribe_dune_riders"/>
  <DEFINITION Label="tribe_ecowarriors" Value="tribe_ecowarriors"/>
  <DEFINITION Label="tribe_firebrands" Value="tribe_firebrands"/>
  <DEFINITION Label="tribe_first_deserter" Value="tribe_first_deserter"/>
  <DEFINITION Label="tribe_frahar" Value="tribe_frahar"/>
  <DEFINITION Label="tribe_frahar_hunters" Value="tribe_frahar_hunters"/>
  <DEFINITION Label="tribe_gibbay" Value="tribe_gibbay"/>
  <DEFINITION Label="tribe_goo_heads" Value="tribe_goo_heads"/>
  <DEFINITION Label="tribe_green_seed" Value="tribe_green_seed"/>
  <DEFINITION Label="tribe_hamazans_of_the_dead_seed" Value="tribe_hamazans_of_the_dead_seed"/>
  <DEFINITION Label="tribe_icon_workshipers" Value="tribe_icon_workshipers"/>
  <DEFINITION Label="tribe_keepers" Value="tribe_keepers"/>
  <DEFINITION Label="tribe_kitin_gatheres" Value="tribe_kitin_gatheres"/>
  <DEFINITION Label="tribe_lagoon_brothers" Value="tribe_lagoon_brothers"/>
  <DEFINITION Label="tribe_lawless" Value="tribe_lawless"/>
  <DEFINITION Label="tribe_leviers" Value="tribe_leviers"/>
  <DEFINITION Label="tribe_master_of_the_goo" Value="tribe_master_of_the_goo"/>
  <DEFINITION Label="tribe_matisian_border_guards" Value="tribe_matisian_border_guards"/>
  <DEFINITION Label="tribe_night_turners" Value="tribe_night_turners"/>
  <DEFINITION Label="tribe_oasis_diggers" Value="tribe_oasis_diggers"/>
  <DEFINITION Label="tribe_pyromancers" Value="tribe_pyromancers"/>
  <DEFINITION Label="tribe_recoverers" Value="tribe_recoverers"/>
  <DEFINITION Label="tribe_renegades" Value="tribe_renegades"/>
  <DEFINITION Label="tribe_restorers" Value="tribe_restorers"/>
  <DEFINITION Label="tribe_root_tappers" Value="tribe_root_tappers"/>
  <DEFINITION Label="tribe_sacred_sap" Value="tribe_sacred_sap"/>
  <DEFINITION Label="tribe_sap_gleaners" Value="tribe_sap_gleaners"/>
  <DEFINITION Label="tribe_sap_slaves" Value="tribe_sap_slaves"/>
  <DEFINITION Label="tribe_scorchers" Value="tribe_scorchers"/>
  <DEFINITION Label="tribe_shadow_runners" Value="tribe_shadow_runners"/>
  <DEFINITION Label="tribe_siblings_of_the_weeds" Value="tribe_siblings_of_the_weeds"/>
  <DEFINITION Label="tribe_silt_sculptors" Value="tribe_silt_sculptors"/>
  <DEFINITION Label="tribe_slavers" Value="tribe_slavers"/>
  <DEFINITION Label="tribe_smuglers" Value="tribe_smuglers"/>
  <DEFINITION Label="tribe_the_arid_matis" Value="tribe_the_arid_matis"/>
  <DEFINITION Label="tribe_the_kuilde" Value="tribe_the_kuilde"/>
  <DEFINITION Label="tribe_the_slash_and_burn" Value="tribe_the_slash_and_burn"/>
  <DEFINITION Label="tribe_tutors" Value="tribe_tutors"/>
  <DEFINITION Label="tribe_water_breakers" Value="tribe_water_breakers"/>
  <DEFINITION Label="tribe_woven_bridles" Value="tribe_woven_bridles"/>
</TYPE>
