services:
  devcontainer:
    image: "ryzomcore/devcontainer"
    build: ./.devcontainer
    volumes:
      - ./:/tmp/ryzomcore

  tools:
    image: "ryzomcore/tools"
    build:
      context: .
      dockerfile: docker/Dockerfile
