services:
  devcontainer:
    image: "ryzomcore/devcontainer"
    build: ./.devcontainer

  web:
    image: bitnami/nginx:1.25
    volumes:
      - ./dev/nginx/conf.d:/opt/bitnami/nginx/conf/server_blocks
      - ./web:/app:ro
    ports:
      - 8080:80
    depends_on:
      - php

  php:
    image: bitnami/php-fpm:8.2
    volumes:
      - ./web:/app
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306

networks:
  default: