name: build
description: build
inputs:
  os:
    description: os
    required: true
  install-dir:
    description: install directory
    required: true
  build-dir:
    description: build directory
    required: true
  build-version:
    description: build version
    required: true
  image-group:
    description: image group
    required: true
  image-version:
    description: image version
    required: true
runs:
  using: composite
  steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "^3.29.5"

    - name: Dependencies Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install --yes \
          build-essential \
          libpng-dev \
          libjpeg-dev \
          libgif-dev libfreetype6-dev \
          freeglut3-dev \
          liblua5.2-dev libluabind-dev libcpptest-dev \
          libogg-dev libvorbis-dev libopenal-dev \
          libavcodec-dev libavformat-dev libavdevice-dev libswscale-dev libpostproc-dev \
          libmysqlclient-dev \
          libcurl4-openssl-dev libssl-dev \
          libsquish-dev \
          libgsf-1-dev \
          qtbase5-dev qttools5-dev qttools5-dev-tools

    - name: Install Dependency
      if: runner.os == 'Linux'
      shell: bash
      run: >
        sh ${{ inputs.build-dir }}/nel-*.sh
        --skip-license
        --include-subdir
        --prefix=${{ inputs.install-dir }}

    - name: Configure CMake
      if: runner.os == 'Linux'
      shell: bash
      run: cmake --preset ci-linux-ryzom

    - name: Build
      shell: bash
      run: cmake --build --preset ryzom

    - name: Package
      shell: bash
      run: cpack --preset ryzom -R "${{ inputs.build-version }}"
