<?php

$titre = "Racine du Savoir -";

$TITLE_kami = "LE SANCTUAIRE DE MA-DUK";

$texteDefault = "choisissez un texte dans le menu";

$menu1 = "LE MESSAGE DES HOMINS";
$menu2 = "LA CREATION D'ATYS";
$menu3 = "LA CREATION DES HOMINS";
$menu4 = "VERS L'AGE DES KAMIS";
$menu5 = "LES ENNEMIS DE MA-DUK";
$menu6 = "LA KARAVAN ET JENA";
$menu7 = "LES BIENFAITS DES KAMIS";
$menu8matis = "LES KAMIS ET LES MATIS";
$menu8tryker = "LES KAMIS ET LES TRYKERS";
$menu8fyros = "LES KAMIS ET LES FYROS";
$menu8zorai = "LES KAMIS ET LES ZORAIS";
$menu9 = "LE GRAND ORDRE DE MA-DUK";
$menu10 = "LES REVELATIONS DE MA-DUK";

$texte_stele_kami_1 = "<ul>Nous faisons partie intégrante du grand dessein de Ma-Duk, le Créateur qui a donné vie à Atys. Nous surveillons les ressources naturelles afin de préserver le fragile équilibre de la planète, pour que tous les homins puissent un jour atteindre l'âge Kami.</ul><br><ul>Homin, souviens-toi que ton destin est lié à celui d'Atys, et pas à la fausse prophétie de la Karavan. Ce sont des étrangers ici, des envahisseurs venus de loin pour voler nos ressources, et qui ne se soucient pas du bien d'Atys.</ul><br><ul>Comme toi, je suis né sur Atys ; ensemble nous devons la chérir et la protéger des dangers. En combattant la Goo, tu marcheras sur le chemin de l'éternelle félicité de Ma-Duk. Pour récompenser tes actes de mérite, nous conclurons des pactes de résurrection et de téléportation, et nous te montrerons les voies de la magie.</ul><br><ul>Pour la vie de notre planète, pour l'esprit de ton peuple, rends grâce au Créateur, choisis la voie de l'éternelle félicité de Ma-Duk !</ul>";


$texte_stele_kami_2 = "<ul>Depuis le début des temps, deux principes contraires forment la trame de l'univers : le Vide et l'énergie Créatrice, appelée aussi le Grand Géniteur. L'énergie crée à partir du Vide, et ne peut détruire le Vide. Le Vide se nourrit des créations de l'énergie, mais ne peut détruire l'énergie elle-même.</ul><br><ul> Aux confins de l'univers, au milieu du Vide, le Grand Géniteur fit naître la matière. Puis un monde unique naquit de cette matière en fusion : Atys. Le Grand Géniteur se fondit dans la jeune planète. Alors que l'angoisse du Vide menaçait d'étreindre Atys, le Géniteur dissémina les premières graines de l'existence. Les racines conquirent le ciel, les oiseaux prirent leur envol et les bêtes grouillèrent dans le miracle frénétique de la Vie.</ul><br><ul> Depuis les entrailles de la planète verte, le Grand Géniteur créa les Kamis et les dota d'esprit, d'un fragment de sa propre conscience, puis il les envoya surveiller sa création. Disposant de grands pouvoirs magiques, les Kamis remontèrent à la surface pour explorer les terres sous leur protection. Cachée au milieu des merveilles qu'offrait Atys, les Kamis découvrirent la Goo, née d'une infime parcelle du Vide qui s'était mêlée au souffle créateur du Grand Géniteur. La Goo dévorait lentement Atys. Les Kamis étaient désarmés face à elle, car ils ne pouvaient anéantir le Vide. Le salut allait venir d'autres êtres : les homins.</ul>";


$texte_stele_kami_3 = "<ul>Alors que les Kamis exploraient l'écorce encore jeune d'Atys, ils découvrirent de nouveaux êtres nés des graines de Ma-Duk. Ils s'appelaient homins. Des graines tombées dans les lacs limpides étaient nés les Trykers. Des graines enfouies dans les sables du désert chauffés par le soleil étaient nés les Fyros. Des graines enfouies dans l'humus des forêts étaient nés les Matis, et des graines tombées dans la sève remontant des racines profondes étaient nés les Zoraïs.</ul><br><ul> Les graines divines avaient germé lentement, et elles avaient donné naissance à des êtres particuliers, dotés d'un esprit indépendant. Grâce à cette conscience de leur propre essence, d'Atys et du Vide, les homins avaient le pouvoir de changer le monde. Car bien qu'ils puissent être détruits par le Vide, comme toute création de l'énergie, leur propre conscience du Vide leur conférait une résistance étonnante à sa corruption, et plus important encore, leur permettait d'agir sur la Goo.</ul><br><ul> Les Kamis rencontrèrent les homins, et leur confièrent une mission sacrée : combattre le fléau. Ainsi l'existence du Grand Géniteur fut-elle révélée, et ainsi les homins purent-ils prendre leur place dans l'univers.</ul>";


$texte_stele_kami_4 = "<ul>Lorsque le Grand Essaim submergea l'écorce, les Kamis firent la guerre aux kitins, afin qu'Atys retrouve la paix. Quand les kitins furent renvoyés dans les profondeurs, Ma-Duk, le Grand Géniteur, apparut à un sage homin, et lui révéla la voie de l'Illumination. Cette voie était le chemin vers la plénitude ultime de l'âge Kami, où les homins ne feront qu'un avec Ma-Duk et obtiendront la connaissance universelle.</ul><br><ul> En suivant les sentiers de l'Illumination, les fidèles franchissent des étapes les menant à d'autres dimensions. L'homin qui devient suffisamment méritant se réincarne dans un autre monde en tant que Kami, jusqu'à ce qu'il soit capable d'atteindre le bonheur suprême en tant que Kami-Ko. Il vivra alors dans l'âge Kami pour l'éternité.</ul><br><ul> Pour gagner du mérite, outre la préservation de la création de Ma-Duk et la vénération des Kamis, les croyants doivent répandre la bonne parole afin que les autres homins puissent avoir la possibilité d'atteindre l'illumination. C'est pourquoi les sages cherchent à libérer l'hominité des influences extérieures qui ne cherchent qu'à l'égarer.</ul>";


$texte_stele_kami_5 = "<ul>Le Vide est la force opposée au Grand Géniteur. La Goo en est la principale manifestation. De nombreux ennemis menacent l'équilibre d'Atys, et les fidèles des Kamis doivent être vigilants. La Karavan et leur fausse déesse Jena représentent le danger le plus pressant, car ils poussent les homins à renier la voie de Ma-Duk et à piller les ressources d'Atys. Ce sont des étrangers venus d'au-delà des étoiles, qui délaissent le combat contre la Goo au profit de leurs propres intérêts.</ul><br><ul> Elias Tryton est aussi un étranger. Il n'est apparu que brièvement sur Atys, et il semble un ennemi de la Karavan. Mais est-il pour autant un allié des Kamis ? Une grande prudence est nécessaire, car il est difficile de prévoir ses intentions.</ul><br><ul> Les kitins sont des êtres participant à la vie sur Atys, mais ils peuvent devenir une menace pour les homins, comme la tragédie du Grand Essaim l'a démontré. Les Kamis ont combattu les kitins par le passé, et ils interviendront à nouveau pour limiter leurs actions de destruction.</ul><br><ul> Certains homins sont considérés comme des ennemis : ils attaquent leurs semblables, s'approprient des ressources ou pire répandent le fléau de la Goo. Les foreurs avides de matières premières s'exposent à la Colère Kamique. Les adeptes de la Goo mettent en péril la planète toute entière, et les Kamis ne montreront aucune indulgence envers eux.</ul><br><ul> Enfin, la plus grande menace, qui ronge Atys depuis des siècles, est la Goo, la Corruption du Vide. Contaminant les créatures et les plantes, elle se répand insidieusement. Tous les homins doivent s'unir pour la combattre, sinon toute vie sur la planète est condamnée.</ul>";


$texte_stele_kami_6 = "<ul>Les membres de la Karavan sont des êtres venus d'ailleurs, d'un monde lointain au delà des étoiles. Ils se comportent comme si Atys leur appartenait : ils pillent les ressources et les retirent du cycle naturel de la planète. Ils utilisent des machines dont l'énergie perturbe la flore. Ils ne préoccupent pas de l'équilibre, ni de l'harmonie nécessaire à toute vie pour s'épanouir.</ul><br><ul> Ma-Duk n'a guère prêté attention à la Karavan dans les premiers âges d'Atys, la considérant comme une menace mineure. Mais les étrangers se sont mis à considérer les Kamis comme des créatures démoniaques, allant jusqu'à pousser les homins à les pourchasser. Ils ont converti de nombreux homins à leur culte envers Jena, les détournant de leur mission sacrée contre la Goo. Ainsi le fléau a pu s'étendre librement.</ul><br><ul> Jena, la fausse déesse de la Karavan, n'est en rien la divinité créatrice d'Atys. Elle a usurpé ce rôle afin de mieux asservir les homins. Ma-Duk pressent que Jena n'est pas une déesse, mais une manifestation du Vide, dont le but serait de réduire les homins en esclavage pour s'emparer d'Atys toute entière et la vider de sa substance. Jena est appelée par les homins kamistes l'Impératrice de la Nuit, nul doute que ses légions n'apporteront que les ténèbres et la mort.</ul><br><ul> Les homins karavaniers posent un problème aux Kamis. Les disciples de Ma-Duk préfèrent convertir des homins plutôt que les punir, mais ils ne peuvent les contraindre. Ceux qui ont choisi de suivre les chemins obscurs de Jena veulent attirer d'autres homins dans les ténèbres, et les Kamis ne permettront pas cela.</ul>";


$texte_stele_kami_7 = "<ul>Les Kamis guident les homins : ils leur ont révélé leur destinée et leur place dans l'univers. Ils les mènent sur les chemins de l'Illumination afin qu'ils parviennent à l'âge Kami ; ils ont protégé les ordres religieux kamistes afin que les homins puissent eux aussi guider leurs frères vers la connaissance suprême.</ul><br><ul> Les Kamis aident les homins : ils ressuscitent leurs esprits selon la volonté de Ma-Duk. Ils leur proposent des pactes leur permettant de se téléporter ou de dissiper leur faiblesse lorsqu'ils sont ramenés à la vie. Ils les assistent dans leur lutte contre la Goo, la Corruption du Vide, qui menace d'engloutir Atys tout entière. Dans le passé, les Kamis ont combattu les kitins lors du Grand Essaim, mettant fin à l'invasion. Ils ont aussi aidé les homins à rebâtir leurs civilisations, en leur permettant d'extraire de grandes quantités de ressources.</ul><br><ul> Les Kamis instruisent les homins : ils leur ont enseigné les secrets de la magie, ce qui leur a permis d'accroître leur puissance et leur connaissance du monde. Ils leur apprennent à respecter les ressources d'Atys, afin que l'équilibre soit préservé et que les homins aient toujours de quoi subsister.</ul><br><ul> Les Kamis veillent sur les homins : Ils luttent contre la Karavan qui surexploite Atys à ses fins personnelles, et qui compte réduire les homins en esclavage. Ils surveillent les kitins, afin que les homins ne soient plus menacés. Les Kamis œuvrent pour l'harmonie et la communion entre les homins et Atys. Ils veulent préserver le présent et l'équilibre si fragile contre les influences néfastes, qui ne mènent qu'à la destruction et la fin de toute chose.</ul>";


$texte_stele_kami_8matis = "<ul>Les Matis ont toujours été fascinés par les forces de la Nature. Mais leur volonté de domination a mis une barrière entre eux et les Kamis. Dans le passé, les disciples de Ma-Duk ont tenté plusieurs fois de briser cette barrière, sans succès. L'omniprésence de la Karavan auprès des Matis a rendu les tentatives de rapprochement encore plus difficiles.</ul><br><ul> La meilleure occasion se présenta lorsque les Kamis vinrent à la rencontre des Matis afin de leur apprendre la magie. Malgré la désapprobation de la Karavan, les Matis se montrèrent des élèves studieux et audacieux. Mais très vite, ils tentèrent d'utiliser la magie pour soumettre les plantes à leur volonté, dans le but de créer de nouvelles espèces. Les Kamis réprouvèrent cette attitude, et ils finirent par se détourner de leurs apprentis trop ambitieux.</ul><br><ul> Les Matis, manipulés par la Karavan, ont été jusqu'à pourchasser les Kamis, dans le but de les livrer aux élus de Jena. Les Kamis se sont fait discrets, ne désirant pas punir trop sévèrement les Matis pour leur inconscience. Car les disciples de Ma-Duk n'ont jamais perdu l'espoir de guider les Matis sur la voie de l'Illumination.</ul><br><ul> Avec leurs connaissances et leur maîtrise de la Nature, les Matis peuvent devenir de précieux gardiens pour Atys.</ul>";


$texte_stele_kami_8tryker = "<ul>Les Trykers furent les premiers homins à entrer en contact avec les Kamis. La nature pacifique et insouciante du peuple des lacs, ainsi que leurs préoccupations écologiques pour l'environnement plaisaient aux Kamis. Mais suite à une vague d'incendies dans les anciens déserts, les Kamis se réfugièrent dans la sécurité des jungles d'Atys pour se régénérer, et furent apaisés par la quiétude des Zoraïs.</ul><br><ul> Désorientés, car ressentant l'absence des Kamis, les Trykers se perdirent dans les chemins tracés par la Karavan. Les Kamis ont tenté de ramener les Trykers sur les chemins de Ma-Duk en leur apprenant à faire de la magie. Au début, les Trykers ont pris cela davantage comme un jeu et se sont montrés des élèves peu appliqués. Mais sous l'influence des maîtres Zoraïs qui accompagnaient les Kamis, ils se sont mis au travail, et ils ont progressé dans les différents domaines des arcanes.</ul><br><ul> Inventeurs dans l'âme, ils ont fini par créer leur propre magie, basée sur les forces du vent et les ondes de choc. Les Trykers ont traversé de nombreuses épreuves, et ils se sont révélés des combattants obstinés, prêts à mourir pour leur liberté. Les Kamis ont toujours voulu les rallier à leur cause, car comme eux, les Trykers sont très attachés aux splendeurs des grands lacs d'Atys.</ul>";


$texte_stele_kami_8fyros = "<ul>Très tôt, les Kamis remarquèrent chez les Fyros une aptitude particulière. Le peuple du désert ne craignaient tout simplement pas l'un des grands fléaux d'Atys : le feu. Les Kamis tentèrent de gagner leur coeur et de les rallier à leur cause. Les Fyros se méfièrent tout d'abord de ces créatures étranges. Puis le sauvetage de l'empereur Arispotle par un Kami scella une nouvelle amitié et marqua la naissance d'un profond respect dans le coeur des Fyros.</ul><br><ul> Les Fyros se tournèrent progressivement vers les Kamis pour apprendre d'eux les secrets de la magie. L'empereur fut le premier homin à utiliser la téléportation kamique. Les Fyros expérimentèrent une magie utilisant le pouvoir du feu, manipulant l'énergie primordiale du désert. En retour des faveurs des Kamis, les Fyros ont garanti une protection contre le feu du Dragon, et ont accepté de se battre pour le dominer en cas d'incendie.</ul><br><ul> Formidables guerriers, les Fyros ont toujours été prêts à se mobiliser pour une cause juste. Bien qu'ils aient préféré leurs propres cultes kamistes au Grand Ordre de Ma-Duk, ils ont répondu à de nombreuses reprises aux appels des adeptes des Kamis, quelles que soient leurs origines.</ul>";


$texte_stele_kami_8zorai = "<ul>Dans les temps anciens, les Kamis, qui s'étaient réfugiés dans la jungle après les grands incendies, rencontrèrent les Zoraïs, et leur confièrent la mission sacrée de lutter contre la Goo. Un lien très fort se créa entre esprits de la nature et Zoraïs, qui conduisit à la fondation du premier culte voué aux Kamis, incarnations vivantes de l'énergie pure qui a créé Atys. Les Kamis créèrent les masques de parenté pour les Zoraïs, comme symbole de ce lien. Les Kamis initièrent les Zoraïs aux secrets de la magie. Les premiers magiciens firent leur apparition sur Atys, réalisant des miracles.</ul><br><ul> Des archimages zoraïs ont ensuite étudié les mystères des arcanes, employant une écriture sacrée pour transmettre leur savoir. Ils ont découvert les pouvoirs de la foudre, et ont créé la première magie de peuple, la magie de l'électricité.</ul><br><ul> Utilisant leur magie et leur connaissance du magnétisme, les Zoraïs ont combattu la Goo qui rongeait les jungles d'Atys. Au nom des Kamis, ils ont courageusement affronté le fléau. Ils se sont méfiés de la Karavan, qui éloignait les homins du chemin de l'Illumination.</ul><br><ul> Leur foi inébranlable a fait des Zoraïs les guerriers sacrés de Ma-Duk.</ul>";


$texte_stele_kami_9 = "<ul>En ce lieu a été érigé un sanctuaire du Grand Ordre de Ma-Duk. Ici, les homins kamistes peuvent méditer et écouter le battement du coeur d'Atys. Ils peuvent communier avec le Grand Géniteur pour trouver les réponses qui les guideront sur le chemin de l'Illumination.</ul><br><ul> Dans les temps anciens, les Zoraïs ont fondé les premiers cultes kamistes. Ces cultes élevaient des temples à la gloire des Kamis et du Kami Suprême. Mais le Grand Essaim a fait table rase des organisations religieuses du passé. Les cultes ont survécu, mais pas leurs églises.</ul><br><ul> Souhaitant communier à nouveau avec tous ses fidèles, Ma-Duk s'est révélé au Grand Sage Hoï-Cho pour fonder un nouveau culte kamiste, le Grand Ordre de Ma-Duk. Homin, sois le bienvenu dans le sanctuaire de Ma-Duk ! Le Grand Géniteur, le Kami Suprême t'y accueille, comme il t'accueillera en son sein lorsque tu atteindras l'âge Kami et la connaissance universelle.</ul>";


$texte_stele_kami_10 = "<ul>Ici sont écrites les Huit Révélations de Ma-Duk, traduites en paroles sacrées, telles qu'elles furent énoncées au Grand Sage Hoï-Cho par Ma-Duk lui-même, puis retranscrites au début du Livre des Révélations.</ul><br><ul> Première Parole : Je suis Ma-Duk, le créateur qui a donné vie à Atys. Je ne forme qu'un avec les Kamis qui font partie de moi. Vous devez donc les adorer comme vous adorerez votre géniteur.</ul><ul> Deuxième Parole : Vous suivrez le chemin de l'Illumination Kami, il vous élèvera jusqu'à atteindre l'âge Kami.</ul><ul> Troisième Parole : Pour atteindre l'âge des Kamis et ne former qu'un avec le Géniteur, vous devez suivre le chemin de l'Illumination pour devenir méritants.</ul><ul> Quatrième Parole : Devenez méritants par votre loyauté et vos soins à Atys, elle se détache de mon sein.</ul><ul> Cinquième Parole : Si vous suivez le chemin de l'Illumination Kami, je raviverai votre esprit si vous mourez avant d'avoir atteint le mérite ultime.</ul><ul> Sixième Parole : Ne vous laissez pas tenter par de faux dieux, ils ne peuvent être de composition atysienne, ils n'ont pas leur place dans mon dessein, ils sont sources de déséquilibres.</ul><ul> Septième Parole : Soyez l'ennemi de l'excès et votre voyage sur le chemin de l'Illumination Kami comblera entièrement le vide en vous.</ul><ul> Huitième Parole : Tout comme j'ai semé les graines de l'existence au vent pour préparer votre vie sur Atys, vous devez répandre l'Illumination Kami aux quatre coins du monde.</ul>";
?>