<?php

$titre = "Knowledge Root -";

$TITLE_kami = "THE SANCTUARY OF MA-DUK";

$texteDefault = "choose a text in the menu";

$menu1 = "THE MESSAGE OF THE KAMIS";
$menu2 = "THE CREATION OF ATYS";
$menu3 = "THE CREATION OF THE HOMINS";
$menu4 = "THE AGE OF KAMIHOOD";
$menu5 = "THE ENEMIES OF MA-DUK";
$menu6 = "THE KARAVAN AND JENA";
$menu7 = "THE DEEDS OF THE KAMIS";
$menu8matis = "THE KAMIS AND THE MATIS";
$menu8tryker = "THE KAMIS AND THE TRYKER";
$menu8fyros = "THE KAMIS AND THE FYROS";
$menu8zorai = "THE KAMIS AND THE ZORAI";
$menu9 = "THE GREAT ORDER OF MA-DUK";
$menu10 = "THE REVELATIONS OF MA-DUK";

$texte_stele_kami_1 = "<ul>We are an integral part of the great design of Ma-Duk, the Life Giver that created Atys. We stand vigil over her natural resources to preserve the fragile balance, so that all homins may attain enlightenment in Kamihood one day.</ul><br><ul>Remember, your destiny is linked to the life of Atys, homin, and not to the false prophecy of the Karavan. They are foreigners here, invading creatures come from afar to steal our resources, they care not a bit for the welfare of Atys.</ul><br><ul>I, like you, was born on Atys, together we must cherish it and keep it from danger. By clearing away the Goo you will gain merit to enter the pathway to the eternal bliss of Ma-Duk. In return for your deeds of merit we will offer you pacts to restore your life energy, and to teleport through the corridors of time, and we will teach you the ways of magic.</ul><br><ul>For the life of our planet, for the spirit of your people, give praise to the Life Giver, choose the pathway to the eternal bliss of Ma-Duk!</ul>";
 

$texte_stele_kami_2 = "<ul>From the beginning of time, two opposing principles formed the matrix of the universe: the Void and the Creative Energy, also known as the Life Giver. The Energy creates from the Void, and cannot destroy the Void. The Void is nourished by the Energy's creations, but cannot destroy the Energy itself.</ul><br><ul>Far across the universe, in the midst of the Void, the Life Giver brought forth matter. And then there was a great fusion that gave birth to a unique world: Atys. Then the great Life Giver merged with the young planet. While the anguish of the Void threatened to hold it in its grip, the Life Giver sowed the first seeds of existence. The primeval roots sent branches into the sky, birds took wing and beasts teemed in a frenzy of miraculous Life.</ul><br><ul>From the bowels of the green planet, the great Life Giver brought forth the Kamis and endowed them with spirit, a fragment of his own consciousness, then sent them forth to watch over his creation. Gifted with vast magical powers, the Kamis came to the surface to explore the lands under their protection. Hidden in the midst of the wonders of Atys, the Kamis encountered the Goo, born from an infinitesimal particle of Void that was mixed in with the creative breath of the great Life Giver. The Goo was gradually devouring Atys. The Kamis were helpless in the face of this menace, because they could not destroy the Void. Salvation would have to come from other beings: the homins.</ul>";


$texte_stele_kami_3 = "<ul>While the Kamis explored the still-young Bark of Atys, they discovered new beings born from the seeds sown by Ma-Duk. They were called homins. Seeds that had fallen into the clear lakes had produced the Trykers. Seeds that had burrowed into the sun-baked desert sands gave birth to the Fyros. Seeds that had worked down into the humus of the forests grew into the Matis, and seeds fallen into the sap that rises from the deep tap roots became the Zoraïs.</ul><br><ul>The divine seeds had germinated slowly and had given birth to some very special beings, endowed with an independent spirit. Because they were conscious of their own essence, and of Atys and the Void, the homins had the power to change the world. Because, although they can be destroyed by the Void, like any of the Energy's creations, their own conscious awareness of the Void conferred on them an astonishing ability to resist its corruption and, even more importantly, to effectively fight the Goo.</ul><br><ul>The Kamis met with the homins and entrusted them with a sacred mission of fighting this plague. And thus was the existence of the great Life Giver revealed, and the homins were able to take their place in the universe.</ul>";


$texte_stele_kami_4 = "<ul>When the Great Swarming covered the Bark, the Kamis made war on the Kitins in order to restore peace to Atys. When the Kitins were forced back underground, Ma-Duk, the great Life Giver, appeared to a homin sage and revealed to him the path of Enlightenment. This was the path to the ultimate fulfillment of the age of Kaminhood, where homins are at one with Ma-Duk and obtain universal knowledge.</ul><br><ul>By following the pathways of Enlightenment, the faithful take the steps that lead to other dimensions. The homin who demonstrates sufficient merit reincarnates into another world as a Kami, until he is capable of attaining the supreme blissful state of Kami-Ko. At that stage, he enters into Kaminhood for all of eternity.</ul><br><ul>To gain such merit, in addition to preserving Ma-Duk's creation and venerating the Kamis, believers must spread the good word so that other homins will have a chance to attain enlightenment too. And this is why the sages seek to liberate hominity from outside influences that seek only to lead it astray.</ul>";


$texte_stele_kami_5 = "<ul>The Void is the force that opposes the great Life Giver. Goo is its most common manifestation. There are many enemies that threaten the equilibrium of Atys, and Kamis followers must be vigilant. The Karavan and their false goddess Jena are the most imminent danger, because they pressure the homins to renounce the way of Ma-Duk and they pillage the resources. They are foreigners who come from beyond the stars, and they ignore the battles against Goo in order to pursue their own interests.</ul><br><ul>Elias Tryton is also a foreigner. He only appeared briefly on Atys, and seems to be an enemy of the Karavan. But does that make him a friend of the Kamis? Extreme caution is required, because it is very difficult to predict his intentions.</ul><br><ul>The Kitins are beings that participate in life on Atys, but they can become a threat to homins, as we saw in the tragedy of the Great Swarming. The Kamis have fought back the Kitins before, and they are prepared to do so again to keep their destructive actions in line.</ul><br><ul>Some homins are seen as enemies too: they attack their own kind, steal resources or, worse, they spread the plague of Goo. Avid foragers of raw materials expose themselves to the wrath of the Kamis. Those who nurture the Goo imperil the entire planet, and the Kamis show them no pity.</ul><br><ul>Indeed, the greatest menace of all that has been devouring Atys for centuries is the Goo - the Corruption of the Void. It contaminates creatures and plants and spreads insidiously. All homins must unite to fend it off, or else all life on the planet will be doomed.</ul>";


$texte_stele_kami_6 = "<ul>The members of the Karavan are beings that have come from elsewhere, from a distant world beyond the stars. They behave as if Atys belonged to them. They pillage its resources and pull them out of the planet's natural cycles. They use machines that emit energies that disturb the flora. They do not care about equilibrium nor about the harmony that is necessary for all life to flourish.</ul><br><ul>Ma-Duk scarcely paid attention to the Karavan in the early ages of Atys, seeing them as a minor threat. But the Foreigners began to view the Kamis as demonic creatures, going so far as to urge homins to hunt them down. They have converted many homins to their devotion to Jena, turning them away from their sacred mission to fight the Goo. So the plague has been allowed to expand unchecked.</ul><br><ul>Jena, the false goddess of the Karavan, is not the divine creator of Atys by any means. She has usurped this role the better to enslave homins. Ma-Duk knows that Jena is not a goddess, but a manifestation of the Void that seeks to subjugate the homins in order to take Atys over completely and drain it of all its substance. The Kamist homins call Jena the Empress of the Night, and have no doubt that her legions bring only shadows and death.</ul><br><ul>The Karavan homins raise a quandary for the Kamis. These disciples of Ma-Duk would prefer to convert the homins rather than punish them, but they cannot do so by force. Those that have chosen to follow the dark ways of Jena seek to attract other homins into the shadows, and the Kamis will never allow this.</ul>";


$texte_stele_kami_7 = "<ul>The Kamis guide the homins. They have revealed to them their destiny and their place in the universe. They lead them on the paths of Enlightenment so that they may attain Kaminhood. They have protected the Kamist religious orders so that the homins may also guide their brothers towards supreme knowledge.</ul><br><ul>The Kamis help the homins: they resuscitate their spirits, in keeping with the will of Ma-Duk. They make pacts with them so they can be teleported, or to strengthen their weakness when they are restored to life. They assist them in their battle with the Goo, the Corruption of the Void, which threatens to engulf all of Atys. In the past, the Kamis fought against the Kitins during the Great Swarming, and put an end to their invasion. They also helped the homins to rebuild their civilization, allowing them to extract large quantities of natural resources.</ul><br><ul>The Kamis also teach the homins: They have taught them the secrets of magic, which has enabled them to increase their power and their knowledge of the world. They teach them to respect the resources of Atys, so that balance will be maintained and homins will always have enough to survive.</ul><br><ul>The Kamis watch over the homins: they fight the Karavan who exploit Atys for their personal gain and who intend to reduce the homins to slavery. They watch out for the Kitins, so that the homins won't be threatened again. The Kamis work to maintain harmony and communion between the homins and Atys. They wish to preserve the present and the fragile balance against harmful influences that only lead to destruction and the end of all things.</ul>";


$texte_stele_kami_8matis = "<ul>The Matis have always been fascinated by the forces of Nature. But their desire for domination has put a barrier between them and the Kamis. In the past, the disciples of Ma-Duk made many attempts to break down this barrier, without success. The omnipresence of the Karavan wherever the Matis go has made any further attempts at rapprochement even more difficult.</ul><br><ul>The best opportunity arose when the Kamis met with the Matis in order to teach them magic. Despite the disapproval of the Karavan, the Matis turned out to be dedicated and daring students. But they very quickly attempted to use magic to make plants submit to their will, in the hope of creating new species. The Kamis rebuked this attitude and they ended up turning away from their overly ambitious apprentices.</ul><br><ul>The Matis, who have been manipulated by the Karavan, have gone so far as to hunt down the Kamis in order to hand them over to the Elect of Jena. The Kamis have become very discreet, not wishing to inflict too much punishment of the Matis for their thoughtlessness. Since the disciples of Ma-Duk never lost their hope of steering the Matis onto the path to Enlightenment.</ul><br><ul>With their knowledge and their mastery of Nature, the Matis could very well become valued guardians of Atys.</ul>";


$texte_stele_kami_8tryker = "<ul>The Trykers were the first homins to make contact with the Kamis. The peaceful, carefree nature of the lake people and their preoccupation with the ecology of the environment were all pleasing factors to the Kamis. But after a series of fires in the ancient deserts, the Kamis took refuge in the jungles of Atys in order to regenerate, and they were calmed by the serenity of the Zoraïs.</ul><br><ul>Feeling disoriented without the Kamis, the Trykers went astray following the ways of the Karavan. The Kamis tried to bring them back onto the path of Ma-Duk by teaching them magic. At first, the Trykers took this as more of a game, and did not prove to be good students. But under the influence of the Zoraïs masters who came along with the Kamis, they began to work at it and made progress in various domains of the arcane.</ul><br><ul>With an inventive gift deep in their souls, they ended up creating their own form of magic, based on the forces of the wind and on shock waves. The Trykers went through many trials and showed themselves to be obstinate fighters, ready to die for their freedom. The Kamis still wished to rally them to their own cause because, just like them, the Trykers have a strong attachment to the splendors of the great lakes of Atys.</ul>";

$texte_stele_kami_8fyros = "<ul>Very early on, the Kamis noticed that the Fyros had a special talent. These desert people simply had no fear of one of the greatest threats to Atys: fire. The Kamis attempted to win their hearts and rally them to the cause. At first, the Fyros were wary of these strange creatures. But then when the emperor Arispotle was saved by a Kami, a new friendship was sealed and the Fyros were filled with a heartfelt respect for the Kamis.</ul><br><ul>The Fyros gradually turned towards the Kamis to learn the secrets of magic. The emperor was the first homin to use Kamic teleportation. The Fyros were working on a kind of magic that uses the power of fire, and manipulating the primordial energy of the desert. In return for the Kamis' favors, the Fyros promised to protect them from the Dragon's fire, and agreed to fight to defeat it and protect them in case of fire. The Fyros are fearsome warriors and have always been willing to fight for a just cause.</ul><br><ul>Although they prefer their own Kamist worship practices to the Great Order of Ma-Duk, they have often responded to the calls from the Kamis' followers, regardless of origin.</ul>";

$texte_stele_kami_8zorai = "<ul>In the old days, the Kamis had taken refuge in the jungle after the great fires, where they met the Zoraïs and entrusted them with the sacred mission to fight the Goo. The spirits of Nature developed very close ties with the Zoraïs, leading to the early devotions to the Kamis, who were the living incarnation of the pure energy that created Atys. The Kamis created the masks linking them to the Zoraïs, as a symbol of this spiritual bond. The Kamis initiated the Zoraïs into the secrets of magic. The first magicians appeared on Atys, performing miracles.</ul><br><ul>Then the Zoraïs' high Magi began to study the arcane mysteries, using sacred writing to transmit their knowledge. They learned the secret powers of lightning, and created the first peoples' magic, the magic of electricity.</ul><br><ul>Using their magic and their knowledge of magnetism, the Zoraïs fought the Goo that was eating away at the forests of Atys. In the name of the Kamis, they bravely battled this plague. They were wary of the Karavan, who led homins away from the path of Enlightenment.</ul><br><ul>Their unshakeable faith has made the Zoraïs the sacred warriors of Ma-Duk.</ul>";


$texte_stele_kami_9 = "<ul>On this site, a sanctuary of the Great Order of Ma-Duk has been erected. Here, Kamist homins may meditate and listen to the heartbeat of Atys. They may commune with the great Life Giver to find the answers that will guide them on the paths of Enlightenment. </ul><br><ul>In ancient times, the Zoraïs founded the first of the Kamist religions. They raised temples to the glory of the Kamis and the supreme Kami. But the Great Swarming wiped out all of the religious organizations of the past. The worship endured, but without the churches.</ul><br><ul>Desiring to commune with all his faithful once again, Ma-Duk revealed himself to the Great Sage Hoï-Cho in order to found a new Kamist religion, the Great Order of Ma-Duk. Homin, we welcome you to the sanctuary of Ma-Duk! The great Life Giver, the supreme Kami, welcomes you, just as he will welcome you into his heart when you attain Kamihood and universal knowledge.</ul>";


$texte_stele_kami_10 = "<ul>Here are written the Eight Revelations of Ma-Duk, translated into sacred words, as they were given to the Great Sage Hoï-Cho by Ma-Duk himself, then transcribed into the beginning of the Book of Revelations.</ul><br><ul>The First Word: I am Ma-Duk, the creator who gave life to Atys. I am at one with the Kamis and they are a part of me. You must therefore adore them as you adore your creator.</ul><ul>The Second Word: You shall follow the Kami path of Enlightenment, which will lead you to attain Kamihood.</ul><ul>The Third Word: In order to attain Kamihood and become as one with your creator, the Life Giver, you must follow the path of Enlightenment to become meritorious.</ul><ul>The Fourth Word: Become meritorious through our loyalty and your attentions to Atys, who is separating from my heart.</ul><ul>The Fifth Word: If you follow the Kami path of Enlightenment, I will restore you to life if you should die before attaining the ultimate merit.</ul><ul>The Sixth Word: Do not be tempted by false gods, they cannot be of Atysian stock, and they have no place in my design, they only create imbalances.</ul><ul>The Seventh Word: Oppose excess and your journey on the Kami path of Enlightenment will completely fill the void in you.</ul><ul>The Eighth Word: Just as I have sown the seeds of existence upon the wind in order to prepare your life on Atys, so you must sow the ways of Kami Enlightenment to all the corners of the world.</ul>";
?>