<?php

$titre = "Colonne du Savoir -";

$TITLE_karavan = "LE TEMPLE DE JENA";

$texteDefault = "choisissez un texte dans le menu";

$menu1 = "LE MESSAGE DE LA KARAVAN";
$menu2 = "LA NAISSANCE DE L'HOMINITE";
$menu3 = "LES CENDRES DRACONIQUES";
$menu4 = "LA PROPHETIE";
$menu5 = "LES ENNEMIS DE JENA";
$menu6 = "L'IMPOSTURE DE MA-DUK";
$menu7 = "LES BIENFAITS DE LA KARAVAN";
$menu8matis = "LA KARAVAN ET LES MATIS";
$menu8tryker = "LA KARAVAN ET LES TRYKER";
$menu8fyros = "LA KARAVAN ET LES FYROS";
$menu8zorai = "LA KARAVAN ET LES ZORAI";
$menu9 = "L'EGLISE DE LA LUMIERE";
$menu10 = "LES COMMANDEMENTS DE JENA";

$texte_stele_karavan_1 = "<ul>Nous sommes les disciples de Jena, déesse d'Atys et Mère de l'hominité. Nous avons été envoyés pour prendre soin de Ses enfants, leur montrer le chemin dans les moments d'égarement et les préparer à l'élévation divine au Jour du Jugement.Sois-en sûr, ce jour est proche, homin !</ul><br><ul> Adore Jena et elle te guidera à travers les portes du paradis vers un monde d'abondance, loin du Dragon et des kitins, loin des Kamis maléfiques ! Prends garde, ces créatures sont plus concernées par les plantes infectées que par la vie homine. Elles prendront possession de ton âme pour nourrir leur égoïste désir d'auto préservation si tu les laisses faire !</ul><br><ul>N'oublie jamais : comme nous, tu as été créé à l'image de Jena, et la foi que tu lui portes doit emplir ton coeur si tu veux recevoir la grâce divine lorsque Atys ne pourra plus supporter la vie homine.</ul><br><ul>En échange de tes offrandes, elle nous a investis de l'autorité divine pour ressusciter ton esprit, te téléporter vers des terres lointaines et t'apprendre à utiliser notre technologie.</ul><br><ul>Si, comme nous, tu estimes qu'une vie homine est plus importante qu'une simple plante, ouvre ton coeur à Jena, et Elle sera ton Sauveur !</ul>";


$texte_stele_karavan_2 = "<ul>Il est dit que dans des temps reculés, les ancêtres des homins habitaient une planète appauvrie. Le Grand Dragon, le prince des ténèbres, vint les séduire par des visions d'eaux pures et de terres fertiles. Il les mena sur la terre promise d'Atys, où il cacha le soleil, plongeant la planète dans le froid et l'obscurité. En fait de pays merveilleux et de liberté, les peuples trompés par le Dragon connurent la désolation et l'esclavage.</ul><br><ul>Jena, Déesse du soleil et Mère de toute vie, leur apporta la délivrance. La créatrice d'Atys eut vent de la perfidie du Dragon et le remplit d'un feu éternel. Ainsi, le dragon ne pourrait plus maintenir un climat froid et éteindre la lumière de la vie. La Déesse fit ensuite renaître la lumière, provoquant la Poussée Verte et la transformation d'Atys en une incroyable planète végétale. Les peuples esclaves furent purifiés et libérés du Dragon, qui se retira dans les profondeurs : ainsi Jena fit-elle naître l'hominité.</ul><br><ul>Jena s'adressa alors à ses disciples, les élus de la Karavan, qui voyageaient parmi les étoiles et avaient assisté au combat contre le Dragon. La Déesse leur confia la tâche de guider les homins afin qu'ils prospèrent, à l'abri de l'influence du Dragon qui reposait endormi dans les entrailles d'Atys. La Karavan aida les homins à s'installer en différents lieux de la planète, afin que chacun puisse construire à sa façon le futur d'Atys.</ul>";


$texte_stele_karavan_3 = "<ul>Le Dragon a été vaincu, mais il a marqué Atys de son empreinte. Lorsque Jena remplit le Dragon ténébreux du feu du soleil, la Bête se tordit de douleur et cracha son souffle enflammé sur toute la planète glacée. Sous l'action de son souffle, le limon originel d'Atys, que le Dragon avait enfoui sous des gangues de glace, réapparut. Alors Jena inonda la planète de sa Lumière, et le sol fertile germa en un miracle frénétique.</ul><br><ul>Le Dragon se retrouva pris dans les racines d'Atys lors de la Poussée Verte. Il tenta de se dégager en crachant le feu du soleil, réduisant en cendres le bois nouveau-né, mais le miracle de la Vie était trop fort, et le feu fut étouffé sous le poids des frondaisons. épuisé, vaincu, le Dragon se réfugia dans l'obscurité d'une caverne végétale, au plus profond des entrailles de la planète, et finit par s'endormir. Les cendres issues du feu du Dragon furent dispersées sur toute la surface d'Atys. Elles se mêlèrent aux rivières de sève, au pollen des fleurs géantes, aux spores des champignons ancestraux.</ul><br><ul>Elles s'incrustèrent dans les lignes de l'écorce primordiale. Lorsque la Poussée Verte arriva à son terme, elles étaient partout. Et elles contenaient en elles les restes de la colère du Dragon. Tous les êtres d'Atys portent en eux des cendres draconiques. Elles sont dans l'air, dans les plantes, dans la pluie. Elles sont invisibles, sans odeur ni saveur, infimes poussières respirées par les créatures vivantes.</ul><br><ul>Les élus de la Karavan, dont la pureté n'a pas été entachée par le Dragon, se protègent des cendres en s'enfermant dans des armures sacrées. Respirer les cendres draconiques reviendrait pour eux à s'ouvrir au souffle du Dragon.</ul>";


$texte_stele_karavan_4 = "<ul>Lorsque Jena confia à ses disciples la mission de guider les homins, une prophétie fut énoncée. Un jour, le Grand Dragon endormi dans les profondeurs d'Atys s'éveillera. Consumé par un éternel feu intérieur, il mettra fin à ses tourments et à son existence en recrachant tout le feu de son corps, ce qui causera la fin d'Atys. Le Jour du Jugement, Jena et ses prophètes sacrés venus d'au-delà des étoiles seront là. Ils sauveront les homins fidèles aux enseignements de la Déesse et les emporteront dans le ciel pour rejoindre les élus de la Karavan.</ul><br><ul>Les homins qui persisteront à nier la toute puissance de Jena périront dans les flammes du Dragon et disparaîtront avec lui. Alors ceux qui ont été sauvés seront transportés vers un nouveau monde d'abondance, où ils vivront dans la lumière de la Déesse pour l'éternité.</ul><br><ul>Seule Jena sait quand le dragon se réveillera pour exhaler son ultime souffle destructeur. Chaque jour qui passe rapproche Atys de son inéluctable fin. Mais cette fin ne doit pas être hâtée par l'imprudence.</ul><br><ul>Aussi la Karavan veille-t-elle à ce que ses fidèles ne s'aventurent pas dans les couches les plus profondes d'Atys. Descendre dans les entrailles de la planète est se rapprocher du Dragon, dont le sommeil tourmenté est hanté par des rêves effrayants. Ces rêves de ténèbres peuvent éloigner la lumière de Jena du cœur des homins et dévorer leur âme. La Karavan autorise toutefois ses adeptes à descendre dans les profondeurs supérieures des Primes Racines, s'ils ont une raison valable de le faire.</ul>";


$texte_stele_karavan_5 = "<ul>De sombres forces existent dans l'univers, et Atys n'est pas à l'abri de leur influence. Pour libérer ses enfants, Jena a déjà livré bataille contre le Dragon malfaisant.</ul><br><ul>D'autres ennemis guettent dans l'ombre, et les fidèles de la Déesse doivent être mis en garde contre eux. Les Kamis et leur chef Ma-Duk sont la plus grande menace pour l'avenir de l'hominité. Ces démons cherchent à posséder les homins pour les asservir et les transformer en serviteurs dociles, qui seront sacrifiés pour assurer la survie de Ma-Duk.</ul><br><ul>élias Tryton, un prophète déchu qui a été corrompu par le Dragon, a fait sa réapparition sur Atys et tente d'influencer les homins. Il est responsable du Grand Essaim : déchaînant la colère des kitins pour anéantir les civilisations homins, il a ouvert des portails magiques pour envoyer les survivants dans les ténèbres des Primes Racines. Il a sous-estimé la puissance de la Karavan, qui a mis fin à l'invasion, et a préservé la lumière de Jena dans le cœur des homins exilés.</ul><br><ul>Les kitins sont une autre menace pour l'hominité. Ces monstres, qui ont balayé les anciennes civilisations lors du grand Essaim, sont nés des écailles du Dragon. Ils ont prospéré dans les entrailles d'Atys avant de se répandre sur l'écorce. La Karavan surveille de près les mouvements de l'Essaim et se tient prête à intervenir en cas d'invasion massive.</ul><br><ul>Les primitifs sont des créatures dégénérées, nées d'homins corrompus par le Dragon. Ils sont très agressifs et attaquent tous les homins qui croisent leur chemin. Leur nombre tend à s'accroître, et certains clans de primitifs plus intelligents ont été aperçus. La Karavan ne peut laisser de telles créatures nuire aux peuples dont elle a la charge.</ul><br><ul> La Goo est une menace qui n'a pas échappé aux élus de Jena. Elle dévore lentement la planète, polluant les ressources d'Atys. Aussi la Karavan veut-elle s'en débarrasser. Dans ce but, elle l'étudie afin d'en apprendre plus sur ses faiblesses. Enfin, il arrive que des homins soient des ennemis pour leurs semblables.</ul><br><ul>La Karavan se montre souvent bienveillante, mais elle ne peut tolérer que ses fidèles soient la proie de fanatiques qui n'hésitent pas à tuer et piller. Les homins karavaniers doivent s'unir sous la lumière de Jena pour lutter contre leurs ennemis : ainsi seront-ils assurés de la victoire.</ul>";


$texte_stele_karavan_6 = "<ul>Les Kamis sont des démons nés des cendres draconiques, omniprésentes sur Atys. Une grande part de l'essence de ces étranges créatures est influencée par l'ancienne colère du Dragon : c'est pourquoi les Kamis sont sauvages, imprévisibles et dangereux. Ils sont obsédés par les ressources naturelles d'Atys, considérant qu'elles leur appartiennent, et n'hésitent pas à tuer les prospecteurs qui défient leurs interdictions.</ul><br><ul>Le chef des Kamis, un démon qui se fait appeler Ma-Duk, a convaincu certains homins qu'il était le dieu créateur d'Atys. à force de magie et de tromperie, il a créé autour de lui un véritable ordre religieux, une secte qui croit œuvrer pour le bien des homins et de la planète toute entière. S'ils réalisaient le but véritable de leur fausse divinité, ses adeptes hurleraient d'épouvante. En effet, le but de Ma-Duk est d'assimiler les homins pour les transformer à son image et les lier à Atys pour toujours, les condamnant à périr avec lui lors du réveil du Dragon.</ul><br><ul>Autre terrible vérité : Ma-Duk est menacé par la Goo qui le ronge. Pour prolonger sa force vitale, Ma-Duk dévore lentement les âmes et les corps des homins qui le suivent, tel un monstrueux parasite.</ul><br><ul>La Karavan espère sauver les homins trompés par les mensonges de Ma-Duk. Elle tente de leur faire comprendre leur erreur et veut les guider hors des ténèbres, afin qu'ils retrouvent la clarté de la lumière de Jena. Mais certains ne veulent pas être sauvés, et font tout pour entraîner d'autres homins dans leur chute. L'affrontement devient alors inévitable.</ul>";


$texte_stele_karavan_7 = "<ul>La Karavan est un guide spirituel : elle a délivré aux homins les messages de Jena, la Déesse qui les sauvera de l'anéantissement lorsque le Dragon s'éveillera. Elle ressuscite l'esprit des homins selon la volonté de la Déesse. Elle propose des pactes, permettant aux homins de se téléporter ou de dissiper l'ombre qui plane sur eux lorsqu'ils reviennent des portes de la mort.</ul><br><ul>La Karavan est un mentor généreux : elle a aidé les homins à développer leurs artisanats. Les secrets du magnétisme, de l'écriture, de la botanique, les fondements du système monétaire, la maîtrise du feu : tout cela a été révélé aux homins par la Karavan. Elle récompense ses fidèles les plus méritants en leur enseignant certaines techniques, en leur attribuant des titres prestigieux, en leur offrant des objets issus de sa puissante technologie.</ul><br><ul>La Karavan est un bâtisseur visionnaire : elle a participé à la construction des civilisations homins. Elle a aidé à rebâtir après le Grand Essaim, mettant en place des foreuses sur les avant-postes pour fournir une grande quantité des ressources.</ul><br><ul>La Karavan est un gardien indéfectible : elle a combattu les kitins lors du Grand Essaim, mettant fin à leur invasion. Elle lutte contre les Kamis qui veulent transformer les homins en démons, et contre élias Tryton qui veut utiliser les peuples d'Atys à ses propres fins obscures. Elle étudie la Goo afin de la comprendre et de la contrôler pour qu'elle ne soit plus une menace. Elle se bat contre la violence aveugle des primitifs. Elle tente de préserver les homins de l'influence néfaste du Dragon. La Karavan œuvre pour l'ordre contre l'anarchie, elle regarde vers le futur plutôt que vers le passé. Elle mènera les peuples homins à leur accomplissement, dans la gloire et dans la lumière de Jena.</ul>";


$texte_stele_karavan_8matis = "<ul>Dans les temps anciens, le peuple Matis a été le plus grand allié de la Karavan. Le premier homin à qui Jena choisit d'apparaître fut un Matis, Zachini, qui devint par la suite le monarque du royaume de Matia.</ul><br><ul>La cité sainte de Karavia fut édifiée sur le lieu de la divine apparition, où Zachini reçut les commandements de Jena des mains de la Karavan. La lumière du culte de la Déesse se répandit ensuite parmi les homins grâce à la piété du roi Zachini.</ul><br><ul>La Karavan a aidé les Matis à bâtir leur civilisation, et les a toujours poussés vers l'excellence. Elle leur a révélé les secrets de la matière vivante, afin qu'ils puissent laisser libre cours à leur créativité. Ainsi l'art de la manipulation de la flore et de la faune est-il devenu l'un des fondements de la culture matis.</ul><br><ul>Les Matis ont combattu farouchement les ennemis de Jena : ils ont mis fin à la menace des primitifs dans les anciennes forêts, et ils ont aidé la Karavan dans sa lutte contre les démons Kamis. La loyauté et la ténacité des guerriers matis a fait d'eux les plus nobles champions au service de la Déesse.</ul>";


$texte_stele_karavan_8tryker = "<ul>Depuis le début de leur Histoire, les Trykers ont surmonté des épreuves difficiles, mais ils sont toujours parvenus à relever la tête. Jena et les élus de la Karavan ont été présents à leurs côtés.</ul><br><ul>Lorsque le peuple Tryker fut réduit en esclavage à l'aube de son existence, Jena intervint pour le libérer. Lorsque les Kamis abandonnèrent les Trykers pour disparaître dans les jungles d'Atys, la Karavan s'avança pour guider le peuple des lacs sur la voie de la lumière.</ul><br><ul>La Karavan a apporté son aide dans le développement de la civilisation tryker. Elle a révélé au peuple lacustre les secrets de la puissance des vents. Elle a donné sa bénédiction à la création de la première monnaie, les dappers, encourageant de nouveaux échanges commerciaux plus équitables. Les artisans trykers, sous la bienveillance de la Karavan, ont pu expérimenter de nombreuses inventions qui ont amélioré la vie de tous.</ul><br><ul>Les Trykers sont enthousiastes et se sont battus farouchement pour défendre leur liberté. La Karavan a pu compter sur eux à de nombreuses reprises pour lutter contre les ténèbres qui menacent d'engloutir Atys.</ul>";


$texte_stele_karavan_8fyros = "<ul>Les Fyros sont un peuple fier et indépendant, et ses relations avec la Karavan ont souvent été teintées de méfiance. Pourtant, les Fyros sont comme tous les homins des enfants de Jena. De plus, ils sont particulièrement conscients de la présence du Dragon : ils veulent le détruire pour mettre un terme à la menace qu'il représente. En suivant le chemin tracé par la Karavan, le destin des Fyros est de devenir les gardiens d'Atys, sentinelles d'une vigilance sans égale.</ul><br><ul>Il y a fort longtemps, la Karavan a révélé un grand secret aux Fyros : le contrôle du feu. C'est grâce aux enseignements des élus de Jena que les Fyros sont devenus les maîtres incontestés du feu, l'utilisant dans leur artisanat, ou le domptant comme un animal sauvage pour en faire une arme contre leurs ennemis.</ul><br><ul>La Karavan a également aidé les Fyros à bâtir leur civilisation, par l'apprentissage de techniques de construction qui leur permirent d'ériger de grandes villes comme Fyr, la cité des flambeaux. Le peuple du désert s'est taillé une place l'épée à la main.</ul><br><ul>Guerriers intrépides à l'honneur sans faille, les Fyros sont sans pitié avec leurs ennemis. Le feu qui les anime est le feu du soleil. Leur place est aux côtés de Jena.</ul>";


$texte_stele_karavan_8zorai = "<ul>Aux yeux de nombreux homins, les Zoraïs sont un peuple mystérieux. Dans les temps anciens, ils ont vécu dans les profondeurs de la jungle, à l'abri des tumultes qui agitaient les autres homins.</ul><br><ul>Les Zoraïs recherchaient la sagesse, et l'amour de Jena les touchait au plus profond de leur âme. Malheureusement, les Kamis séduisirent nombre d'entre eux par de fausses promesses, et beaucoup de Zoraïs se détournèrent de leur Mère et de la Karavan.</ul><br><ul>Afin de ramener les Zoraïs sur la voie de la lumière, les élus de la Karavan leur enseignèrent les secrets du magnétisme. Ils leur apprirent à tracer des signes sur des papyrus, révélant les principes de l'écriture. Mais l'emprise des démons malfaisants était très forte, et les brumes de la magie obscurcissaient l'esprit des Zoraïs. Pourtant, jamais la Karavan ne perdit l'espoir de les dissiper.</ul><br><ul>Luttant courageusement contre le fléau de la Goo, les Zoraïs ont longtemps rêvé d'un monde d'harmonie. Ce monde existe, reposant dans le creux des mains de Jena. Un jour les masques des Zoraïs tomberont, et la lumière de la Déesse illuminera leur visage.</ul>";


$texte_stele_karavan_9 = "<ul>En ce lieu a été bâti un temple de Jena. Ce temple est l'une des maisons sacrées de l'église de la Lumière, où les homins karavaniers peuvent se recueillir. Ils trouveront ici ce qu'ils recherchent : le courage d'accomplir leur destin, l'amour de la Déesse, la paix de l'âme.</ul><br><ul>L'église de la Lumière, composée d'homins sous l'égide de la Karavan, a été constituée quelques années après la première apparition de Jena. Elle a été dispersée lors du Grand Essaim. La reconstruction des civilisations et l'établissement des homins sur les nouvelles terres ont demandé beaucoup de temps et de sacrifices. Après plusieurs décades, de nouveaux temples ont été érigés, pour honorer la Déesse avec la magnificence qui lui est due.</ul><br><ul>Homin, sois le bienvenu dans le temple de Jena ! La Déesse du soleil, Mère de toute vie, est aimante et accueillante. Sois baigné de Sa lumière, et prépare ton âme pour le Jour du Jugement, afin qu'elle puisse s'élever vers les étoiles.</ul>";


$texte_stele_karavan_10 = "<ul>Ici sont écrits les Dix Commandements de Jena, tels qu'ils furent révélés au roi Zachini par la Déesse, et tels qu'ils furent transmis par la sainte Karavan.</ul><br><ul>Premier Commandement : Moi, Jena je suis votre déesse, la mère créatrice, vous avez été faits à mon image. Aimez votre déesse comme vous vous aimez vous-même.</ul><ul>Deuxième Commandement : Vous n'adorerez point d'autres dieux.</ul><ul>Troisième Commandement : Enseignez à vos enfants mon amour comme je vous donne le mien.</ul><ul>Quatrième Commandement : Vous honorerez mes disciples, ils sont les hérauts de ma loi, et sont envoyés pour protéger votre bien-être.</ul><ul>Cinquième Commandement : Vous ne descendrez pas dans les entrailles d'Atys, de peur que la sainte Lumière quitte votre cœur et que les ténèbres du Dragon dévorent votre âme.</ul><ul>Sixième Commandement : Comme la feuille d'un arbre tombe sur le sol qui donne la force de vivre, votre âme sera rappelée à moi quand vous mourrez. Selon la force de votre foi vous renaîtrez avec ma bénédiction ou vous pourrirez dans d'atroces tourments.</ul><ul>Septième Commandement : Annoncez ma venue et mon amour grandira dans vos cœurs.</ul><ul>Huitième Commandement : Ne vous appropriez pas la loi, de peur de tomber dans le péché le jour du jugement.</ul><ul>Neuvième Commandement : Cherchez à rejoindre mon royaume et je vous attendrai à mi-chemin.</ul><ul>Dixième Commandement : Une fois que vous aurez prouvé la pureté de votre foi vous atteindrez la joie de l'élévation et ainsi deviendrez un disciple de confiance.</ul>";

?>