<?php

$titre = "Wissenskolonne -";

$TITLE_karavan = "JENAS TEMPEL";

$texteDefault = "Einen Text aus dem Menü auswählen";

$menu1 = "DIE NARCHRICHT DER KARAVAN";
$menu2 = "DIE GEBURT DER HOMINHEIT";
$menu3 = "DIE DRAKONISCHEN ASCHEN";
$menu4 = "DIE PROPHEZEIUNG";
$menu5 = "DIE FEINDE JENAS";
$menu6 = "DIE LÜGEN DES MA-DUK";
$menu7 = "DIE WOHLTATEN DER KARAVAN";
$menu8matis = "DIE KARAVAN UND DIE MATIS";
$menu8tryker = "DIE KARAVAN UND DIE TRYKER";
$menu8fyros = "DIE KARAVAN UND DIE FYROS";
$menu8zorai = "DIE KARAVAN UND DIE ZORAÏ";
$menu9 = "DIE KIRCHE DES LICHTS";
$menu10 = "DIE GEBOTE DER JENA";

$texte_stele_karavan_1 = " Wir sind die Jünger Jenas, Göttin von Atys und Mutter der Hominheit. Sie sandte uns, um ihre Kinder in unsere Obhut zu nehmen, ihnen aus Verirrungen den Weg zu weisen und sie auf die göttliche Rettung am Tage des Gerichts vorzubereiten. Es sei dir versichert, Homin, dieser Tag ist nahe!</ul><br><ul>Ehre Jena und sie wird dich durch die Pforten des Paradieses in eine Welt des Wohlstands führen, fern des Drachen und der Kitin, fern der bösartigen Kamis! Sei wachsam! Diese Kreaturen sorgen sich mehr um die infizierten Pflanzen als um das Leben der Homins. Wenn du sie gewähren lässt, nehmen sie Besitz von deiner Seele, um ihre selbstsüchtige Begierde der Selbsterhaltung zu stillen.</ul><br><ul>Vergiss nie: Wie wir wurdest auch du nach dem Abbild Jenas erschaffen. Dein Glaube soll dein Herz ausfüllen, wenn du die göttliche Gunst zu empfangen suchst, wenn Atys das hominische Leben nicht mehr ertragen kann. Zur Belohnung deiner Opfergaben hat sie uns mit der göttlichen Macht versehen, um deinen Geist wieder auferstehen zu lassen, dich in entfernte Welten zu senden und dir den Umgang mit unserer Technologie beizubringen.</ul><br><ul>Wenn du, wie wir, das Leben eines Homin als wichtiger erachtest als das einer einfachen Pflanze, dann öffne Jena dein Herz und Sie wird dich erretten!";


$texte_stele_karavan_2 = "Der Sage nach bewohnten die Ahnen der Homins in vergangenen Zeiten einen öden Planeten. Der große Drache, Prinz der Finsternis, verführte sie mit Trugbildern von reinem Wasser und fruchtbarer Erde. Er führte die Homins auf das versprochene Land von Atys, wo er die Sonne gefangen nahm. Der Planet fiel in Kälte und Dunkelheit. Statt eines wunderbaren Landes und der Freiheit lernten die vom Drachen betrogenen Völker Trostlosigkeit und Sklaverei kennen.</ul><br><ul>Jena, die Göttin der Sonne und Mutter allen Lebens, schenkte ihnen Erlösung. Die Schöpferin von Atys erhielt Nachricht von der Hinterhältigkeit des Drachen und flößte ihm ewiges Feuer ein. So konnte der Drache das kalte Klima nicht aufrecht erhalten und das Licht des Lebens nicht weiter verbergen. Die Göttin ließ anschließend das Licht wieder auferstehen. Die Zeit des Grünen Erwachens brach an und Atys verwandelte sich in einen üppigen grünen Planeten. Die versklavten Völker waren vom Drachen erlöst, der sich in das tiefste Innere des Planeten zurückzog. So erschuf Jena die Homins.</ul><br><ul>Jena richtete sich an ihre Jünger, die Auserwählten der Karavan, die zwischen den Sternen reisten und ihr im Kampf gegen den Drachen zur Seite standen. Die Göttin betraute sie mit der Aufgabe, die Homins zu führen, auf dass das Volk gedeihe, frei vom Einfluss des Drachens, der im Inneren von Atys schlummerte. Die Karavan half den Homins, sich an verschiedenen Orten auf dem Planeten anzusiedeln, damit jedes Volk auf seine Weise die Zukunft von Atys errichten konnte.";


$texte_stele_karavan_3 = "Der Drachen war besiegt, aber sein unheilvolles Erbe bedrohte Atys weiter. Als Jena den scheußlichen Drachen mit dem Feuer der Sonne erfüllt hatte, krümmte sich die Bestie vor Schmerzen und spie ihren flammenden Atem über den gesamten vereisten Planeten. Der feurige Atem ließ den Urschlamm von Atys wieder aufleben, der bis dahin unter den Eisschichten verborgen lag. Jena überflutete den Planeten mit ihrem Licht, und der fruchtbare Boden keimte wie ein Feuerwerk.</ul><br><ul>Während des Grünen Erwachens umschlangen die Urwurzeln von Atys den Drachen. Er versuchte sich zu befreien, indem er das Sonnenfeuer ausspie und den neu geborenen Wald zu Asche versengte, aber das Wunder des Lebens war stark, und das Feuer erlosch unter dem Gewicht des Blattwerks. Erschöpft floh der besiegte Drache in die Dunkelheit einer Pflanzenhöhle im tiefsten Inneren des Planeten und schlief ein. Die Asche, die vom Feuer des Drachen zurückblieb, verteilte sich auf ganz Atys. Sie vermischte sich mit den Sapflüssen, mit den Pollen der Riesenblumen, mit den Sporen der Pilze.</ul><br><ul>Sie setzte sich in den Spalten der Urrinde fest. Als das Grüne Erwachen vorbei war, befand sie sich überall. Sie enthielt die Reste der Wut des Drachen. Alle Wesen von Atys tragen die drakonische Asche in sich. Die Luft, die Pflanzen und der Regen sind von ihr durchdrungen. Sie ist unsichtbar, hat keinen Geruch oder Geschmack und findet sich als winzige Partikel im Atem aller Lebewesen wieder.</ul><br><ul>Die Auserwählten der Karavan, deren Reinheit nicht vom Drachen beschmutzt ist, werden durch heilige Rüstungen vor der Asche geschützt. Würden sie die drakonische Asche einatmen, dann wären sie dem Atem des Drachen schutzlos ausgeliefert.";


$texte_stele_karavan_4 = "Als Jena ihre Jünger mit dem Schutz der Homins beauftragte, wurde eine Prophezeiung verkündet. Eines Tages würde der große Drachen, der in den Tiefen von Atys schlief, wieder erwachen. Vom ewigen Feuer in seinem Inneren aufgezehrt würde er seinen Qualen und seiner Existenz ein Ende bereiten, indem er alles Feuer in seinem Körper ausspeien und Atys so vernichten würde. Am Tag des Gerichts werden Jena und ihre heiligen Propheten von jenseits der Sterne kommen. Sie werden die Homins erretten, die den Lehren der Göttin treu waren, und sie in den Himmel bringen, wo sie die Auserwählten der Karavan treffen.</ul><br><ul>Homins, die die Allgewalt Jenas nicht anerkennen, werden in den Flammen des Drachen umkommen und mit ihm untergehen. Den Geretteten wird eine neue Welt des Wohlstands eröffnet, wo sie auf ewig im Licht der Göttin leben.</ul><br><ul>Einzig Jena weiß, wann der Drache erwacht, um seinen letzten Atem der Zerstörung auszustoßen. Jeder Tag, der vergeht, bringt Atys seinem unabwendbaren Ende näher. Doch dieses Ende darf nicht unvorsichtig herbeigeführt werden.</ul><br><ul>Auch wacht die Karavan darüber, dass ihre Getreuen sich nicht in die tiefsten Schichten von Atys begeben. In die Tiefen des Planeten hinab zu steigen bedeutet, sich dem Drachen zu nähern, dessen unruhiger Schlaf von schrecklichen Träumen gestört wird. Diese Träume der Finsternis können das Licht der Jena aus den Herzen der Homins stehlen und ihre Seele verschlingen.Die Karavan erlaubt ihren Anhängern jedoch, in die oberen Schichten der Urwurzeln einzudringen, wenn es notwendig ist.";


$texte_stele_karavan_5 = "Dunkle Kräfte beherrschen das Universum, und Atys ist vor ihrem Einfluss nicht geschützt. Um ihre Kinder zu befreien, hat Jena ihre Schlacht gegen den Verderben bringenden Drachen geführt.</ul><br><ul>Andere Feinde lauern im Dunkeln, und die Getreuen der Göttin müssen vor ihnen gewarnt werden. Die Kamis und ihr Oberhaupt Ma-Duk sind die größte Bedrohung für die Zukunft der Hominheit. Diese Dämonen wollen sich der Homins bemächtigen, um sie zu versklaven und zu gefügigen Dienern zu machen, welche für das Überleben von Ma-Duk geopfert werden.</ul><br><ul>Elias Tryton, ein Prophet, der vom Drachen vergiftet wurde, ist wieder auf Atys erschienen und versucht, die Homins zu beeinflussen. Er ist für den Großen Schwarm verantwortlich: Er entfesselte die Wut der Kitins, um die Homin-Kulturen zu vernichten und öffnete die magischen Pforten, um die Überlebenden in die Finsternis der Urwurzeln zu schicken. Doch unterschätzte er die Macht der Karavan, die der Invasion ein Ende setzte, und das Licht der Jena in den Herzen der vertriebenen Homins erhielt.</ul><br><ul>Die Kitins stellen eine weitere Bedrohung für die Homins dar. Diese Monster, die die alten Kulturen beim Großen Schwarm vernichteten, wurden aus den Schuppen des Drachen geboren. Im Inneren von Atys gediehen sie und breiteten sich dann über die gesamte Rinde aus. Die Karavan überwacht jede Bewegung des Schwarms, bereit, bei einer massiven Invasion einzuschreiten.</ul><br><ul>Die Primitiven sind entartete Kreaturen, geboren aus den vom Drachen verdorbenen Homins. Sie sind überaus aggressiv und greifen alle Homins an, die ihren Weg kreuzen. Sie vermehren sich rasch, und es haben sich einige Klans von intelligenteren Primitiven gebildet. Die Karavan kann nicht erlauben, dass solche Kreaturen den Völkern schaden, für die sie verantwortlich ist.</ul><br><ul> Das Goo ist eine Bedrohung, die den Auserwählten Jenas nicht entgangen ist. Allmählich verschlingt sie den Planeten und vergiftet die Ressourcen von Atys. Auch die Karavan versucht, sich des Goos zu entledigen. Deshalb studiert sie es, um mehr über seine Schwächen zu erfahren. Und schließlich sind auch einige Homins ihresgleichen Feind. Die Karavan ist wohlwollend, aber sie toleriert nicht, dass ihre Getreuen Fanatikern zum Opfer fallen, die nicht zögern, sie zu töten und auszuplündern. Die Homins müssen sich mit Hilfe der Karavan unter dem Licht Jenas vereinigen, um gegen ihre Feinde zu kämpfen. So wird ihnen der Sieg sicher sein.";


$texte_stele_karavan_6 = "Die Kamis sind Dämonen, die aus der drakonischen Asche geboren wurden und sich überall auf Atys verbreitet haben. Ein Großteil dieser eigentümlichen Kreaturen ist von der alten Wut des Drachen erfüllt. Deshalb sind die Kamis wild, unberechenbar und gefährlich.Sie sind von den natürlichen Ressourcen von Atys besessen und der Überzeugung, sie würden ihnen gehören. Ohne Zögern töten sie jeden, der ihre Verbote missachtet.</ul><br><ul>Das Oberhaupt der Kamis, der Dämon Ma-Duk, konnte einige Homins davon überzeugen, er sei der göttliche Schöpfer von Atys. Mit der Kraft von Magie und Täuschung schuf er einen religiösen Orden, eine Sekte, die glaubt, für das Wohl der Homins und des gesamten Planeten zu wirken.Sie wären entsetzt, würden sie die wahren Absichten ihrer falschen Gottheit erfahren. Denn das Ziel von Ma-Duk ist, sich der Homins zu bemächtigen, um sie nach seinem Bild umzuformen und für immer an Atys zu binden, wo sie dazu verdammt wären beim Erwachen des Drachen mit ihm umzukommen.</ul><br><ul>Eine andere erschreckende Wahrheit: Ma-Duk wird vom Goo zerfressen. Um seine Lebenskraft zu verlängern, verschlingt er die Seelen und Köper der Homins, die ihm folgen, wie ein Monster.</ul><br><ul>Die Karavan hofft, die von den Lügen Ma-Duks getäuschten Homins zu retten. Sie versucht, ihnen ihren Irrtum vor Augen zu führen und sie aus der Finsternis zu leiten, damit sie das klare Licht der Jena wieder finden. Doch einige wollen nicht gerettet werden und tun alles, um bei ihrem Untergang andere Homins mit sich zu reißen. Die Konfrontation ist unvermeidbar.";


$texte_stele_karavan_7 = "Die Karavan ist eine spirituelle Führerin: Sie hat den Homins die Botschaften Jenas überbracht, der Göttin, die sie vor der Vernichtung durch den Drachen erretten wird. Sie erweckt den Geist der Homins nach dem Willen der Göttin. Sie schlägt Pakte vor, die den Homins erlauben, sich zu teleportieren und die Schatten zu vertreiben, die über ihnen schweben, wenn sie von den Pforten des Todes zurück kehren.</ul><br><ul>Die Karavan ist eine großzügige Lehrmeisterin: Sie half den Homins, ihre Künste zu entwickeln. Die Geheimnisse des Magnetismus, der Schrift, der Botanik, die Grundlagen des Geldsystems und die Beherrschung des Feuers sind Gaben, die die Karavan den Homins überbrachte. Sie belohnt ihre würdigsten Getreuen, indem sie ihnen Techniken beibringt, ihnen angesehene Titel verleiht und ihnen Gegenstände ihrer machtvollen Technologie schenkt.</ul><br><ul>Die Karavan ist eine visionäre Baumeisterin: Sie half den Homins beim Aufbau ihrer Kulturen. Sie unterstützte sie beim Wiederaufbau nach dem Großen Schwarm, indem sie Bohrmaschinen auf den Außenposten einrichtete, um eine ausreichende Versorgung mit Ressourcen sicherzustellen.</ul><br><ul>Die Karavan ist eine felsenfeste Wächterin: Sie bekämpfte die Kitins während des Großen Schwarms und setzte ihrer Invasion ein Ende. Sie kämpft gegen die Kamis, die die Homins in Dämonen verwandeln wollen, und gegen Elias Tryton, der die Völker von Atys für seine eigenen finsteren Zwecke benutzen will. Sie studiert das Goo, um es so kontrollieren zu können, dass es keine Bedrohung mehr darstellt. Sie schlägt sich gegen die blinde Gewalt der Primitiven. Sie versucht, die Homins vor dem unheilvollen Einfluss des Drachen zu schützen. Die Karavan strebt für Ordnung gegen die Anarchie, sie blickt in die Zukunft statt in die Vergangenheit. Sie wird die Homins zur Rettung führen, im Ruhm und Licht Jenas.";


$texte_stele_karavan_8matis = "In alten Zeiten waren die Matis die stärksten Alliierten der Karavan. Der erste Homin, dem Jena erschien, war der Matis Zachini, der später zum Monarchen des Königreichs Matia aufstieg.</ul><br><ul>Die heilige Stadt Karavia wurde an dem Ort der göttlichen Erscheinung errichtet, an dem Zachini die Gebote Jenas aus den Händen der Karavan entgegennahm. Das Licht der Göttin verbreitete sich daraufhin dank der Ehrfurcht des Königs Zachini unter den Homins.</ul><br><ul>Die Karavan half den Matis, ihre Kultur zu errichten und spornte sie immer zu Höchstleistungen an. Sie enthüllte ihnen die Geheimnisse der lebenden Materie, damit sie ihrer Kreativität freien Lauf lassen konnten. So wurde die Kunst, Flora und Fauna zu manipulieren, zu einer der Grundlagen der Matis-Kultur.</ul><br><ul>Die Matis kämpften entschlossen gegen Jenas Feinde: Sie setzten der Bedrohung durch die Primitiven in den alten Wäldern ein Ende und unterstützen die Karavan im Kampf gegen die Kami-Dämonen. Die Loyalität und Ausdauer der Matis-Krieger machte sie zu den nobelsten Meistern im Dienste der Göttin.";


$texte_stele_karavan_8tryker = "Seit Anbeginn ihrer Geschichte wurden die Tryker schweren Prüfungen unterzogen, die sie stets erhobenen Hauptes bestanden haben. Jena und die Auserwählten der Karavan waren an ihrer Seite.</ul><br><ul>Als das Volk der Tryker zu Beginn seiner Existenz versklavt wurde, schritt Jena ein, um sie zu befreien. Als die Kamis die Tryker im Stich ließen, um in den Urwäldern von Atys zu verschwinden, führte die Karavan das Volk von den Seen auf den Weg des Lichts.</ul><br><ul>Die Karavan unterstütze die Tryker in der Entwicklung ihrer Kultur. Sie enthüllte dem Seenvolk die Geheimnisse der Macht der Winde. Sie gab ihren Segen zur Einführung des ersten Geldes, der Dapper, und förderte den gerechten Handel. Die Kunsthandwerker der Tryker konnten unter dem Wohlwollen der Karavan mit zahlreichen Erfindungen experimentieren, die das Leben aller verbesserten.</ul><br><ul>Die Tryker sind ein eifriges Volk, das leidenschaftlich für die Verteidigung seiner Freiheit kämpfte. Die Karavan konnte immer auf sie zählen, um gegen die dunklen Mächte zu kämpfen, die Atys zu verschlingen drohen.";


$texte_stele_karavan_8fyros = "Die Fyros sind ein stolzes und unabhängiges Volk, und seine Beziehungen zur Karavan sind oft von Misstrauen überschattet. Dennoch sind die Fyros wie alle Homins Kinder Jenas. Sie sind sich der Gegenwart des Drachen besonders bewusst: Sie versuchen, ihn zu vernichten, um der Bedrohung unwiderruflich ein Ende zu setzen. Indem sie dem von der Karavan vorgezeichneten Weg folgen, sind die Fyros als Wächter und Beschützer von Atys auserkoren.</ul><br><ul>Vor sehr langer Zeit enthüllte die Karavan den Fyros ein großes Geheimnis: die Herrschaft über das Feuer. Dank der Unterweisungen der Auserwählten der Jena wurden die Fyros unbestrittene Meister des Feuers, setzten es für ihr Kunsthandwerk ein und bändigten es wie ein wildes Tier, um sich seiner gegen ihre Feinde zu bedienen.</ul><br><ul>Die Karavan half den Fyros auch bei der Errichtung ihrer Kultur, indem sie ihnen Bautechniken zeigte, mit deren Hilfe sie große Städte wie Fyr, die Stadt der Flammen, errichteten. Das Volk der Wüste erkämpfte sich seinen Platz, ein Schwert in der Hand.</ul><br><ul>Als standhafte Krieger haben die Fyros kein Mitleid mit ihren Feinden. Das Feuer, das sie belebt, ist das Feuer der Sonne. Ihr Platz ist an der Seite Jenas.";


$texte_stele_karavan_8zorai = "In den Augen zahlreicher Homins sind die Zoraï ein geheimnisvolles Volk. In alten Zeiten lebten sie tief im Dschungel, geschützt vor den Gefahren, von denen die anderen Homins heimgesucht wurden.</ul><br><ul>Die Zoraï suchten die Weisheit, und die Liebe Jenas berührte sie tief in ihrer Seele. Leider wurden viele von ihnen mit falschen Versprechungen von den Kamis in die Irre geführt und viele Zoraï wandten sich von ihrer Mutter und der Karavan ab.</ul><br><ul>Um die Zoraï wieder auf den Weg des Lichts zu führen, weihten die Auserwählten der Karavan sie in die Geheimnisse des Magnetismus ein. Sie lehrten sie die Grundzüge der Schreibkunst mit Zeichen auf Papyrus. Doch die Macht der verderblichen Dämonen war groß, und die Nebel der Magie verdunkelten den Geist der Zoraïs. Die Karavan verlor jedoch nie die Hoffnung, sie zu zerstreuen.</ul><br><ul>Im unerbittlichen Kampf gegen die Plage des Goo träumten die Zoraï lange von einer Welt der Harmonie. Diese Welt existiert. Sie ruht in den Händen Jenas. Eines Tages werden die Masken der Zoraï fallen und das Licht der Göttin wird ihr Angesicht erhellen.";



$texte_stele_karavan_9 = "An diesem Ort wurde ein Tempel Jenas errichtet. Dieser Tempel ist eines der heiligen Gebäude der Kirche des Lichts, wo die Homins im Dienste der Karavan sich versammeln. Hier finden sie, was sie suchen: den Mut, ihr Schicksal zu erfüllen, die Liebe der Göttin und Frieden für ihre Seelen.</ul><br><ul>Die Kirche des Lichts, die sich aus Homins unter der Führung der Karavan zusammensetzt, wurde einige Jahre nach der ersten Erscheinung Jenas gegründet. Beim Großen Schwarm wurde sie zerstört. Der Wiederaufbau der Kulturen und die Ansiedlung der Homins auf der neuen Erde erforderten viel Zeit und zahlreiche Opfer. Nach mehreren Jahrzehnten errichtete man neue Tempel, um die Göttin mit der Ihr gebührenden Pracht zu ehren.</ul><br><ul>Homin, sei willkommen in Jenas Tempel! Die Göttin der Sonne, Mutter allen Lebens, ist liebreich und gastfreundlich. Lass dich von ihrem Licht erfüllen und bereite deine Seele auf den Tag des Gerichts vor, damit sie zu den Sternen aufsteigen kann.";



$texte_stele_karavan_10 = "Hier sind die zehn Gebote der Jena niedergeschrieben, so wie sie dem König Zachini durch die Göttin dargebracht, und wie sie durch die heilige Karavan übermittelt wurden.</ul><br><ul>Erstes Gebot: Ich, Jena, bin eure Göttin, Schöpferin und Mutter. Ihr wurdet nach meinem Bild geschaffen. Liebt eure Göttin so wie ihr euch selbst liebt.</ul><ul>Zweites Gebot: Betet keine anderen Götter an.</ul><ul>Drittes Gebot: Lehrt eure Kinder meine Liebe, so wie ich euch meine gebe.</ul><ul>Viertes Gebot: Ehrt meine Jünger. Sie sind die Herolde meiner Gesetze, und sie wurden gesandt, um eurer Wohl zu schützen.</ul><ul>Fünftes Gebot: Steigt nicht in die Tiefen von Atys herab, wo das heilige Licht eure Herzen verlässt und die Finsternis des Drachen eure Seelen verschlingt.</ul><ul>Sechstes Gebot: So wie das Blatt eines Baumes auf den Boden fällt, der die Lebenskraft birgt, so wird eure Seele bei eurem Tode zu mir gebracht. In der Kraft eures Glaubens werdet ihr mit meinem Segen wieder geboren oder ihr verrottet in schrecklichen Qualen.</ul><ul>Siebtes Gebot: Verkündet meine Ankunft, und meine Liebe wird in euren Herzen wachsen.</ul><ul>Achtes Gebot: Bemächtigt euch nicht des Gesetzes, oder am Tag des Gerichts werdet ihr in Sünde fallen.</ul><ul>Neuntes Gebot: Strebt danach, in mein Königreich zu gelangen und ich werde euch entgegenkommen.</ul><ul>Zehntes Gebot: Wenn ihr die Reinheit eures Glaubens bewiesen habt, erwartet euch die Rettung und ihr werdet Jünger des Vertrauens.";


?>
