<?php

$titre = "Wissenswurzel -";

$TITLE_kami = "DER ALTAR DES MA-DUK";

$texteDefault = "Einen Text aus dem Menü auswählen";

$menu1 = "DIE NACHRICHT DER KAMIS";
$menu2 = "DIE ERSCHAFFUNG VON ATYS";
$menu3 = "DIE ERSCHAFFUNG DER HOMINS";
$menu4 = "DIE ERLEUCHTUNG ZUM KAMI-ZEITALTER";
$menu5 = "MA-DUKS FEINDE";
$menu6 = "DIE KARAVAN UND JENA";
$menu7 = "DIE GUTEN TATEN DER KAMIS";
$menu8matis = "DIE KAMIS UND DIE MATIS";
$menu8tryker = "DIE KAMIS UND DIE TRYKER";
$menu8fyros = "DIE KAMIS UND DIE FYROS";
$menu8zorai = "DIE KAMIS UND DIE ZORAI";
$menu9 = "DER GROßE ORDEN DES MA-DUK";
$menu10 = "DIE ENTHÜLLUNGEN DES MA-DUK";

$texte_stele_kami_1 = "Wir sind integraler Bestandteil der Schöpfung des Ma-Duk, Schöpfer von Atys. Wir beschützen die natürlichen Ressourcen, um das prekäre Gleichgewicht des Planeten zu bewahren, damit alle Homins eines Tages das Kami-Zeitalter erreichen können.</ul><br><ul>Homin, vergiss nicht dass dein Schicksal an jenes von Atys gebunden ist und nicht an die falsche Prophezeiung der Karavan. Das sind Fremde hier, Besatzer die von weit hergekommen sind, um uns unsere Ressourcen zu stehlen und sich nicht um das Wohl von Atys scheren.</ul><br><ul>Ich bin wie du auf Atys geboren und zusammen müssen wir den Planeten verehren und vor Gefahren schützen. Indem du das Goo bekämpfst wirst du den Weg der ewigen Glückseligkeit des Ma-Duk begehen. Um deine glorreichen Taten zu belohnen, werden wir Wiederauferstehungs- und Teleportationsspakte schließen und dir die Wege der Magie zeigen.</ul><br><ul>Für das Leben unseres Planeten und den Geiste deines Volkes, folge dem Weg des Schöpfers und wähle den Pfad der ewigen Glückseligkeit des Ma-Duk!";


$texte_stele_kami_2 = "Seit dem Beginn der Zeiten widersprechen sich zwei Gegensätze im Universum: das Nichts und die Erschaffende Energie, auch noch Großer Schöpfer genannt. Die Energie erschafft aus dem Nichts heraus und kann das Nichts nicht zerstören. Das Nichts ernährt sich von den Kreationen der Energie, kann aber die Energie selbst nicht zerstören.</ul><br><ul>Am Ende des Universums, inmitten des Nichts, erschuf der Große Schöpfer die Materie. Es entstand eine einzigartige Welt aus dieser fusionierenden Materie: Atys. Der Große Schöpfer verschmolz im jungen Planeten. Als die Gefahr des Nichts Atys zu fesseln drohte, säte der Schöpfer die ersten Samen des Lebens. Die Wurzeln eroberten den Himmel, die Vögel flogen davon und die Tiere gurrten im hysterischen Wunder des Lebens.</ul><br><ul>Aus dem Inneren des Grünen Planeten heraus schuf der Große Schöpfer die Kamis und versah sie mit einem Geist, einem Fragment seines eigenen Bewusstseins und schickte sie dann los, um seine Schöpfung zu überwachen. Die Kamis verfügten über große magische Kräfte und stiegen an die Oberfläche, um die Ländereien in ihrer Obhut zu erforschen. Inmitten der atysianischen Wunder entdeckten sie das Goo, das aus einer minimalen Parzelle des Nichts entstanden war, das sich mit dem Atem des Großen Schöpfers vermischt hatte. Das Goo fraß Atys langsam auf. Die Kamis konnten nichts dagegen tun, denn sie konnten das Nichts nicht zerstören. Das Schicksal schickte ihnen jedoch andere Wesen: die Homins.";


$texte_stele_kami_3 = "Während die Kamis die noch junge Rinde von Atys erforschten, entdeckten sie neue Wesen, die aus der Saat des Ma-Duk gediehen waren. Sie hießen Homins. Es waren Samen in die klaren Seen gefallen, aus denen die Tryker entstanden waren. Aus denen in der Wüste vergrabenen und von der Sonne erwärmten Samen waren die Fyros entstanden. Aus denen im Humus in den Wäldern steckenden Samen entstanden die Matis und aus denen ins Sap gefallenen Samenkerne die Zorai.</ul><br><ul>Die göttlichen Samenkerne hatten langsam gekeimt und spezielle Wesen hervorgebracht, denen ein unabhängiger Geist gegeben ward. Dank dieses Bewusstseins ihrer eigenen Existenz und derer von Atys und dem Nichts, hatten die Homins die Macht, die Welt zu verändern. Denn auch wenn sie durch das Nichts verwundbar sind, wie jede Schöpfung der Energie, verleihte ihr Bewusstsein dessen ihnen eine außergewöhnliche Resistenz gegen seinen Befall und, noch wichtiger, ermöglichte ihnen gegen das Goo vorzugehen. </ul><br><ul>Die Kamis lernten die Homins kennen und auferlegten ihnen eine Mission: die Epidemie bekämpfen. So wurde die Existenz des Großen Schöpfers Preis gegeben und die Homins konnten ihren Platz im Universum einnehmen.";


$texte_stele_kami_4 = "Als der Große Schwarm aus der Rinde brach, bekämpften die Kamis die Kitins, damit auf Atys wieder Frieden herrschte. Als die Kitins in das Innere des Planeten zurück gedrängt wurden erschien Ma-Duk, der Große Schöpfer, einem weisen Homin und zeigte ihm den Weg der Erleuchtung. Dieser Weg war der Weg zur absoluten Erleuchtung des Kami-Zeitalters, in dem die Homins mit Ma-Duk verschmelzen werden und das universelle Wissen erhalten.</ul><br><ul>Wenn sie den Pfaden der Erleuchtung folgen, durchqueren die Gläubigen verschiedene Etappen, die sie in andere Dimensionen führen. Der Homin, dem ausreichend Ehre zu Teil kommt, ersteht in einer anderen Welt als Kami auf, bis dass er in der Lage ist, die unendliche Glückseligkeit als Kami-Ko zu erreichen. Dann wird er für alle Ewigkeit im Kami-Zeitalter leben.</ul><br><ul>Um sich ehrwürdig zu erweisen, muss der Gläubige die Kreation des Ma-Duk beschützen, die Kamis verehren und das gute Wort verbreiten, damit die anderen Homins auch die Möglichkeit erhalten, die Erleuchtung zu erreichen. Deshalb versuchen die Weisen, die Hominheit von äußeren Einflüssen zu befreien, die sie nur in die Irre führen wollen.";


$texte_stele_kami_5 = "Das Nichts ist der Gegensatz zum Großen Schöpfer. Das Goo ist die wichtigste Lebensform des Nichts. Viele Feinde gefährden das Gleichgewicht von Atys und die Anhänger der Kamis müssen vorsichtig sein. Die Karavan und ihre falsche Göttin Jena stellen die größte Gefahr dar, denn sie bringen die Homins dazu, den Weg des Ma-Duk nicht einzuhalten und die Ressourcen von Atys auszubeuten. Es handelt sich um Fremde, die von jenseits der Sterne herkommen und den Kampf gegen das Goo zugunsten ihrer eigenen Interessen vernachlässigen.</ul><br><ul>Elias Tryton ist ebenfalls ein Fremder. Er erschien nur kurz auf Atys und scheint ein Feind der Karavan zu sein. Doch macht das ihn zu einem Alliierten der Kamis? Vorsicht ist geboten, denn es ist schwierig, seine Pläne voraus zu sehen.</ul><br><ul>Die Kitins sind Wesen, die am Leben auf Atys teilnehmen, doch wie wir beim Großen Schwarm feststellen konnten, können sie zu einer Bedrohung für die Homins werden. Die Kamis haben die Kitins schon in der Vergangenheit bekämpft und sie werden erneut eingreifen, um ihre Zerstörung in Grenzen zu halten.</ul><br><ul>Manche Homins werden als Feinde angesehen: Sie greifen ihresgleichen an, reißen Ressourcen an sich oder verbreiten im schlimmsten Falle die Epidemie des Goo. Die Rohstoffabbauer, die gierig nach Rohstoffen sind, setzen sich der Kamischen Wut aus. Die Anhänger des Goo gefährden den ganzen Planeten und die Kamis haben keine Nachsicht mehr für sie.</ul><br><ul>Das Goo, das Atys schon seit Jahrhunderten auffrisst, stellt die größte Bedrohung für Atys dar. Das Goo ist die Korruptheit des Nichts. Es steckt Pflanzen und Kreaturen an und verbreitet sich unermüdlich. Alle Homins müssen sich einen, um das Goo zu bekämpfen, sonst ist das Leben auf dem Planeten dem Untergang geweiht.";


$texte_stele_kami_6 = "Die Mitglieder der Karavan sind Wesen aus einer anderen Welt, jenseits der Sterne. Sie verhalten sich so als gehöre Atys ihnen: Sie beuten die Ressourcen aus und entziehen sie dem natürlichen Zyklus des Planeten. Sie setzen Maschinen ein, deren Energie die Flora stört. Sie scheren sich weder um das Gleichgewicht noch um die Harmonie, die für jegliches Leben notwendig sind.</ul><br><ul>In den frühen Zeiten von Atys schenkte Ma-Duk der Karavan keine Aufmerksamkeit und sah sie als kleineres Übel an. Doch die Fremden fingen an, die Kamis als dämonische Kreaturen anzusehen und trieben die Homins dazu, sie zu verfolgen. Sie haben zahlreiche Homins für ihre Verehrung Jenas gewonnen und sie von ihrer heiligen Mission gegen das Goo abgebracht. So konnte die Epidemie sich frei verbreiten. </ul><br><ul>Jena, die falsche Göttin der Karavan, ist überhaupt nicht die schöpferische Göttin von Atys. Sie ist in diese Rolle geschlüpft, um die Homins besser unterwerfen zu können. Ma-Duk spürt, dass Jena keine Göttin ist, sondern eine Erscheinung des Nichts, dessen Ziel es ist, die Homins zu versklaven, um ganz Atys zu beherrschen und sie ihrer Essenz zu berauben. Die Kamisten-Homins nennen Jena Herrscherin der Nacht, denn sie sind überzeugt, ihre Legionen würden nur Dunkelheit und Tod mit sich bringen.</ul><br><ul>Die Karavanhomins sind ein Problem für die Kamis. Die Anhänger Ma-Duks wollen die Homins lieber bekehren als sie zu bestrafen, können sie aber nicht dazu zwingen. Diejenigen, die den dunklen Weg der Jena gewählt haben, wollen andere Homins mit in die dunkele Welt ziehen und die Kamis werden das nicht zulassen.";


$texte_stele_kami_7 = "Die Kamis führen die Homins: Sie haben ihnen ihr Schicksal und ihren Platz im Universum offenbart. Sie führen sie auf die Wege der Erleuchtung, damit sie das Kami-Zeitalter erreichen. Sie haben die religiösen Kamisten-Orden beschützt, damit die Kamis ihre Brüder auch zum oberen Wissen leiten können.</ul><br><ul>Die Kamis helfen den Homins: Sie lassen ihren Geist wieder auferstehen nach dem Willen Ma-Duks. Sie schlagen ihnen Pakte vor, mit denen sie sich teleportieren oder ihre Schwächen verschwinden lassen können, wenn sie wieder auferstehen. Sie stehen ihnen in ihrem Kampf gegen das Goo bei, der Korruptheit des Nichts, die droht ganz Atys aufzufressen. In der Vergangenheit bekämpften die Kamis die Kitins während des Großen Schwarms und bereiteten der Invasion ein Ende. Sie haben den Homins auch dabei geholfen, ihre Zivilisationen wieder aufzubauen, indem sie ihnen ermöglichten, große Mengen an Ressourcen abzubauen.</ul><br><ul>Die Kamis bilden die Homins aus und haben ihnen die Geheimnisse der Magie beigebracht, wodurch sie ihre Macht und ihr Wissen über die Welt vergrößern konnten. Sie lehren sie, die Ressourcen von Atys zu respektieren, damit das Gleichgewicht bewahrt wird und die Homins immer etwas zum Überleben haben.</ul><br><ul>Die Kamis wachen über die Homins: Sie bekämpfen die Karavan, die Atys zu persönlichen  Zwecken ausbeutet und die Homins versklaven will. Sie behalten ebenfalls die Kitins im Auge, damit die Homins nicht mehr bedroht sind.</ul><br><ul>Die Kamis arbeiten für die Harmonie und Kommunion zwischen den Homins und Atys. Sie wollen das Jetzt und das prekäre Gleichgewicht vor verheerenden Einflüssen bewahren, die nur zu Zerstörung und Verfall aller Dinge führen würden.";


$texte_stele_kami_8matis = "Die Matis sind seit jeher fasziniert von den Kräften der Natur. Doch ihr Wille zu dominieren, hat einen Keil zwischen die Kamis und die Matis getrieben. Die Anhänger Ma-Duks haben in der Vergangenheit mehrmals versucht, dies zu ändern, allerdings ohne Erfolg. Die Allgegenwärtigkeit der Karavan bei den Matis hat die Annäherungsversuche zusätzlich erschwert.</ul><br><ul>Die beste Gelegenheit bot sich, als die Kamis die Matis trafen, um ihnen ihre Magie beizubringen. Trotz der Ablehnung der Karavan stellten die Matis sich als fleißige und ehrgeizige Schüler heraus. Doch sie versuchten sehr schnell die Magie einzusetzen, um die Pflanzen nach ihrem Willen zu unterwerfen und neue Arten zu erschaffen. Die Kamis waren nicht damit einverstanden und wandten sich von den zu ehrgeizigen Lehrlingen ab.</ul><br><ul>Die von der Karavan manipulierten Matis haben die Kamis sogar verfolgt, um sie den Auserwählten Jena zu übergeben. Die Kamis haben sich diskret verhalten und wollten die Matis nicht zu hart für ihr Unwissen bestrafen. Denn die Anhänger des Ma-Duk haben die Hoffnung nie verloren, die Matis auf den Weg der Erleuchtung zu führen.</ul><br><ul>Mit ihrem Wissen und ihrer Herrschaft über die Natur können die Matis wertvolle Wächter von Atys werden.";


$texte_stele_kami_8tryker = "Die Tryker waren die ersten Homins, die mit den Kamis in Kontakt traten. Die friedliche und unbesorgte Art des Seenvolkes und ihre ökologischen Beschäftigungen bezüglich der Umwelt gefielen den Kamis. Doch nach einer Feuersbrunst in den alten Wüstenländern suchten die Kamis Schutz in den sicheren Dschungeln von Atys und genossen die Ruhe der Zorais.</ul><br><ul>Die Tryker waren durch die Abwesenheit der Kamis verstört und verloren sich in den Wegen der Karavan. Die Kamis haben versucht, die Tryker zurück auf die Wege des Ma-Duk zu leiten, indem sie ihnen Magie beibrachten. Am Anfang sahen die Tryker das eher wie ein Spiel an und waren unfleißige Schüler. Doch unter dem Einfluss der Zorai-Meister, die die Kamis begleiteten, haben sie sich an die Arbeit gemacht und Fortschritte in verschiedenen Gebieten der Mystik gemacht.</ul><br><ul>Im Herzen sind sie Erfinder und haben ihre eigene Magie erfunden, die auf den Kräften des Windes und Schockwellen beruht. Die Tryker haben viel durchgemacht und sich als entschiedene Kämpfer entpuppt, die bereit sind, sich für ihre Freiheit zu opfern. Die Kamis wollten sie immer für sich gewinnen, denn wie sie hängen auch die Tryker sehr an der Schönheit der großen Seen von Atys.";

$texte_stele_kami_8fyros = "Die Kamis stellten schon sehr früh eine besondere Begabung bei den Fyros fest. Das Wüstenvolk hatte vor einer großen atysianischen Gefahr keine Angst: dem Feuer. Die Kamis haben versucht, ihr Herz zu erobern und sie für ihre Sache zu gewinnen. Die Fyros nahmen sich zuerst in Acht vor diesen eigenartigen Kreaturen. Doch die Rettung des Imperators Arispotle durch einen Kami ließ eine neue Freundschaft entstehen und war der Beginn eines tiefen Respekts im Herzen der Fyros.</ul><br><ul>Die Fyros näherten sich den Kamis mehr und mehr an, um von ihnen die Geheimnisse der Magie zu lernen. Der Imperator war der erste Homin, der die kamische Teleportation benutzte. Die Fyros experimentierten mit einer Magie, die Feuer einsetzt und manipulierten die Hauptenergie der Wüste. Als Dank für ihre Dienste versprachen die Fyros den Kamis, sie gegen das Feuer des Drachens zu schützen und erklärten sich einverstanden, im Falle eines Feuers gegen ihn zu kämpfen. Die Fyros sind ausgezeichnete Krieger und allzeit bereit, sich für eine gerechte Sache einzusetzen.</ul><br><ul>Auch wenn sie dem Großen Orden des Ma-Duks ihre eigenen kamistischen Kulte bevorzugten, sind viele dem Aufruf der Kami-Anhänger gefolgt, egal von wo sie herkommen.";


$texte_stele_kami_8zorai = "Die Kamis, die sich während der alten Zeiten nach dem großen Inferno in den Dschungel verschanzt hatten, lernten die Zorai kennen und betrauten sie mit der heiligen Mission gegen das Goo. Es entstand eine starke Bindung zwischen den Geistern der Natur und den Zorais, was zur Gründung des ersten Kamikultes führte – der Verkörperung der puren Energie, aus der Atys entstand. Die Kamis schufen Verwandschaftsmasken für die Zorai, um diese Verbindung zu symbolisieren. Die Kamis weihten die Zorai in die Geheimnisse der Magie ein. So kamen die ersten Magier auf Atys, die Wunder vollbrachten.</ul><br><ul>Danach haben Zorai-Übermagier die mystischen Geheimnisse studiert und eine heilige Schrift benutzt, um ihr Wissen weiter zu geben. Sie haben die Macht des Blitzes entdeckt und die erste Volksmagie erschaffen: die Magie der Elektrizität.</ul><br><ul> Mit ihrer Magie und ihrem Wissen über den Magnetismus bekämpften die Zorais das Goo, das die Dschungel von Atys befiel. Im Namen der Kamis haben sie die Epidemie mutig bekämpft. Sie nahmen sich vor der Karavan in Acht, die die Homins vom Weg der Erleuchtung abbrachte.</ul><br><ul>Ihr fester Glaube hat die Zorais zu heiligen Kriegern des Ma-Duk gemacht.";


$texte_stele_kami_9 = "An diesem Ort wurde eine Kultstätte des Großen Ordens des Ma-Duk errichtet. Hier können die Kamisten-Homins meditieren und das Herz von Atys schlagen hören. Sie können mit dem großen Schöpfer kommunizieren, um die Antworten zu finden, die sie auf dem Weg zur Erleuchtung leiten werden. </ul><br><ul>In den alten Zeiten haben die Zorais die ersten Kamikulte gegründet. Diese Kulte errichteten Tempel zu Ehren der Kamis und des Obersten Kami. Doch der Große Schwarm hat alle religiösen Organisationen der Vergangenheit zerstört. Die Kulte selbst haben überlebt, nicht aber ihre Kirchen.</ul><br><ul>Da Ma-Duk wieder mit all seinen Gläubigen kommunizieren wollte, ist er dem Großen Weisen Hoi-Cho erschienen, um einen neuen Kami-Kult ins Leben zu rufen, den Großen Orden des Ma-Duk. Homin, sei willkommen in der Kultstätte des Ma-Duk! Der Große Schöpfer, der Oberste Kami, empfängt dich dort so wie er dich in seiner Mitte empfangen wird, wenn du das Kami-Zeitalter und das universelle Wissen erreicht hast.";


$texte_stele_kami_10 = "Hier sind die acht Enthüllungen des Ma-Duk niedergeschrieben, in heilige Schrift übersetzt, und so überliefert wie Ma-Duk selbst sie dem Großen Weisen Hoi-Cho vorgetragen hat, ehe sie am Anfang des Buchs der Enthüllungen niedergeschrieben wurden.</ul><br><ul></ul><ul>Erste Aussage: Ich bin Ma-Duk, der Schöpfer von Atys. Ich bin eins mit den Kamis, die ein Teil von mir sind. Ihr müsst sie so verehren wie den Schöpfer selbst.</ul><ul>Zweite Aussage: Ihr werdet dem Weg der Erleuchtung der Kamis folgen. Er wird euch ins Kami-Zeitalter geleiten.</ul><ul>Dritte Aussage: Um das Kami-Zeitalter zu erreichen und eins mit dem Schöpfer zu sein, müsst ihr dem Weg der Erleuchtung folgen, um ehrbürtig zu sein.</ul><ul>Vierte Aussage: Werdet durch eure Loyalität und eure Pflege von Ays ehrwürdig, der Planet entspringt meinem Leib.</ul><ul>Fünfte Aussage: Wenn ihr dem Weg der Erleuchtung der Kamis folgt, werde ich euren Geist wieder auferstehen lassen, wenn ihr sterbt, ehe ihr die absolute Ehre erreicht habt.</ul><ul>Sechste Aussage: Lasst euch nicht von falschen Göttern verführen, sie können nicht aus einer atysianischen Materie zusammengesetzt sein. Sie haben keinen Platz in meiner Schöpfung und sind der Ursprung von Unausgeglichenheiten.</ul><ul>Siebte Aussage: Seid der Feind des Exzesses und eure Reise auf dem Weg zur Erleuchtung der Kamis wird euch erfüllen.</ul><ul>Achte Aussage: Sowie ich die Samen der Existenz in den Wind gesät habe, um euer Leben auf Atys vorzubereiten, so müsst ihr die Erleuchtung der Kamis auf der ganzen Welt verbreiten.";
?>