<?php

$titre = "Knowledge Column -";

$TITLE_karavan = "THE TEMPLE OF JENA";

$texteDefault = "choose a text in the menu";

$menu1 = "THE MESSAGE OF THE KARAVAN";
$menu2 = "THE BIRTH OF HOMINITY";
$menu3 = "THE DRACONIC ASHES";
$menu4 = "THE PROPHECY";
$menu5 = "THE ENEMIES OF JENA";
$menu6 = "MA-DUK THE IMPOSTER";
$menu7 = "THE GOOD WORKS OF THE KARAVAN";
$menu8matis = "THE KARAVAN AND THE MATIS";
$menu8tryker = "THE KARAVAN AND THE TRYKER";
$menu8fyros = "THE KARAVAN AND THE FYROS";
$menu8zorai = "THE KARAVAN AND THE ZORAI";
$menu9 = "THE CHURCH OF LIGHT";
$menu10 = "THE COMMANDMENTS OF JENA";

$texte_stele_karavan_1 = "We are the disciples of Jena, the Goddess of Atys and Mother of Hominity. We have been sent to watch over Her children to give them guidance should they lose their way, and to prepare them for divine elevation on the judgment day. Be sure, that day is near, homin!</ul><br><ul> Adore Jena and She will lead you through the pearly gates to a world of plenty, away from the dragon and the kitins, away from the evil Kamis! Beware, these creatures are more concerned with festering plants than with homin life.  They will possess your soul just to nourish their selfish desire of self-preservation if you let them!</ul><br><ul>Never forget, like me, you were made in Jena's image, and faith in Her must prevail in your heart for you to receive divine grace when Atys can no longer support homin life.  In return for your devout offerings, She has invested us with divine authority to resurrect your spirit, to teleport you to distant lands, and to teach you how to wield our technology. </ul><br><ul>If, like us, you consider that a homin life is worth more than a simple plant, open your hearts to Jena, and She will be your Savior!";


$texte_stele_karavan_2 = "It is said that long ago, the ancestors of the homins inhabited an impoverished planet. The Great Dragon, the prince of shadows, came to entice them with visions of pure water and fertile lands. He led them to the promised land of Atys, where he hid the sun, plunging the planet into cold and darkness. Indeed, instead of a land of wonders and of freedom, the people tricked by the Dragon experienced desolation and slavery.</ul><br><ul>Jena, the sun goddess and Mother of all life, granted them deliverance. The creator of Atys heard of the perfidy of the Dragon and filled him with an eternal fire. That way, the dragon could no longer maintain a cold climate and extinguish the light of life. The Goddess then caused the light to be reborn, causing the green to grow and transforming Atys into an amazing planet of plants. The enslaved people were purified and set free from the Dragon, who withdrew into the depths: and this is how Jena gave birth to hominity.</ul><br><ul>Jena then turned to her disciples, the Elect of the Karavan, who were traveling among the stars and had witnessed the combat with the Dragon. The Goddess gave them the task of guiding the homins so that they would prosper, protected from the influence of the Dragon, who slept in the bowels of Atys. The Karavan helped the homins settle at various locations around the planet, so that each could build the future of Atys in their own way.";


$texte_stele_karavan_3 = "The Dragon was defeated, but he left his mark on Atys. When Jena filled the shadowy Dragon with the fire of the sun, the Beast twisted in pain and spit his flaming breath all across the frozen planet. Under the heat of his fiery breath, the primal ooze of Atys, which the Dragon had buried under a wasteland of ice, emerged once again. Then Jena flooded the planet with her Light, and the fertile soil sprouted with a miraculous frenzy of life.</ul><br><ul>The Dragon was caught in the roots of Atys during the Green Rising. He attempted to escape by spitting the sun fire, and reducing the new wood to ash, but the miracle of life was far too strong, and the fire was smothered under the weight of many unfolding leaves. Exhausted and defeated, the Dragon took refuge in the darkness of a plant cavern, in the depths of the planet, and finally went to sleep. The ashes that came from the Dragon's fire were scattered all over the surface of Atys. They blended with the rivers of sap, the pollen from the giant flowers, and the spores of the ancestral mushrooms.</ul><br><ul>They stuck to the lines of primeval bark. When the Green Rising came to a stop, they were everywhere. And they contained the remains of the Dragon's wrath. All beings on Atys carry traces of the draconic ashes. They are in the air, in the plants and in the rain. They are invisible, odorless and tasteless, infinitely tiny particles of dust breathed in by all living creatures.</ul><br><ul>The Elect of the Karavan, who are above any stains of impurity from the Dragon, protect themselves from the ashes by wearing sacred armor. For them, to breathe the draconic ashes would be tantamount to opening up to the breath of the Dragon.";


$texte_stele_karavan_4 = "When Jena gave her disciples the mission of guiding the homins, a prophecy was pronounced. One day, the Great Dragon sleeping in the depths of Atys would awaken. Consumed by an eternal inner flame, he will put an end to his torment and his very existence by spitting out all of the fire in his body, which will destroy Atys. On the day of judgment, Jena and her sacred prophets who came from beyond the stars will be there. They will save the homins who have been loyal to the teachings of the Goddess and carry them off into the sky to join the Elect of the Karavan.</ul><br><ul>The homins who continue to deny that Jena is the all-powerful Goddess will perish in the flames of the Dragon and disappear along with him. And those who have been saved will be transported to a new world of abundance, where they will live in the Light of the Goddess for all of eternity.</ul><br><ul>Only Jena knows when the Dragon will wake up to breathe out his ultimate destructive breath. Every passing day brings Atys closer to the inevitable end. But this end must not be hastened by imprudence.</ul><br><ul>So the Karavan are watching out to make sure that the faithful do not venture into the deeper layers of Atys. To descend into the bowels of the planet is to approach the Dragon, whose sleep is tormented by terrifying dreams. These shadowy dreams can push the light of Jena away from the hearts of homins, and devour their souls. Nevertheless, the Karavan still permit their followers to go down into the upper levels of the Prime Roots if there is a valid reason for going there.";


$texte_stele_karavan_5 = "There are dark forces in the universe, and Atys is not beyond their reach. Jena has already done battle against the evil Dragon in order to liberate her children.</ul><br><ul>There are other enemies lurking in the shadows, and the followers of the Goddess must beware. The Kamis and their leader Ma-Duk are the greatest threat to the future of hominity. These demons seek to possess the homins in order to subjugate them and turn them into docile servants who will be sacrificed for the survival of Ma-Duk.</ul><br><ul>Elias Tryton, a fallen prophet who was corrupted by the Dragon, has reappeared on Atys and tries to influence the homins. He is the one behind the Great Swarming, unleashing the anger of the Kitins to demolish homin civilizations, he opened magic portals to send the survivors into the shadows of the Prime Roots. He underestimated the strength of the Karavan, who ended the invasion and protected the light of Jena in the hearts of the exiled homins.</ul><br><ul>The Kitins are another threat to hominity. These monsters that swept away the ancient civilizations during the Great Swarming were born of the scales of the Dragon. They prospered in the depths of Atys before spreading out over the Bark. The Karavan keep an eye on the swarm and stand ready to intervene if there are any massive invasions.</ul><br><ul>The primitives are degenerate creatures, born of homins that have been corrupted by the Dragon. They are highly aggressive and attack any homins that cross their path. Their numbers are growing, and there are reports of some clans of primitives with higher intelligence. The Karavan cannot allow such people to harm those in their charge.</ul><br><ul> And the Goo is a threat that cannot escape the Elect of Jena either. It is slowly devouring the planet and polluting her resources. So the Karavan wish to get rid of it. In order to do so, they are studying it so they can find its weak points. And finally, there are also homins who turn out to be enemies to their own kind.</ul><br><ul>The Karavan are generally benevolent, but they cannot allow their followers to fall prey to fanatics who are ready to kill and pillage. Karavan homins must unite in the light of Jena to fight their enemies – this is how they will achieve victory.";


$texte_stele_karavan_6 = "The Kamis are demons born of the draconic ashes that are omnipresent on Atys. A large portion of the essence of these strange creatures is influenced by the ancient wrath of the Dragon: this is why the Kamis are savage, unpredictable and dangerous. They are obsessed with the natural resources of Atys, which they consider to be their own property, and they don't hesitate to kill any prospectors who defy their restrictions.</ul><br><ul>The head of the Kamis is a demon named Ma-Duk and he has convinced some of the homins that he is the creator of Atys. With magic and trickery, he has created a veritable religious order around himself. This is a sect that believes it works for the good of homins and the entire planet. If they realized the true purpose of their false divinity, the followers would scream in horror. Indeed, the goal of Ma-Duk is to assimilate homins to transform them into his own likeness and bind them to Atys forever, condemning them to perish along with him when the Dragon awakens.</ul><br><ul>Another terrible truth is that Ma-Duk is threatened by the terrible Goo that eats away at him. In order to prolong his own life force, Ma-Duk gradually devours the bodies and souls of the homins that follow him, like a monstrous parasite.</ul><br><ul>The Karavan hope to save the homins who have been fooled by the lies of Ma-Duk. They try to make them see the error of their ways and lead them out of the shadows, so they may return to the light of Jena. But there are some who do not want to be saved, and who do everything they can to drag other homins to their downfall. In such cases, a confrontation is inevitable.";


$texte_stele_karavan_7 = "The Karavan provide spiritual guidance: they have given the homins the messages of Jena, the Goddess who will save them from destruction when the Dragon awakens. They resurrect the spirits of homins in accordance with the will of the Goddess. They offer pacts that enable homins to teleport or to dissipate the shadow that floats over them when they return from the gates of death.</ul><br><ul>The Karavan are generous mentors: they have helped homins develop their crafts. The Karavan have revealed to them all the secrets of magnetism, writing, botany, the foundations of a monetary system, the mastery of fire. They reward their most meritorious followers by teaching them certain techniques, granting them prestigious titles and giving them object produced by their powerful technology.</ul><br><ul>The Karavan are visionary builders: they have participated in the construction of homin civilizations. They helped to rebuild after the Great Swarming, setting up mining machinery at the furthest outposts to provide plentiful resources.</ul><br><ul>The Karavan are loyal guardians: they fought the Kitins during the Great Swarming, putting an end to their invasion. They fight against the Kamis, who want to transform homins into demons, and against Elias Tryton, who wants to use the people of Atys for his own obscure purposes. They study the Goo in order to understand it and control it, so it will no longer be a threat. And they fight against the blind violence of the primitives. They try to protect homins from the harmful effects of the Dragon. The Karavan work to maintain order above anarchy, and they look towards the future rather than the past. They will lead the homin people to fulfillment, in the glory and light of Jena.";


$texte_stele_karavan_8matis = "In ancient times, the Matis people were the greatest allies of the Karavan. The first homin that Jena caused to appear was a Matis, Zachini, who then became the monarch of the Matia kingdom.</ul><br><ul>The holy city of Karavia was built at the site of the divine apparition, where Zachini received the commandments of Jena from the hands of the Karavan. The light of Goddess worship spread among the homins thanks to the piety of King Zachini.</ul><br><ul>The Karavan helped the Matis build their civilization, always urging them towards excellence. They then revealed the secrets of living matter, so that they could let their creativity flourish. Thus was born the art of manipulation of the flora and fauna, one of the foundations of Matis culture.</ul><br><ul>The Matis have fought fiercely against the enemies of Jena: they have ended the threat of the primitives in the ancient forests, and they have helped the Karavan in their fight against the Kamis demons. The loyalty and perseverance of the Matis warriors makes them the most noble champions of the Goddess.";


$texte_stele_karavan_8tryker = "Since the beginning of their history, the Trykers have overcome difficult trials, but they have always managed to keep their dignity. Jena and the Karavan Elect have always been at their sides.</ul><br><ul>When the Tryker people were reduced to slavery during the dawn of their existence, Jena intervened to liberate them. When the Kamis abandoned the Trykers and disappeared into the jungles of Atys, the Karavan stepped in to guide the lake people onto the path of light.</ul><br><ul>The Karavan provided help with the development of Tryker civilization. They revealed the secrets of wind power to these people of the lakes. They gave their blessings to the creation of the first currency, dappers, encouraging new, more equitable, commercial exchange. Under the benevolent guidance of the Karavan, the Tryker crafters were able to try out many new inventions that have improved life for all.</ul><br><ul>The Trykers are enthusiastic people who have fought bravely to defend their freedom. The Karavan have always been able to count on them on many occasions to fight against the shadows that threaten to swallow Atys.";

$texte_stele_karavan_8fyros = "The Fyros are proud, independent people, and their relations with the Karavan have often been marked by wariness. However, the Fyros, like all homins, are the children of Jena. They are also keenly aware of the presence of the Dragon: they wish to destroy it in order to end the threat that it poses to their existence. By following the path shown by the Karavan, the destiny of the Fyros is to become the guardians of Atys – sentinels whose vigilance is unmatched.</ul><br><ul>Long, long ago, the Karavan revealed a great secret to the Fyros: how to control fire. Thanks to the teachings of the Jena Chosen Ones, the Fyros became unrivaled masters of fire, using it in their crafts, or taming it like a wild animal in order to use it as a weapon against their enemies.</ul><br><ul>The Karavan also helped them build their civilization, by teaching them construction techniques that enabled them to build large cities like Fyr, the city of a torches. The desert people have carved out a place for themselves, sword in hand.</ul><br><ul>As intrepid warriors with unfailing honor, the Fyros are merciless with their enemies. They are fueled by the fire of the sun, and their place is alongside Jena.";

$texte_stele_karavan_8zorai = "In the eyes of many homins, the Zoraïs are a mysterious people. In ancient times, they lived deep in the jungle, far from the turbulence that drove other homins.</ul><br><ul>The Zoraïs were seeking wisdom, and the love of Jena touched the very depths of their souls. Unfortunately, the Kamis enticed many of them with false promises, and many Zoraïs turned away from their Mother and from the Karavan.</ul><br><ul>In order to bring the Zoraïs back to the pathways of light, the Karavan Chosen Ones taught them the secrets of magnetism. Thy taught them to draw signs on papyrus, revealing the principles of writing. But the grip of the evil demons was strong, and the mists of magic darkened the spirits of the Zoraïs. Still, the Karavan have never abandoned hope of dissipating this darkness.</ul><br><ul>Fighting courageously against the plague of Goo, the Zoraïs have long dreamed of a world of harmony. This world exists, in the hands of Jena. Someday, the Zoraïs' masks will fall, and the light of the Goddess will shine on their faces.";


$texte_stele_karavan_9 = "In this place was built a temple to Jena. This temple is one of the sacred houses of the Church of Light, where the Karavan homin can gather. Here, they will find what they need: the courage to fulfill their destiny, the love of the Goddess, and peace in their souls.</ul><br><ul>The Church of Light, made up of homins under the guidance of the Karavan, was built a few years after the appearance of Jena. It was dispersed during the Great Swarming. The reconstruction of civilizations and relocation of homins in new lands took a long time and many sacrifices. After several decades, new temples were built, to honor the Goddess with due magnificence.</ul><br><ul>Homin, welcome to the temple of Jena! The Sun Goddess, Mother of all life, is loving and welcoming. Be bathed in her light, and prepare your soul for the day of judgment, so that she may lift you up to the stars.";


$texte_stele_karavan_10 = "Here are written the ten commandments of Jena, as they were revealed to King Zachini by the Goddess, and transmitted by the holy Karavan.</ul><br><ul>First Commandment: I, Jena, am your Goddess, the Mother Creator, and you were created in my image. Love your Goddess as you love yourselves.</ul><ul>Second Commandment: You shall worship no other gods.</ul><ul>Third Commandment: Teach your children of my love, as I teach you.</ul><ul>Fourth Commandment: Honor my disciples, they are the heralds of my laws and have been sent to protect your well-being.</ul><ul>Fifth Commandment: You shall not descend into the bowels of Atys, for fear that the Light may leave your heart and the shadows of the Dragon may devour your soul.</ul><ul>Sixth Commandment: Like the leaf of a tree that falls to the ground which gives the power of life, your soul will be called back to me when you die. Depending on the strength of your faith, you will either be reborn with my blessings or you will rot in atrocious torment.</ul><ul>Seventh Commandment: Announce my coming and my love will grow in your hearts.</ul><ul>Eight Commandment: Do not take the law into your hands, for fear of falling into sin on the day of judgment.</ul><ul>Ninth Commandment: Seek to return to my kingdom, and I will meet you halfway.</ul><ul>Tenth Commandment: Once you have proven that your faith is pure, you will attain the joy of elevation and thereby become a trusted disciple.";

?>