#!/bin/bash

# Trap interrupts and exit instead of continuing the loop
trap "echo Exited!; exit;" SIGINT SIGTERM

cd ~/scripts/

LANG=en

while true
do
	touch $SHARD_PATH/logs/chat/chat.log
	export PYTHONPATH=$PYTHONPATH:$SHARD_PATH/tools
	export PYTHONIOENCODING=UTF-8
	python3 deepl.py $LANG yubo
done
