#!/bin/sh
cd /home/nevrax/scripts/Rocket.Chat

export INSTANCE_IP=127.0.0.1
export NODE_ENV=production
export ROOT_URL=https://chatdev.ryzom.com
export MONGO_URL=mongodb://arma.ryzom.com:22110/megacorp_test?replicaSet=mc
export PORT=3000
export MONGO_OPLOG_URL=mongodb://arma.ryzom.com:22110/local?replicaSet=mc
export METEOR_SETTINGS='{ "local-console-debug":true }'
node main.js --mobile-server https://chatdev.ryzom.com

