--***************************************************************--
-- this file was generated by the r2 editor, do not edit !!!!!!  --
--***************************************************************--

r2.CustomBBox.Boxes['object_campfire.creature'] = { Enabled = true, XMin = -1.001000, XMax = 0.999600, YMin = -1.001000, YMax = 0.999600, ZMin = -0.197400, ZMax = 2.069200 }