// Ryzom - MMORPG Framework <http://dev.ryzom.com/projects/ryzom/>
// Copyright (C) 2010  Winch Gate Property Limited
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by world_editor.rc
//
#define IDC_BROWSE                      3
#define ID_OPEN                         3
#define IDMORE                          3
#define IDUPDATE                        3
#define ID_REPLACE                      3
#define ID_NAME_RESET                   3
#define ID_REPLACE_ALL                  4
#define ID_NAME_ASSIGN                  4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DIALOG                      129
#define IDR_WORLDETYPE                  129
#define IDD_CREATE_ELEMENT              130
#define IDR_MAINFREAME                  130
#define IDD_TOOLS_ZONE                  131
#define IDD_SELECTZONE                  132
#define IDD_GENERATE                    133
#define IDD_MOVE                        134
#define IDD_EXPORT                      135
#define IDD_TYPEMANAGER                 136
#define IDD_TYPE                        137
#define IDD_TYPESEL                     138
#define IDR_MAINFRAME_LIGHT             139
#define IDD_PROJECT_SETTINGS            139
#define IDD_PROPERTIES                  140
#define IDC_MOVE                        141
#define IDC_ROTATE                      142
#define IDD_EXPORTCB                    143
#define IDC_TURN                        143
#define IDI_FOLDER_CLOSED               143
#define IDD_TOOLS_LOGIC                 144
#define IDI_PRIM                        144
#define IDC_SCALE                       144
#define IDI_GROUP                       145
#define IDD_EDIT_STRING                 145
#define IDC_RADIUS                      145
#define IDC_ADD_POINT                   146
#define IDI_POINT                       146
#define IDI_POINT_OPENED                146
#define IDI_POINT_HIDE                  147
#define IDC_SELECT                      147
#define IDI_LINE                        148
#define IDC_SELECT_COPY                 148
#define IDI_LINE_OPENED                 148
#define IDI_LINE_HIDE                   149
#define IDC_INSERT_POINT                149
#define IDI_ZONE_HIDE                   150
#define IDC_HAND                        150
#define IDI_ZONE                        151
#define IDI_ZONE_OPENED                 151
#define IDD_LOADING                     152
#define IDI_FOLDER_OPENED               152
#define IDD_CUSTOM_SNAPSHOT             153
#define IDI_PROPERTY_CLOSED             153
#define IDI_MAIN_FRAME                  154
#define IDI_MAINFRAME                   154
#define IDI_ROOT_CLOSED                 155
#define IDI_PROPERTY_OPENED             156
#define IDD_SELECT_PRIMITIVE_BY_LOCATION 156
#define IDC_COPY                        157
#define IDI_LINE_CLOSED                 157
#define IDD_FIND_PRIMITIVE              157
#define IDI_POINT_CLOSED                158
#define IDI_ZONE_CLOSED                 159
#define IDI_ROOT_OPENED                 160
#define IDI_FOLDER_HIDDEN               161
#define IDI_LINE_HIDDEN                 162
#define IDI_POINT_HIDDEN                163
#define IDI_PROPERTY_HIDDEN             164
#define IDI_ROOT_HIDDEN                 165
#define IDI_ZONE_HIDDEN                 166
#define IDI_ERROR_STRUCTURE             167
#define IDD_PRIMITIVE_CONFIGURATION     169
#define IDR_MENU1                       171
#define IDC_ZOOM                        172
#define IDD_GOTO_POS                    174
#define IDD_SPLASHSCREEN                175
#define IDD_DIRECTORY_SELECTOR          176
#define IDD_NAME                        177
#define IDC_EDIT_NAME                   1000
#define IDC_TITLE_VERSION               1000
#define IDC_EDIT_LAYERNAME              1001
#define IDC_PROGRESS1                   1001
#define IDC_CATTYPE1                    1002
#define IDC_COMBO1                      1002
#define IDC_CONTEXT                     1002
#define IDC_DIRLIST                     1002
#define IDC_CATVALUE1                   1003
#define ID_FIND_NEXT                    1003
#define IDC_CATTYPE2                    1004
#define IDC_PRIMITIVE_NAME              1004
#define IDC_CATVALUE2                   1005
#define IDC_RGBA                        1005
#define IDC_CATTYPE3                    1006
#define IDC_GRAY_SCALE                  1006
#define IDC_CATVALUE3                   1007
#define IDC_FIXED_SIZE                  1007
#define IDC_LIST1                       1007
#define IDC_NAME_SEARCH                 1007
#define IDC_CATTYPE4                    1008
#define IDC_GRAY_SCALE2                 1008
#define IDC_RADIO1                      1008
#define IDC_SELECTION                   1008
#define IDC_CATVALUE4                   1009
#define IDC_AND2                        1010
#define IDC_EDIT2                       1010
#define IDC_NAME_EBOX_GN                1010
#define IDC_OR2                         1011
#define IDC_CHECK_POS_ZOMM              1011
#define IDC_AND3                        1012
#define IDC_STATIC_VIDEO_MEM            1012
#define IDC_OR3                         1013
#define IDC_LOAD_WORLD_EDIT             1013
#define IDC_AND4                        1014
#define IDC_NAME_ID                     1014
#define IDC_OR4                         1015
#define IDC_RANDOM                      1018
#define IDC_NAME_EBOX_IG                1018
#define IDC_NOT_PROPAGATE               1019
#define IDC_ROT0                        1020
#define IDC_NAME_DIR                    1020
#define IDC_ROT90                       1021
#define IDC_NAME_NEWGN                  1021
#define IDC_ROT180                      1022
#define IDC_ROT270                      1023
#define IDC_ROTRANDOM                   1024
#define IDC_ROTCYCLE                    1025
#define IDC_FLIPNO                      1026
#define IDC_FLIPYES                     1027
#define IDC_FLIPRANDOM                  1028
#define IDC_FLIPCYCLE                   1029
#define IDC_LISTZONE                    1030
#define IDC_FULL_CYCLE                  1030
#define IDC_BUTTON1                     1031
#define IDC_BUTTON_REFZONEDIR           1031
#define IDC_FORCE                       1031
#define IDC_NEW_GROUP                   1031
#define IDC_EDITMINX                    1032
#define IDC_BUTTON_OUTZONEDIR           1032
#define IDC_EDITMINY                    1033
#define IDC_BUTTON_TILEBANKFILE         1033
#define IDC_EDITMAXX                    1034
#define IDC_BUTTON_HEIGHTMAPFILE        1034
#define IDC_EDITMAXY                    1035
#define IDC_BUTTON_HEIGHTMAPFILE2       1035
#define IDC_COMBOMATERIAL               1036
#define IDC_BUTTON_REFIGDIR             1036
#define IDC_EDITZONEBASEX               1037
#define IDC_BUTTON_OUTIGDIR             1037
#define IDC_EDITXOFFSET                 1038
#define IDC_BUTTON_REFCMBDIR            1038
#define IDC_EDITYOFFSET                 1039
#define IDC_BUTTON_OUTCMBDIR            1039
#define IDC_EDITZONEBASEY               1040
#define IDC_BUTTON_REFADDITIONNALIGDIR  1040
#define IDC_EDIT1                       1041
#define IDC_EDIT_REFZONEDIR             1041
#define IDC_EDIT_INFO                   1041
#define IDC_WIDTH                       1041
#define IDC_DATA_DIRECTORY              1041
#define IDC_X                           1041
#define IDC_PROPERTY                    1041
#define IDC_GOTO_POS_X                  1041
#define IDC_NAME_FILTER                 1041
#define IDC_EDIT_REFIGDIR               1042
#define IDC_HEIGHT                      1042
#define IDC_Y                           1042
#define IDC_GOTO_POS_Y                  1042
#define IDC_EDIT_REFCMBDIR              1043
#define IDC_THRESHOLD                   1043
#define IDC_VALUE                       1043
#define IDC_REPLACE_TEXT                1044
#define IDC_EDIT_OUTZONEDIR             1044
#define IDC_REMOVETYPE                  1045
#define IDC_EDIT_TILEBANKFILE           1045
#define IDC_ADDTYPE                     1046
#define IDC_EDIT_HEIGHTMAPFILE          1046
#define IDC_EDITTYPE                    1047
#define IDC_EDIT_HEIGHTMAPFILE2         1047
#define IDC_BUTTONCOLOR                 1048
#define IDC_EDIT_OUTIGDIR               1048
#define IDC_EDITNAME                    1049
#define IDC_EDIT_OUTCMBDIR              1049
#define IDC_COMBOTYPE                   1050
#define IDC_EDIT_REFADDITIONNALIGDIR    1050
#define IDC_LISTTYPE                    1051
#define IDC_EDIT_OUTADDITIONNALIGDIR    1051
#define IDC_LIST                        1052
#define IDC_BUTTON_OUTADDITIONNALIGDIR  1052
#define IDC_PROGRESS                    1053
#define IDC_PASSTEXT                    1054
#define IDC_EDIT_ZFACTOR                1055
#define IDC_EDIT_ZFACTOR2               1056
#define IDC_EDIT_ZONEMIN                1057
#define IDC_EDIT_ZONEMAX                1058
#define IDC_NEW_PATAT                   1059
#define IDC_EDIT_COLORMAPFILE           1059
#define IDC_TYPE                        1060
#define IDC_BUTTON_COLORMAPFILE         1060
#define IDC_STATIC_TEXT_LOADING         1061
#define IDC_EDIT_DFNDIR                 1061
#define IDC_BUTTON_DFNDIR               1062
#define IDC_EXPORT_COLLISIONS           1063
#define IDC_EDIT_CONTINENTFILE          1064
#define IDC_KEEPRATIO                   1064
#define IDC_BUTTON_CONTINENTFILE        1065
#define IDC_EXPORT_ADDITIONNAL_IGS      1066
#define IDC_EDIT_CONTINENTSDIR          1067
#define IDC_BUTTON_CONTINENTSDIR        1068
#define IDC_RADIOLIGHTNOISE             2042
#define IDC_RADIOLIGHTPATCH             2043
#define IDC_RADIOLIGHTNO                2044
#define IDC_SCROLLBAR_PROP              2045
#define IDC_PROPERTY_FRAME              2046
#define IDC_FIRST_PROP                  2047
#define ID_VIEW_GRID                    32771
#define ID_FILE_EXIT                    32772
#define ID_MODE_LOGIC                   32773
#define ID_MODE_ZONE                    32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_FILE_OPENLOGIC               32777
#define ID_FILE_SAVELOGIC               32778
#define ID_FILE_OPENLANDSCAPE           32779
#define ID_FILE_SAVELANDSCAPE           32780
#define ID_MODE_SELECT                  32781
#define ID_FILE_UNLOAD                  32782
#define ID_FILE_NEWLOGIC                32783
#define ID_FILE_UNLOADLOGIC             32784
#define ID_MODE_UNDO                    32785
#define ID_MODE_REDO                    32786
#define ID_FILE_GENERATE                32787
#define ID_MODE_MOVE                    32788
#define ID_FILE_EXPORT                  32789
#define ID_MODE_TYPE                    32790
#define ID_VIEW_BACKGROUND              32792
#define ID_BUTTON32795                  32795
#define ID_FILE_VIEW                    32797
#define ID_FILE_SETDATADIR              32798
#define ID_MODE_TRANSITION              32799
#define ID_MODE_COUNT_ZONES             32800
#define ID_FILE_SNAPSHOT                32801
#define ID_FILE_VIEWWITHIG              32802
#define ID_FILE_COLORSNAPSHOT           32803
#define ID_FILE_CUSTOMSNAPSHOT          32804
#define ID_BUTTON32814                  32814
#define ID_PROJECT_ADDLANDSCAPE         32815
#define ID_PROJECT_CLEARALLLANDSCAPE    32816
#define ID_PROJECT_ADDPRIMITIVEFILE     32817
#define ID_PROJECT_SETTINGS             32818
#define ID_PROJECT_ADDPRIMITIVE         32821
#define ID_PROJECT_CLEARALLPRIMITIVE    32822
#define ID_PROJECT_IMPORT_PRIM          32823
#define ID_EDIT_LOCK                    32825
#define ID_EDIT_ZONE                    32826
#define ID_EDIT_TRANSITION              32827
#define ID_EDIT_LOGIC                   32828
#define ID_EDIT_SELECT                  32829
#define ID_EDIT_TRANSLATE               32830
#define ID_EDIT_ROTATE                  32831
#define ID_EDIT_TURN                    32832
#define ID_EDIT_SCALE                   32833
#define ID_EDIT_RADIUS                  32834
#define ID_EDIT_ADD_POINT               32835
#define ID_EDIT_DELETE                  32836
#define ID_PROJECT_NEWPRIMITIVE         32837
#define ID_EDIT_PROPERTIES              32838
#define ID_EDIT_CREATE_BEGIN            32839
#define ID_EDIT_CREATE_END              33038
#define ID_EDIT_DETAILS                 33042
#define ID_VIEW_SHOW                    33043
#define ID_VIEW_HIDE                    33044
#define ID_EDIT_SELECT_CHILDREN         33045
#define ID_EDIT_EXPAND                  33046
#define ID_EDIT_COLLAPSE                33047
#define ID_EDIT_GENERATE_BEGIN          33048
#define ID_EDIT_GENERATE_END            33248
#define ID_VIEW_LANDSCAPE               33249
#define ID_EDIT_OPEN_FILE_BEGIN         33250
#define ID_EDIT_OPEN_FILE_END           33450
#define ID_VIEW_PRIMITIVES              33452
#define ID_VIEW_LAYERS                  33453
#define ID_VIEW_GRIS                    33454
#define ID_EDIT_SELECT_BY_LOCATION      33456
#define ID_BUTTON33457                  33457
#define ID_VIEW_LOCATESELECTEDPRIMITIVES 33458
#define ID_VIEW_LOCATESELECTEDPRIMITIVES_TREE 33459
#define ID_PROJECT_RESETUNIQUEID        33460
#define ID_FIND                         33461
#define ID_VIEW_COLLISIONS              33462
#define ID_RENAME_SELECTED              33463
#define ID_REPAIR_SELECTED              33464
#define ID_HELP_HISTORY                 33465
#define ID_PROJECT_NEWLANDSCAPE         33467
#define ID_EXPORT_SNAPSHOT              33468
#define ID_WINDOWS_PRIMITIVECONFIGURATION 33469
#define ID_PRIMITIVECONFIGURATION_SELECT 33470
#define ID_PRIMITIVECONFIGURATION_SHOW  33471
#define ID_PRIMITIVECONFIGURATION_HIDE  33472
#define ID_EDIT_PACS                    33473
#define ID_VIEW_PACS                    33475
#define ID_VIEW_POINTS                  33476
#define ID_PROJECT_GENERATENULLID       33477
#define ID_PROJECT_CORRECT_ID           33478
#define ID_GOTO                         33479
#define ID_PROJECT_RESET_PRIMITIVE_CONFIGURATION 33480
#define ID_SAVPOS                       33482
#define ID_MISSION_COMPILER             33483
#define ID_NAME_DLG                     33484
#define ID_INDICATOR_ZONENAMENEL        0xE710
#define ID_INDICATOR_ZONENAMEREF        0xE711
#define ID_INDICATOR_COORDINATES        0xE712
#define ID_INDICATOR_ZONEROT            59155
#define ID_INDICATOR_ZONEFLIP           59156
#define ID_INDICATOR_INFO               59157
#define ID_INDICATOR_SELECTION          59158
#define ID_WINDOWS_PLUGINS              59170

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         33485
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
