name: build
description: build
inputs:
  os:
    description: os
    required: true
  cmake-preset:
    description: cmake preset to use for configure step
    required: true
  build-version:
    description: build version
    required: true
  chocolatey-cache-dir:
    description: cache directory for chocolatey
    required: false
    default: "${{ github.workspace }}/.choco"
  hunter-cache-dir:
    description: cache directory for hunter
    required: false
    default: "${{ github.workspace }}/.hunter"
  vcpkg-cache-dir:
    description: cache directory for vcpkg
    required: false
    default: "${{ github.workspace }}/.vcpkg"
runs:
  using: composite
  steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "^3.31.11"

    - uses: lukka/run-vcpkg@v11

    - uses: actions/cache/restore@v4
      id: vcpkg-cache
      with:
        path: ${{ inputs.vcpkg-cache-dir}}
        key: vcpkg-${{ inputs.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

    - uses: actions/cache/restore@v4
      id: hunter-cache
      with:
        path: ${{ inputs.hunter-cache-dir}}
        key: hunter-${{ inputs.os }}-nel

    - name: Dependencies ${{ runner.os }}
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install --yes \
          build-essential bison ccache\
          autoconf autoconf-archive automake libtool \
          libpng-dev \
          libjpeg-dev \
          libgif-dev libfreetype-dev \
          freeglut3-dev \
          liblua5.2-dev libluabind-dev \
          libogg-dev libvorbis-dev libopenal-dev \
          libavcodec-dev libavformat-dev libavdevice-dev libswscale-dev libpostproc-dev \
          libmysqlclient-dev \
          libxml2-dev \
          libcurl4-openssl-dev libssl-dev \
          libsquish-dev \
          liblzma-dev \
          libgsf-1-dev \
          qtbase5-dev qttools5-dev qttools5-dev-tools

    - uses: actions/cache@v4
      if: runner.os == 'Windows'
      with:
        path: C:\DXSDK
        key: dxsdk-jun2010

    - name: DirectX SDK
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        IF NOT EXIST C:\DXSDK (
          aria2c https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe
          7z x DXSDK_Jun10.exe -oC:\ -r -y
          del DXSDK_Jun10.exe
        )

    - uses: actions/cache/restore@v4
      if: runner.os == 'Windows'
      id: chocolatey-cache
      with:
        path: ${{ inputs.chocolatey-cache-dir }}
        key: chocolatey-${{ inputs.os }}-${{ hashFiles('chocolatey.config') }}

    - name: Dependencies ${{ runner.os }}
      if: runner.os == 'Windows'
      shell: powershell
      run: choco install chocolatey.config --cache-location=${{ inputs.chocolatey-cache-dir }}

    - uses: actions/cache/save@v4
      if: runner.os == 'Windows'
      with:
        path: ${{ inputs.chocolatey-cache-dir }}
        key: ${{ steps.chocolatey-cache.outputs.cache-primary-key }}

    - name: Configure ccache
      shell: bash
      run: |
        ccache --set-config=max_size=1G
        ccache --set-config=compression=true
        ccache -z

    - name: Configure CMake
      if: runner.os != 'Windows'
      env:
        VCPKG_BINARY_SOURCES: "clear;files,${{ inputs.vcpkg-cache-dir }},readwrite"
        HUNTER_ROOT: ${{ inputs.hunter-cache-dir }}
      shell: bash
      run: cmake --preset ${{ inputs.cmake-preset }}

    - name: Configure CMake
      if: runner.os == 'Windows'
      env:
        VCPKG_BINARY_SOURCES: "clear;files,${{ inputs.vcpkg-cache-dir }},readwrite"
        HUNTER_ROOT: ${{ inputs.hunter-cache-dir }}
      shell: powershell
      run: cmake --preset ${{ inputs.cmake-preset }}

    - uses: actions/cache/save@v4
      if: ( ! cancelled() )
      with:
        path: ${{ inputs.vcpkg-cache-dir }}
        key: ${{ steps.vcpkg-cache.outputs.cache-primary-key }}

    - uses: actions/cache/save@v4
      if: ( ! cancelled() )
      with:
        path: ${{ inputs.hunter-cache-dir }}
        key: ${{ steps.hunter-cache.outputs.cache-primary-key }}

    - name: Build
      if: runner.os != 'Windows'
      shell: bash
      run: cmake --build --preset nel --target install

    - name: Build
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        cmake --build --preset nel
        cmake --install build/nel

    - name: ccache stats
      if: always()
      shell: bash
      run: ccache -s -v || ccache -s

    - name: Test
      shell: bash
      run: ctest --preset nel

    - uses: actions/upload-artifact@v4
      if: ( !cancelled() )
      with:
        name: nel-${{ inputs.os }}-${{ inputs.cmake-preset }}-${{ github.sha }}-test-results
        if-no-files-found: error
        path: build/reports/*.xml

    - name: Package
      if: runner.os != 'Windows'
      shell: bash
      run: cpack --preset nel -R "${{ inputs.build-version }}"

    - name: Package
      if: runner.os == 'Windows'
      shell: powershell
      run: cpack --preset nel -R "${{ inputs.build-version }}"

    - if: ( failure() )
      shell: bash
      run: find build

    - uses: actions/upload-artifact@v4
      if: ( failure() )
      with:
        name: build-logs-${{ inputs.os }}-${{ inputs.cmake-preset }}-${{ github.sha }}
        path: build/**/*.log

