name: build
description: build
inputs:
  os:
    description: os
    required: true
  build-type:
    description: link statically or dynamically value  should be static | dynamic
    required: true
  build-dir:
    description: build directory
    required: true
  build-version:
    description: build version
    required: true
runs:
  using: composite
  steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "^3.31.6"

    - name: Dependencies Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install --yes \
          build-essential ccache \
          bison autoconf automake \
          libpng-dev \
          libjpeg-dev \
          libgif-dev libfreetype6-dev \
          freeglut3-dev \
          liblua5.2-dev libluabind-dev libcpptest-dev \
          libogg-dev libvorbis-dev libopenal-dev \
          libavcodec-dev libavformat-dev libavdevice-dev libswscale-dev libpostproc-dev \
          libmysqlclient-dev \
          libxml2-dev \
          libcurl4-openssl-dev libssl-dev \
          libsquish-dev \
          liblzma-dev \
          libgsf-1-dev \
          qtbase5-dev qttools5-dev qttools5-dev-tools

    - name: Configure CMake
      if: runner.os == 'Linux'
      shell: bash
      run: cmake --preset ci-linux-nel-${{ inputs.build-type }}

    - name: Build
      shell: bash
      run: cmake --build --preset nel

    - name: Test
      shell: bash
      run: ctest --preset nel

    - uses: actions/upload-artifact@v4
      if: ( !cancelled() )
      with:
        name: nel-${{ inputs.os }}-${{ inputs.build-type }}-test-results
        if-no-files-found: error
        path: ${{ inputs.build-dir }}/reports/*.xml

    - name: Package
      shell: bash
      run: cpack --preset nel -R "${{ inputs.build-version }}"

