#ifndef NL_VERSION_H
#define NL_VERSION_H

#define NL_VERSION "${NL_VERSION}"
#define NL_PRODUCT_VERSION "${NL_PRODUCT_VERSION}"
#define NL_VERSION_MAJOR ${NL_VERSION_MAJOR}
#define NL_VERSION_MINOR ${NL_VERSION_MINOR}
#define NL_VERSION_PATCH ${NL_VERSION_PATCH}
#define NL_VERSION_NUM ${NL_VERSION_NUM}

#define NL_REVISION ${REVISION}

#define NL_BUILD_DATE "${BUILD_DATE}"

#endif
