FILE(GLOB SRCS *.cpp)
FILE(GLOB HDRS *.h)

SOURCE_GROUP("" FILES ${SRCS} ${HDRS})

NL_TARGET_LIB(nel_gltf ${SRCS} ${HDRS})

TARGET_LINK_LIBRARIES(nel_gltf NeL::misc NeL::3d)
NL_DEFAULT_PROPS(nel_gltf "NeL, Tools, 3D: NeL glTF Common")
NL_ADD_RUNTIME_FLAGS(nel_gltf)

IF(WITH_INSTALL_LIBRARIES OR NOT WITH_STATIC)
  INSTALL(TARGETS nel_gltf LIBRARY DESTINATION ${NL_LIB_PREFIX} ARCHIVE DESTINATION ${NL_LIB_PREFIX} COMPONENT tools3d)
ENDIF()
