<?xml version="1.0"?>
<TYPE Type="String" UI="NonEditableCombo" Default="common" Revision="$Revision: 1.3 $" State="modified">
  <DEFINITION Label="fyros" Value="Fyros"/>
  <DEFINITION Label="matis" Value="Matis"/>
  <DEFINITION Label="tryker" Value="Tryker"/>
  <DEFINITION Label="zorai" Value="Zorai"/>
  <DEFINITION Label="karavan" Value="Karavan"/>
  <DEFINITION Label="tribe" Value="Tribe"/>
  <DEFINITION Label="common" Value="Common"/>
  <DEFINITION Label="arma" Value="Arma"/>
  <DEFINITION Label="balduse" Value="Balduse"/>
  <DEFINITION Label="bul" Value="Bul"/>
  <DEFINITION Label="capryni" Value="Capryni"/>
  <DEFINITION Label="chonari" Value="Chonari"/>
  <DEFINITION Label="clapclap" Value="Clapclap"/>
  <DEFINITION Label="cococlaw" Value="Cococlaw"/>
  <DEFINITION Label="cute" Value="Cute"/>
  <DEFINITION Label="dag" Value="Dag"/>
  <DEFINITION Label="diranak" Value="Diranak"/>
  <DEFINITION Label="estrasson" Value="Estrasson"/>
  <DEFINITION Label="filin" Value="Filin"/>
  <DEFINITION Label="frahar" Value="Frahar"/>
  <DEFINITION Label="gibbai" Value="Gibbai"/>
  <DEFINITION Label="hachtaha" Value="Hachtaha"/>
  <DEFINITION Label="jungler" Value="Jungler"/>
  <DEFINITION Label="kakty" Value="Kakty"/>
  <DEFINITION Label="kalab" Value="Kalab"/>
  <DEFINITION Label="kami" Value="Kami"/>
  <DEFINITION Label="kazoar" Value="Kazoar"/>
  <DEFINITION Label="kitifly" Value="Kitifly"/>
  <DEFINITION Label="kitihank" Value="Kitihank"/>
  <DEFINITION Label="kitiharak" Value="Kitiharak"/>
  <DEFINITION Label="kitikil" Value="Kitikil"/>
  <DEFINITION Label="kitimandib" Value="Kitimandib"/>
  <DEFINITION Label="kitin" Value="Kitin"/>
  <DEFINITION Label="kitinagan" Value="Kitinagan"/>
  <DEFINITION Label="kitinega" Value="Kitinega"/>
  <DEFINITION Label="kitinokto" Value="Kitinokto"/>
  <DEFINITION Label="lightbird" Value="Lightbird"/>
  <DEFINITION Label="mektoub" Value="Mektoub"/>
  <DEFINITION Label="mektoubpacker" Value="MektoubPacker"/>
  <DEFINITION Label="mektoubmount" Value="MektoubMount"/>
  <DEFINITION Label="pucetron" Value="Pucetron"/>
  <DEFINITION Label="regus" Value="Regus"/>
  <DEFINITION Label="ryzerb" Value="Ryzerb"/>
  <DEFINITION Label="ryzoholo" Value="Ryzoholo"/>
  <DEFINITION Label="ryzoholok" Value="Ryzoholok"/>
  <DEFINITION Label="vampignon" Value="Vampignon"/>
  <DEFINITION Label="varinx" Value="Varinx"/>
  <DEFINITION Label="yber" Value="Yber"/>
  <DEFINITION Label="zerx" Value="Zerx"/>
  <DEFINITION Label="cephaloplant" Value="Cephaloplant"/>
  <DEFINITION Label="electroalgs" Value="Electroalgs"/>
  <DEFINITION Label="phytopsy" Value="Phytopsy"/>
  <DEFINITION Label="sapenslaver" Value="SapEnslaver"/>
  <DEFINITION Label="spittingweeds" Value="SpittingWeeds"/>
  <DEFINITION Label="swarmplants" Value="Swarmplants"/>
  <DEFINITION Label="source" Value="Source"/>
  <DEFINITION Label="unknown" Value="Unknown"/>
  <LOG>Wed May 12 19:55:03 2004 (fleury) Type Predef = </LOG>
</TYPE>
