MACRO(NL_CONFIGURE_CHECKS)
  INCLUDE(GetRevision)

  # 3D drivers
  IF(WITH_DRIVER_OPENGL)
    SET(NL_OPENGL_AVAILABLE 1)
  ENDIF()

  IF(WITH_DRIVER_OPENGLES)
    SET(NL_OPENGLES_AVAILABLE 1)
  ENDIF()

  IF(WITH_DRIVER_DIRECT3D)
    SET(NL_DIRECT3D_AVAILABLE 1)
  ENDIF()

  # sound drivers
  IF(WITH_DRIVER_FMOD)
    SET(NL_FMOD_AVAILABLE 1)
  ENDIF()

  IF(WITH_DRIVER_OPENAL)
    SET(NL_OPENAL_AVAILABLE 1)
  ENDIF()

  IF(WITH_DRIVER_DSOUND)
    SET(NL_DSOUND_AVAILABLE 1)
  ENDIF()

  IF(WITH_DRIVER_XAUDIO2)
    SET(NL_XAUDIO2_AVAILABLE 1)
  ENDIF()

  CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/config.h.cmake ${CMAKE_CURRENT_BINARY_DIR}/config.h)
  INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})
  ADD_DEFINITIONS(-DHAVE_CONFIG_H)
ENDMACRO()
