IF(assimp_FIND_REQUIRED)
  SET(ASSIMP_FIND_REQUIRED ON)
ENDIF()

FIND_PATH(
	ASSIMP_INCLUDE_DIRS
	NAMES assimp/postprocess.h assimp/scene.h assimp/version.h assimp/config.h assimp/cimport.h
	PATHS /usr/local/include/
)

FIND_LIBRARY(
	ASSIMP_LIBRARY_RELEASE
	NAMES assimp
	PATHS /usr/local/lib/
)

FIND_LIBRARY(
	IRRXML_LIBRARY_RELEASE
	NAMES IrrXML
	PATHS /usr/local/lib/
)

FIND_LIBRARY(
	ASSIMP_LIBRARY_DEBUG
	NAMES assimpd
	PATHS /usr/local/lib/
)

FIND_LIBRARY(
	IRRXML_LIBRARY_DEBUG
	NAMES IrrXMLd
	PATHS /usr/local/lib/
)

IF (ASSIMP_INCLUDE_DIRS)
    SET(ASSIMP_FOUND TRUE)
    IF(ASSIMP_LIBRARY_RELEASE)
      SET(ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES} optimized ${ASSIMP_LIBRARY_RELEASE})
    ENDIF()
    IF(ASSIMP_LIBRARY_DEBUG)
      SET(ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES} debug ${ASSIMP_LIBRARY_DEBUG})
    ENDIF()
    FIND_PACKAGE(ZLIB)
    IF(ZLIB_FOUND)
        SET(ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES} ${ZLIB_LIBRARIES})
    ENDIF()
    IF(IRRXML_LIBRARY_RELEASE)
      SET(ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES} optimized ${IRRXML_LIBRARY_RELEASE})
    ENDIF()
    IF(IRRXML_LIBRARY_DEBUG)
      SET(ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES} debug ${IRRXML_LIBRARY_DEBUG})
    ENDIF()
ENDIF()

IF (ASSIMP_FOUND)
    IF (NOT ASSIMP_FIND_QUIETLY)
        MESSAGE(STATUS "Found asset importer library: ${ASSIMP_LIBRARIES}")
    ENDIF ()
ELSE (ASSIMP_FOUND)
    IF (ASSIMP_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find asset importer library")
    ENDIF ()
ENDIF ()
