#
# - Locate CEF3 library
# This module defines
#  CEF3_LIBRARIES    the libraries to link against
#  CEF3_INCLUDE_DIR  where to find headers.
#

IF(CEF3_LIBRARIES)
  SET(CEF3_FIND_QUIETLY TRUE)
ENDIF()

FIND_PATH(CEF3_INCLUDE_DIR
  NAMES include/cef_version.h
  PATHS ${CEF3_ROOT})
SET(CEF3_INCLUDE_DIR ${CEF3_INCLUDE_DIR} ${CEF3_INCLUDE_DIR}/include)

FIND_LIBRARY(CEF3_LIBRARY_RELEASE
  NAMES cef
  PATHS ${CEF3_ROOT} PATH_SUFFIXES Release)

FIND_LIBRARY(CEF3_LIBRARY_DEBUG
  NAMES cef
  PATHS ${CEF3_ROOT} PATH_SUFFIXES Debug)
#SET(CEF3_LIBRARY
#	optimized ${CEF3_LIBRARY_RELEASE}
#	debug ${CEF3_LIBRARY_DEBUG})
SET(CEF3_LIBRARY ${CEF3_LIBRARY_RELEASE})

#
# libcef_dll_wrapper.a
#
FIND_LIBRARY(CEF3_LIBRARY_WRAPPER_RELEASE
  NAMES cef_dll_wrapper
  PATHS ${CEF3_ROOT} PATH_SUFFIXES Release)

FIND_LIBRARY(CEF3_LIBRARY_WRAPPER_DEBUG
  NAMES cef_dll_wrapper
  PATHS ${CEF3_ROOT} PATH_SUFFIXES Debug)
#SET(CEF3_LIBRARY_WRAPPER
#	optimized ${CEF3_LIBRARY_WRAPPER_RELEASE}
#	debug ${CEF3_LIBRARY_WRAPPER_DEBUG})
SET(CEF3_LIBRARY_WRAPPER ${CEF3_LIBRARY_WRAPPER_RELEASE})

SET(CEF3_LIBRARIES ${CEF3_LIBRARIES} ${CEF3_LIBRARY} ${CEF3_LIBRARY_WRAPPER})

IF(CEF3_LIBRARY AND CEF3_INCLUDE_DIR)
  SET(CEF3_FOUND "YES")
  IF(NOT CEF3_FIND_QUIETLY)
    MESSAGE(STATUS "Found Cef3: ${CEF3_LIBRARIES}")
  ENDIF()
ELSE()
  IF(NOT CEF3_FIND_QUIETLY)
    MESSAGE(STATUS "Warning: Unable to find Cef3!")
  ENDIF()
ENDIF()

