//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by nel_export.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDC_ADD                         3
#define IDS_PARAMS                      4
#define IDC_REMOVE                      4
#define IDS_SPIN                        5
#define IDC_UP                          5
#define IDC_DOWN                        6
#define IDD_PANEL                       101
#define IDD_SWT                         103
#define IDD_EXPORTSCENE                 104
#define IDD_CALCULATING                 106
#define IDD_NODE_PROPERTIES             110
#define IDD_NODE_PROPERTIES_PANEL       110
#define IDC_CURSOR1                     113
#define IDD_LOD                         116
#define IDD_ACCEL                       117
#define IDD_LIGHTMAP                    118
#define IDD_MISC                        119
#define IDD_VEGETABLE                   120
#define IDD_INSTANCE                    121
#define IDD_VERTEX_PROGRAM              122
#define IDD_VP_WINDTREE                 123
#define IDD_ANIM                        124
#define IDD_LIGHTMAP2                   126
#define IDD_LMC_CHOOSE_FROM             127
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define ID_SAVEAS                       1001
#define ID_SAVEMODEL                    1001
#define ID_SAVE                         1002
#define ID_SAVE_MODEL_ANIM              1002
#define ID_SAVESEL                      1003
#define ID_SAVE_SCENE_ANIM              1003
#define ID_BAR                          1004
#define ID_SAVESKELETON                 1004
#define ID_VIEW                         1005
#define IDC_ALLCHANNEL                  1005
#define ID_SAVESWT                      1006
#define IDC_CHANNELPOS                  1006
#define IDC_CHANNELROT                  1007
#define ID_EXPORTINSTANCEGROUP          1007
#define IDC_CHANNELSCA                  1008
#define IDC_CHECKEXPORTINSTANCEGROUP    1009
#define ID_NODE_PROPERTIES              1009
#define IDC_CHECKEXPORTSHAPES           1010
#define ID_SAVECOLLISION                1010
#define IDC_CHECKEXPORTLIGHTING         1011
#define ID_TEST_INTERFACE_MESH          1011
#define IDC_RADIONORMALEXPORTLIGHTING   1012
#define IDC_RADIORADIOSITYEXPORTLIGHTING 1013
#define IDC_EDITEXPORTINSTANCEGROUP     1014
#define IDC_CHECKOUTPUTLIGHTMAPLOG      1014
#define IDC_BUTTONEXPORTINSTANCEGROUP   1015
#define IDC_EDITEXPORTSHAPES            1016
#define IDC_BUTTONEXPORTSHAPES          1017
#define IDC_EDITEXPORTLIGHTING          1018
#define IDC_BUTTONEXPORTLIGHTING        1019
#define IDC_EDITLUMELSIZE               1020
#define IDC_RADIOSS1                    1021
#define IDC_RADIOSS2                    1022
#define IDC_RADIOSS3                    1023
#define IDC_RADIOSS4                    1024
#define IDC_PROGRESS1                   1025
#define IDC_STATICTIMELEFT              1026
#define IDC_BUTTONCANCEL                1027
#define IDC_SHADOW                      1028
#define IDC_EXCLUDE                     1029
#define IDC_LIST1                       1030
#define IDC_BLEND_IN                    1031
#define IDC_BLEND_OUT                   1032
#define IDC_COARSE_MESH                 1033
#define IDC_DIST_MAX                    1034
#define IDC_DYNAMIC_MESH                1035
#define IDC_BLEND_LENGTH                1036
#define IDC_SKIN_REDUCTION_MIN          1037
#define IDC_SKIN_REDUCTION_MAX          1038
#define IDC_SKIN_REDUCTION_BEST         1039
#define IDC_NB_LOD                      1040
#define IDC_DIVISOR                     1041
#define IDC_DIST_FINEST                 1042
#define IDC_DIST_MIDDLE                 1043
#define IDC_DIRT_COARSEST               1044
#define IDC_ACTIVE_MRM                  1045
#define IDC_ACTIVE_MRM2                 1046
#define IDC_FATHER_VISIBLE              1049
#define IDC_VISIBLE_FROM_FATHER         1050
#define IDC_DYNAMIC_PORTAL              1051
#define IDC_EDIT_INSTANCE_NAME          1052
#define IDC_FATHER_AUDIBLE              1052
#define IDC_DONT_ADD_TO_SCENE           1053
#define IDC_AUDIBLE_FROM_FATHER         1053
#define IDC_VERSION                     1054
#define IDC_AUDIBLE_LIKE_VISIBLE        1054
#define IDC_STATICINFO                  1055
#define IDC_SHOWLUMEL                   1056
#define IDC_CLUSTERIZE                  1057
#define IDC_EXPORT_NOTE_TRACK           1058
#define IDC_DONT_EXPORT                 1059
#define IDC_EDIT_INTERFACE_THRESHOLD    1059
#define IDC_EXPORT_SSS_TRACK            1059
#define IDC_EDIT_LUMELSIZEMUL           1060
#define IDC_EDIT_SOFTSHADOW_RADIUS      1061
#define IDC_EDIT_SOFTSHADOW_CONELENGTH  1062
#define IDC_REMANENCE_SAMPLING_PERIOD   1062
#define IDC_MISC_PROPERTIES             1063
#define IDC_EDIT_UV_CHANNEL_FOR_ALPHA   1064
#define IDC_FLOATING_OBJECT             1065
#define IDC_CANCEL                      1066
#define IDC_OK                          1067
#define IDC_VEGETABLE_ALPHA_BLEND_OFF   1068
#define IDC_VEGETABLE_AB_ON_LIGHTED_PRECOMPUTED 1069
#define IDC_VEGETABLE_AB_ON_UNLIGHTED   1070
#define IDC_VEGETABLE_AB_OFF_LIGHTED_PRECOMPUTED 1071
#define IDC_VEGETABLE_AB_OFF_LIGHTED_DYNAMIC 1072
#define IDC_VEGETABLE_AB_OFF_UNLIGHTED  1073
#define IDC_VEGETABLE_AB_OFF_DOUBLE_SIDED 1074
#define IDC_CENTER_NULL                 1075
#define IDC_CENTER_Z                    1076
#define IDC_VEGETABLE_BEND_FACTOR       1077
#define IDC_EXPORT_ANIMATED_MATERIALS   1078
#define IDC_LIGO_SYMMETRY               1079
#define IDC_LIGO_ROTATE                 1080
#define IDC_EXPORT_REALTIME_LIGHT       1081
#define IDC_USE_LIGHT_LOCAL_ATTENUATION 1082
#define IDC_EXPORT_LIGHTMAP_LIGHT       1083
#define IDC_EXPORT_AS_SUN_LIGHT         1084
#define IDC_COMBO_VP                    1085
#define IDC_CHECK_VP_SPECLIGHT          1086
#define IDC_EDIT_VPWT_FREQ_SCALE        1087
#define IDC_EDIT_VPWT_DIST_SCALE        1088
#define IDC_SLIDER_VPWT_FREQ_L0         1089
#define IDC_SLIDER_VPWT_FREQ_L1         1090
#define IDC_SLIDER_VPWT_FREQ_L2         1091
#define IDC_SLIDER_VPWT_DISTXY_L0       1092
#define IDC_SLIDER_VPWT_FREQWD_L0       1093
#define IDC_SLIDER_VPWT_DISTZ_L0        1094
#define IDC_SLIDER_VPWT_BIAS_L0         1095
#define IDC_SLIDER_VPWT_DISTXY_L1       1096
#define IDC_SLIDER_VPWT_FREQWD_L1       1097
#define IDC_SLIDER_VPWT_DISTZ_L1        1098
#define IDC_SLIDER_VPWT_BIAS_L1         1099
#define IDC_SLIDER_VPWT_DISTXY_L2       1100
#define IDC_SLIDER_VPWT_FREQWD_L2       1101
#define IDC_SLIDER_VPWT_DISTZ_L2        1102
#define IDC_SLIDER_VPWT_BIAS_L2         1103
#define IDC_STATIC_VPWT_FREQ_L0         1104
#define IDC_STATIC_VPWT_DISTXY_L0       1105
#define IDC_STATIC_VPWT_BIAS_L0         1106
#define IDC_STATIC_VPWT_FREQWD_L0       1107
#define IDC_STATIC_VPWT_DISTZ_L0        1108
#define IDC_STATIC_VPWT_FREQ_L1         1109
#define IDC_STATIC_VPWT_DISTXY_L1       1110
#define IDC_STATIC_VPWT_BIAS_L1         1111
#define IDC_STATIC_VPWT_FREQWD_L1       1112
#define IDC_STATIC_VPWT_DISTZ_L1        1113
#define IDC_STATIC_VPWT_FREQ_L2         1114
#define IDC_STATIC_VPWT_DISTXY_L2       1115
#define IDC_STATIC_VPWT_BIAS_L2         1116
#define IDC_STATIC_VPWT_FREQWD_L2       1117
#define IDC_STATIC_VPWT_DISTZ_L2        1118
#define IDC_EXPORT_LIGHTMAP_DYNAMIC     1119
#define IDC_EXPORT_LIGHTMAP_NAME        1120
#define IDC_SWT_WEIGHT                  1121
#define IDC_EXPORT_LIGHTMAP_ANIMATED    1122
#define IDC_SWT                         1123
#define IDC_SET_GLOBAL_LIGHT            1124
#define IDC_RESET_NAME                  1125
#define IDC_CHECK_COLLISION             1126
#define IDC_CHECK_COLLISION_EXTERIOR    1127
#define IDC_EDITCELLSIZE                1128
#define IDC_EDITCELLDELTAZ              1129
#define IDC_STATIC2                     1130
#define IDC_BYPASS_VP                   1131
#define IDC_VP_TEXT                     1132
#define IDC_AUTOMATIC_ANIM              1135
#define IDC_EXPORT_CLOD                 1136
#define IDC_GET_INTERFACE_NORMAL_FROM_SCENE_OBJECTS 1137
#define IDC_USE_REMANENCE               1138
#define IDC_REMANENCE_SHIFTING_TEXTURE  1139
#define IDC_ROLLUP_RATIO                1140
#define IDC_REMANENCE_ROLLUP_RATIO      1141
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496
#define IDC_EDIT_INTERFACE_FILE_NAME    1497
#define IDC_TEST_SURFACE_LIGHT          1498
#define IDC_EXPORT_BONE_SCALE           1499
#define IDC_EXPORT_BONE_SCALE_NAME_EXT  1500
#define IDC_EXPORT_NODE_ANIMATION       1501
#define ID_EXPORTSCENE                  1502
#define ID_OPTIONS                      1503
#define IDC_EXPORT_BG_COLOR             1504
#define IDC_INTERFACE_FILE              1505
#define IDC_EXPORT_BG_COLOR2            1505
#define IDC_EDIT_INTERFACE_FILE         1506
#define IDC_RADIAL_NORMAL_29            1507
#define IDC_RADIAL_NORMAL_30            1508
#define IDC_RADIAL_NORMAL_31            1509
#define IDC_RADIAL_NORMAL_32            1510
#define IDC_VEGETABLE_AB_ON_LIGHTED_PRECOMPUTED_ONESIDED 1511
#define IDC_EXPORT_ANIMATION_PREFIXE_NAME 1512
#define IDC_VEGETABLE_FORCE_BEST_SIDED_LIGHTING 1513
#define IDC_VEGETABLE_AB_OFF_LIGHTED_PRECOMPUTED_ONESIDED 1514
#define IDC_VEGETABLE_ALPHA_BLEND_ON    1515
#define IDC_TAB                         1516
#define IDC_VEGETABLE                   1517
#define IDC_DONT_EXPORT2                1518
#define IDC_REMANENCE_SLICE_NUMBER      1519
#define IDC_EDIT_INSTANCE_GROUP_NAME    1520
#define IDC_EDIT_INSTANCE_GROUP_NAME2   1521
#define IDC_EDIT_INSTANCE_GROUP_SHAPE   1522
#define IDC_DIST_COARSEST               1523
#define IDC_RADIOACCELNO                1524
#define IDC_RADIOACCELPORTAL            1525
#define IDC_RADIOACCELCLUSTER           1526
#define IDC_BONE_LOD_DISTANCE           1527
#define IDC_OCC_MODEL                   1528
#define IDC_OPEN_OCC_MODEL              1529
#define IDC_ENV_FX                      1531
#define IDC_SOUND_GROUP                 1532
#define IDC_LIGHT_DONT_CAST_SHADOW_INTERIOR 1536
#define IDC_LIGHT_DONT_CAST_SHADOW_EXTERIOR 1537
#define IDC_8BITS_LIGHTMAP              1537
#define IDC_LM_ALWAYS_AMBIENT           1538
#define IDC_LM_ALWAYS_DIFFUSE           1539
#define IDC_LM_DAY_AMBIENT              1540
#define IDC_LMC_COPY_ALWAYS_AMBIENT     1540
#define IDC_LM_DAY_DIFFUSE              1541
#define IDC_LMC_COPY_SUN_AMBIENT        1541
#define IDC_LM_NIGHT_AMBIENT            1542
#define IDC_LMC_COPY_SUN_DIFFUSE        1542
#define IDC_LM_NIGHT_DIFFUSE            1543
#define IDC_LMC_COPY_NIGHT_DIFFUSE      1543
#define IDC_LM_COMPRESS_8BIT            1544
#define IDC_LMC_COPY_NIGHT_AMBIENT      1544
#define IDC_LMC_STATIC0                 1545
#define IDC_LMC_STATIC1                 1546
#define IDC_LMC_STATIC2                 1547
#define IDC_LMC_STATIC3                 1548
#define IDC_LMC_STATIC4                 1549
#define IDC_LMC_STATIC5                 1550
#define IDC_LMC_STATIC6                 1551
#define IDC_LMC_STATIC7                 1552
#define IDC_LMC_STATIC8                 1553
#define IDC_LMC_AUTO_SETUP              1554
#define IDC_LMC_AUTO_SETUP_VISIBLEONLY  1555
#define IDC_CAMERA_COL_RADIO1           1555
#define IDC_CAMERA_COL_RADIO2           1556
#define IDC_CAMERA_COL_RADIO3           1557
#define IDC_LMC_COPY_FROM               1558
#define IDC_CAMERA_COL_RADIO4           1558
#define IDC_LMC_COPY_ALWAYS_AMBIENT_FILTER 1559
#define IDC_LMC_COPY_ALWAYS_DIFFUSE_FILTER 1560
#define IDC_LMC_COPY_SUN_DIFFUSE_FILTER 1561
#define IDC_LMC_COPY_SUN_AMBIENT_FILTER 1562
#define IDC_LMC_COPY_NIGHT_AMBIENT_FILTER 1563
#define IDC_LMC_COPY_NIGHT_DIFFUSE_FILTER 1564
#define IDC_LMC_COPY_CLEAR              1565
#define IDC_LMC_COPY_GET_ALL            1566
#define IDC_LMC_COPY_ALWAYS_DIFFUSE     1567
#define IDC_LMC_COPY_LIST               1568
#define IDC_REALTIME_LIGHT_AMBIENT_ADD_SUN 1569
#define IDC_LIGHT_GROUP_ALWAYS          1570
#define IDC_LIGHT_GROUP_LANDSCAPE_DIFFUSE 1571
#define IDC_LIGHT_GROUP_NIGHT_CYCLE     1572
#define IDC_LIGHT_GROUP_DAY_CYCLE       1573
#define IDC_LIGHT_GROUP_LANDSCAPE_AMBIENT 1574
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1570
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
