name: build
description: build
inputs:
  os:
    description: os
    required: true
  install-dir:
    description: install directory
    required: true
  build-dir:
    description: build directory
    required: true
  build-version:
    description: build version
    required: true
  image-group:
    description: image group
    required: true
  image-version:
    description: image version
    required: true
runs:
  using: composite
  steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "^3.31.6"

    - name: Dependencies Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install --yes \
          build-essential \
          libpng-dev \
          libjpeg-dev \
          libgif-dev libfreetype-dev \
          freeglut3-dev \
          liblua5.2-dev libluabind-dev libcpptest-dev \
          libogg-dev libvorbis-dev libopenal-dev \
          libavcodec-dev libavformat-dev libavdevice-dev libswscale-dev libpostproc-dev \
          libmysqlclient-dev \
          libcurl4-openssl-dev libssl-dev \
          libsquish-dev \
          libgsf-1-dev \
          qtbase5-dev qttools5-dev qttools5-dev-tools

    - name: Install Dependency
      if: runner.os == 'Linux'
      shell: bash
      run: >
        sh ${{ inputs.build-dir }}/nel-*.sh
        --skip-license
        --include-subdir
        --prefix=${{ inputs.install-dir }}

    - name: Configure CMake
      if: runner.os == 'Linux'
      shell: bash
      run: cmake --preset ci-linux-nelns

    - name: Build
      shell: bash
      run: cmake --build --preset nelns

    - name: Test
      shell: bash
      run: ctest --preset nelns

    - uses: actions/upload-artifact@v4
      if: ( !cancelled() )
      with:
        name: nelns-${{ inputs.os }}-test-results
        if-no-files-found: error
        path: ${{ inputs.build-dir }}/reports/*.xml

    - name: Package
      shell: bash
      run: cpack --preset nelns -R "${{ inputs.build-version }}"

    - name: Build Docker image
      shell: bash
      if: inputs.os == 'ubuntu-24.04'
      run: |
        IMAGE_TAG="${{ inputs.image-group }}/ryzomcore-nelns:${{ inputs.image-version }}"
        docker build . --file nelns/docker/Dockerfile --tag "${IMAGE_TAG}"
        docker save --output=${{ inputs.build-dir }}/nelns/nelns-docker-${{ inputs.build-version }}.tar "${IMAGE_TAG}"

