
all:
	+make $(MAKE_ALL_ARGS) -C src all

mono:
	+make -C src all

clean:
	+make -C src clean

cleansheets:
	+make -C src cleansheets

update:
	+make -C src update

touch:
	+make -C src touch
