#!/bin/bash
# ______                           _____ _                   _   _____           _
# | ___ \                         /  ___| |                 | | |_   _|         | |
# | |_/ /   _ _______  _ __ ___   \ `--.| |__   __ _ _ __ __| |   | | ___   ___ | |___
# |    / | | |_  / _ \| '_ ` _ \   `--. \ '_ \ / _` | '__/ _` |   | |/ _ \ / _ \| / __|
# | |\ \ |_| |/ / (_) | | | | | | /\__/ / | | | (_| | | | (_| |   | | (_) | (_) | \__ \
# \_| \_\__, /___\___/|_| |_| |_| \____/|_| |_|\__,_|_|  \__,_|   \_/\___/ \___/|_|___/
#        __/ |
#       |___/
#
# Ryzom - MMORPG Framework <https://ryzom.com/dev/>
# Copyright (C) 2019  Winch Gate Property Limited
# This program is free software: read https://ryzom.com/dev/copying.html for more details
#
# This script helps to manage the shard using a screen session.
# You can start, join, stop and get state of services
#

CMD=$1
DOMAIN=shard

if [[ ! -z "$2" ]]
then
	SHARD_PATH=$2
fi

if [[ -z "$CMD" ]]
then
	echo
	echo "Commands:"
	echo "  'start' to start the shard"
	echo "  'stop'  to stop the shard"
	echo "  'join'  to show the shard"
	echo "  'dev'   to show the shard in textual dev mode"
	echo
	printf "Enter a command: "
	read CMD
fi

if [ "$CMD" = "stop" ]
then
	python3 $SHARD_PATH/tools/shard.py stop
	bash $SHARD_PATH/tools/notify.sh ShardStopped
fi

if [ "$CMD" = "start" ]
then
	python3 $SHARD_PATH/tools/shard.py start
	bash $SHARD_PATH/tools/notify.sh ShardStarting
fi


if [ "$CMD" = "join" ]
then
	python3 $SHARD_PATH/tools/shard.py
fi


if [ "$CMD" = "dev" ]
then
	textual run $SHARD_PATH/tools/shard.py --dev
fi
