#!/usr/bin/env python3
"""Generate wind_tree_vp_embedded.h from compiled Cg shader files."""

import os
import sys

SHADERDIR = os.path.dirname(os.path.abspath(__file__))
OUTFILE = os.path.join(SHADERDIR, 'wind_tree_vp_embedded.h')

VARIANTS = [
    '0pl', '0pl_norm', '0pl_spec', '0pl_spec_norm',
    '1pl', '1pl_norm', '1pl_spec', '1pl_spec_norm',
    '2pl', '2pl_norm', '2pl_spec', '2pl_spec_norm',
    '3pl', '3pl_norm', '3pl_spec', '3pl_spec_norm',
]

LABELS = [
    '0PL', '0PL normalize', '0PL specular', '0PL specular + normalize',
    '1PL', '1PL normalize', '1PL specular', '1PL specular + normalize',
    '2PL', '2PL normalize', '2PL specular', '2PL specular + normalize',
    '3PL', '3PL normalize', '3PL specular', '3PL specular + normalize',
]

BS = chr(92)

def escape_c(s):
    s = s.replace(BS, BS + BS)
    s = s.replace(chr(34), BS + chr(34))
    s = s.replace(chr(9), BS + 't')
    return s


def process_arb(filepath):
    result = []
    with open(filepath, 'r') as f:
        for line in f:
            line = line.rstrip(chr(13) + chr(10))
            if line.startswith('#'):
                continue
            line = line.replace('program.local', 'program.env')
            result.append(chr(34) + escape_c(line) + BS + 'n' + chr(34))
    return result


def process_vs20(filepath):
    result = []
    with open(filepath, 'r') as f:
        for line in f:
            line = line.rstrip(chr(13) + chr(10))
            if line.startswith('//'):
                continue
            result.append(chr(34) + escape_c(line) + BS + 'n' + chr(34))
    return result


def main():
    out = []
    out.append('// Auto-generated by gen_embedded.py -- do not edit')
    out.append('// Wind tree vertex program variants embedded as C string literals')
    out.append('')

    out.append('static const char *s_windTreeARBVP1[16] = {')
    for i, (v, l) in enumerate(zip(VARIANTS, LABELS)):
        fp = os.path.join(SHADERDIR, 'wind_tree_vp_%s_arbvp1.txt' % v)
        if not os.path.isfile(fp):
            print('ERROR: Missing ' + fp, file=sys.stderr)
            sys.exit(1)
        out.append('// [%d] %s' % (i, l))
        out.extend(process_arb(fp))
        if i < 15:
            out.append(',')
    out.append('};')
    out.append('')

    out.append('static const char *s_windTreeVS20[16] = {')
    for i, (v, l) in enumerate(zip(VARIANTS, LABELS)):
        fp = os.path.join(SHADERDIR, 'wind_tree_vp_%s_vs20.txt' % v)
        if not os.path.isfile(fp):
            print('ERROR: Missing ' + fp, file=sys.stderr)
            sys.exit(1)
        out.append('// [%d] %s' % (i, l))
        out.extend(process_vs20(fp))
        if i < 15:
            out.append(',')
    out.append('};')

    NL = chr(10)
    with open(OUTFILE, 'w', newline=NL) as f:
        for line in out:
            f.write(line + NL)

    print('Generated %s' % OUTFILE)
    print('Line count: %d' % len(out))


if __name__ == '__main__':
    main()
