#!/usr/bin/env python3
"""Assemble a Max 9 MAXScript that runs the ORIGINAL NelExportInstanceGroup over every
ig-source directory of the workspace (the exact listing build_gamedata processes/ig/1_export.py
would drive), writing the RAW intermediate .ig exports — the ig_static_* stage outputs, before
ig_elevation / ig_add / ig_lighter touch them.

These intermediates are the direct byte-compare references for pipeline_max_export_ig (the
same role ~/characters/anim_export plays for the anim exporter): the .ig files under
~/core4_data are the FINAL client data (elevated + lighted), so they can only be compared
structurally. Copy the output folder back to ~/ig_export/.

The emitted script is a faithful port of processes/ig/maxscript/ig_export.ms (unhide, scan all
objects for the NEL3D_APPDATA_IGNAME appdata, per-ig select geometry+lights+helpers, call
NelExportInstanceGroup) minus the tag/retry machinery, over a generated (source dir, output
subdir) list. Requires the NelExport plugin in the running Max.

Usage: gen_ig_export.py [--out ig_export_max9.ms]
Requires ~/ryzomcore_leveldesign (workspace) and ~/ryzomcore_graphics checkouts.
"""

import argparse, os, sys

WORKSPACE = os.path.expanduser("~/ryzomcore_leveldesign/workspace")
GRAPHICS = os.path.expanduser("~/ryzomcore_graphics")

HEADER = r'''-- ============================================================================
-- ig_export_max9.ms — raw intermediate .ig exports over the whole ig corpus
-- (generated by gen_ig_export.py; do not edit the directory list by hand).
--
-- Faithful port of build_gamedata processes/ig/maxscript/ig_export.ms without
-- the tag/retry machinery: for every .max in each ig source directory, group
-- nodes by the NEL3D_APPDATA_IGNAME appdata and NelExportInstanceGroup each
-- group (geometry + lights + helpers selection, same order).
--
-- Target: the 3ds Max + NelExport install that produced the reference exports.
-- EDIT DB_ROOT / OUT_DIR below, then run. Copy OUT_DIR back to ~/ig_export/.
-- ============================================================================

global DB_ROOT = "R:\\ryzomcore_graphics\\"   -- EDIT ME: database checkout root
global OUT_DIR = "C:\\ig_export\\"            -- EDIT ME: output folder
makeDir OUT_DIR all:true

global gMan
gMan = createFile (OUT_DIR + "manifest.txt")
fn mlog s = ( if gMan != undefined do ( format "%\n" s to:gMan; flush gMan ); format "%\n" s )

NEL3D_APPDATA_IGNAME = 1423062564

fn unhidelayers =
(
	for i = 0 to (LayerManager.count - 1) do
	(
		layer = (LayerManager.getLayer i)
		layer.ishidden = false
	)
)

fn unhidecategory =
(
	if (geometry.count > 0) then
	(
		unhide geometry[1]
		if (geometry[1].ishidden == true) then
			max hide object toggle
	)
	if (shapes.count > 0) then
	(
		unhide shapes[1]
		if (shapes[1].ishidden == true) then
			max hide shape toggle
	)
	if (lights.count > 0) then
	(
		unhide lights[1]
		if (lights[1].ishidden == true) then
			max hide light toggle
	)
	if (cameras.count > 0) then
	(
		unhide cameras[1]
		if (cameras[1].ishidden == true) then
			max hide camera toggle
	)
	if (helpers.count > 0) then
	(
		unhide helpers[1]
		if (helpers[1].ishidden == true) then
			max hide helper toggle
	)
)

fn getIg node =
(
	return (getappdata node NEL3D_APPDATA_IGNAME)
)

fn runNelMaxExport inputMaxFile outputDirectory =
(
	unhidelayers()
	unhidecategory()
	max unhide all
	max select none
	clearSelection()

	ig_array = #()
	for node in objects do
	(
		ig = getIg node
		if ( (ig != undefined) and (ig != "") ) then
		(
			found = false
			for j = 1 to ig_array.count do
			(
				if (ig_array[j]==ig) then
				(
					found = true
					exit
				)
			)
			if (found == false) then
			(
				append ig_array ig
			)
		)
	)

	if (ig_array.count != 0) then
	(
		for ig = 1 to ig_array.count do
		(
			outputNelFile = (outputDirectory + ig_array[ig] + ".ig")
			max select none
			clearSelection()
			for node in geometry do
			(
				if ((getIg node) == ig_array[ig]) then
					selectmore node
			)
			for node in lights do
			(
				if ((getIg node) == ig_array[ig]) then
					selectmore node
			)
			for node in helpers do
			(
				if ((getIg node) == ig_array[ig]) then
					selectmore node
			)
			try
			(
				instancegroup2export = $selection as array
				if (NelExportInstanceGroup instancegroup2export outputNelFile) == true then
				(
					mlog ("OK " + outputNelFile)
				)
				else
				(
					mlog ("ERROR exporting ig " + ig_array[ig] + " in file " + inputMaxFile)
				)
			)
			catch
			(
				mlog ("ERROR fatal error exporting ig " + ig_array[ig] + " in file " + inputMaxFile)
			)
		)
	)
	else
	(
		mlog ("WARNING nothing exported from ig max file " + inputMaxFile)
	)
)

fn exportDir srcSubDir outSubDir =
(
	local srcDir = DB_ROOT + srcSubDir
	local outDir = OUT_DIR + outSubDir + "\\"
	makeDir (OUT_DIR + outSubDir) all:true
	files = getFiles (srcDir + "\\*.max")
	sort files
	if files.count != 0 then
	(
		for i = 1 to files.count do
		(
			inputMaxFile = files[i]
			gc()
			heapfree
			resetMAXFile #noprompt
			mlog ("FILE " + inputMaxFile)
			if (loadMaxFile inputMaxFile quiet:true) == true then
			(
				runNelMaxExport inputMaxFile outDir
			)
			else
			(
				mlog ("ERROR can't open the file " + inputMaxFile)
			)
		)
	)
	else
	(
		mlog ("WARNING no *.max file in folder " + srcDir)
	)
)

'''

FOOTER = r'''
mlog "BYE"
resetMAXFile #noPrompt
'''


def load_dirs(path):
    ns = {}
    try:
        exec(compile(open(path).read(), path, "exec"), ns)
    except Exception:
        return None
    return ns


def enumerate_ig_dirs():
    """Unique ig source dirs (workspace order), as (subdir, flat_out_name)."""
    seen = []
    for root in ("common", "ecosystems", "continents", "shard"):
        base = os.path.join(WORKSPACE, root)
        if not os.path.isdir(base):
            continue
        for name in sorted(os.listdir(base)):
            d = os.path.join(base, name, "directories.py")
            if not os.path.isfile(d):
                continue
            ns = load_dirs(d)
            if ns is None:
                continue
            for dd in (ns.get("IgOtherSourceDirectories") or []) + (ns.get("IgLandSourceDirectories") or []):
                if dd not in seen and os.path.isdir(os.path.join(GRAPHICS, dd)):
                    seen.append(dd)
    return seen


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="ig_export_max9.ms")
    args = ap.parse_args()

    dirs = enumerate_ig_dirs()
    if not dirs:
        print("no ig source directories found (missing checkouts?)")
        return 77

    with open(args.out, "w", newline="\r\n") as f:
        f.write(HEADER)
        for d in dirs:
            flat = d.replace("/", "_").replace(" ", "_")
            win = d.replace("/", "\\")
            f.write('exportDir "%s" "%s"\n' % (win, flat))
        f.write(FOOTER)
    print("wrote %s (%d source directories)" % (args.out, len(dirs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
