#!/usr/bin/env python3
"""Generate a READ-ONLY Max 9 MAXScript that loads every original corpus skeleton .max and dumps
per-bone ground truth to a manifest — nothing is modified or saved.

Unlike the regen script (gen_biped_regen.py), which recreates rigs fresh and therefore only
validates the FRESH-format decode, this dump gives Max's own evaluation of the LEGACY
(figure-version 3) records: per-node world transforms straight from the loaded figure state.
That is per-bone truth the reference .skel files cannot provide (78/169 of them predate max-file
edits — the reference-era class), and it covers the questions no fresh-format data can settle:
the corpus-era L-half finger/toe base-matrix encoding, the non-COM-parented prs:name markers,
the moved-footsteps grounds, and the two-biped kitin rigs (no createNew needed here).

Output manifest format extends the regen one:
  FILE  <name>.max
  STATE <base>            — biped.getTransform per biped node (id/link), same as regen
  NODE  <name> parent <p> ctrl <class> pos x,y,z rot x,y,z,w   — EVERY scene node, world TM
Compare with skel_corpus-style tooling / regen_corpus.py parsers (BONE lines identical).

Usage: gen_skel_gt_dump.py [--out skel_gt_dump_max9.ms]
The graphics database root on the Max machine is a GFX_ROOT variable at the top of the script
(relative paths below it match the ryzomcore_graphics checkout layout).
"""

import argparse, os, sys

from skel_corpus import enumerate_corpus, is_git_lfs_stub, SKIP_CODE

HEADER = r'''-- ============================================================================
-- skel_gt_dump_max9.ms — READ-ONLY ground-truth dump of the original corpus
-- skeleton .max files (generated by gen_skel_gt_dump.py).
--
-- Target: 3ds Max 9. Set System Unit Scale to METERS before running
-- (Customize > Units Setup), same as the differential dataset / regen runs.
-- Loads each file quietly, dumps every node's world transform (+ the biped
-- getTransform view per biped system), saves NOTHING.
-- ============================================================================

global GFX_ROOT = "C:\\ryzomcore_graphics\\"   -- EDIT ME: graphics database root
global OUT_DIR = "C:\\skel_gt\\"               -- EDIT ME: output folder
makeDir OUT_DIR all:true

global gMan
fn openManifest = ( gMan = createFile (OUT_DIR + "manifest.txt") )
fn mlog s = ( if gMan != undefined do ( format "%\n" s to:gMan; flush gMan ); format "%\n" s )

fn enumBiped com = (
  local ctrl = com.transform.controller
  local nn = biped.maxNumNodes ctrl
  local nl = biped.maxNumLinks ctrl
  local res = #()
  for i = 1 to nn do
    for j = 1 to nl do (
      local nd = biped.getNode ctrl i link:j
      if nd != undefined do append res #(nd, i, j)
    )
  res
)

fn dumpBipedState com tag = (
  mlog ("STATE\t" + tag)
  for e in (enumBiped com) do (
    local nd = e[1]
    local idl = biped.getIdLink nd
    local wp  = biped.getTransform nd #pos
    local wr  = biped.getTransform nd #rotation
    mlog ("  BONE\t" + nd.name \
      + "\tid\t" + (idl.x as string) + "\tlink\t" + (idl.y as string) \
      + "\tpos\t" + (wp.x as string) + "," + (wp.y as string) + "," + (wp.z as string) \
      + "\trot\t" + (wr.x as string) + "," + (wr.y as string) + "," + (wr.z as string) + "," + (wr.w as string))
  )
)

fn dumpAllNodes = (
  for obj in objects do (
    local pn = if obj.parent != undefined then obj.parent.name else "-"
    local cn = try ((classof obj.transform.controller) as string) catch ("?")
    local tm = obj.transform
    local wp = tm.translationpart
    local wr = tm.rotationpart
    mlog ("  NODE\t" + obj.name + "\tparent\t" + pn + "\tctrl\t" + cn \
      + "\tpos\t" + (wp.x as string) + "," + (wp.y as string) + "," + (wp.z as string) \
      + "\trot\t" + (wr.x as string) + "," + (wr.y as string) + "," + (wr.z as string) + "," + (wr.w as string))
  )
)

fn dumpFile relPath base = (
  mlog ""
  mlog ("FILE\t" + base + ".max")
  local ok = loadMaxFile (GFX_ROOT + relPath) quiet:true
  if not ok then (
    mlog ("ERROR\t" + base + "\tloadMaxFile failed")
  )
  else (
    -- biped view per system: every node whose TM controller is Vertical_Horizontal_Turn is a COM
    local coms = #()
    for obj in objects do (
      local c = try (obj.transform.controller) catch (undefined)
      if c != undefined and (classof c) as string == "Vertical_Horizontal_Turn" do append coms obj
    )
    for com in coms do dumpBipedState com (base + ":" + com.name)
    dumpAllNodes()
  )
)

openManifest()
mlog ("SKEL GT DUMP  out=" + OUT_DIR + "  maxver=" + ((maxVersion())[1] as string))
'''

FOOTER = r'''
mlog ""
mlog "DONE"
close gMan
resetMaxFile #noPrompt
-- end of file
'''


def main():
    home = os.path.expanduser("~")
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--graphics", default=os.path.join(home, "ryzomcore_graphics"))
    ap.add_argument("--workspace", default=os.path.join(home, "ryzomcore_leveldesign/workspace"))
    ap.add_argument("--out", default="skel_gt_dump_max9.ms")
    args = ap.parse_args()

    if not os.path.isdir(args.graphics) or not os.path.isdir(args.workspace):
        print("SKIP: asset checkouts not present")
        sys.exit(SKIP_CODE)

    files = enumerate_corpus(args.graphics, args.workspace)
    n = 0
    with open(args.out, "w") as out:
        out.write(HEADER)
        for d, name, full in files:
            if is_git_lfs_stub(full):
                continue
            base = os.path.splitext(name)[0]
            rel = (d + "/" + name).replace("/", "\\\\")
            # try/catch per file so one crashing asset (some kitin-queen files are known to
            # crash Max) doesn't kill the whole run
            out.write(f"try ( dumpFile \"{rel}\" \"{base}\" ) catch ( mlog (\"ERROR\\t{base}\\t\" + getCurrentException()) )\n")
            n += 1
        out.write(FOOTER)
    print(f"wrote {args.out}: {n} files")


if __name__ == "__main__":
    main()
