#!/usr/bin/env python3
"""Assemble one big Max 9 MAXScript that regenerates every biped rig in the skel corpus from
the headless exporter's decoded reconstruction (pipeline_max_export_skel --maxscript).

Running the output script in 3ds Max 9 recreates each rig with biped.createNew (structure
detected from the records) and forces every bone's figure-mode world transform to our decoded
values, then saves <name>.max and logs ground truth to manifest.txt — the same manifest format
as the differential dataset, so the analysis tooling can compare directly. This cross-validates
the decode in the ENCODE direction: Max re-derives its own records from our values, and the
regenerated files can be diffed chunk-by-chunk against the originals.

Usage: gen_biped_regen.py [--out biped_regen_max9.ms] [--bin <builddir/bin>]
Same asset-checkout requirements as skel_corpus.py.
"""

import argparse, os, subprocess, sys, tempfile

from skel_corpus import enumerate_corpus, is_git_lfs_stub, is_biped, SKIP_CODE

HEADER = r'''-- ============================================================================
-- biped_regen_max9.ms — regenerate the skel corpus bipeds from the headless
-- pipeline's decoded figure reconstruction (generated by gen_biped_regen.py;
-- fragments emitted by pipeline_max_export_skel --maxscript).
--
-- Target: 3ds Max 9. Set System Unit Scale to METERS before running
-- (Customize > Units Setup), same as the differential dataset.
--
-- For every corpus rig: biped.createNew with the structure decoded from the
-- original records, then two passes of biped.setTransform forcing each bone's
-- figure-mode WORLD pos+rot to the decoded values, then save + ground-truth
-- manifest entry (same format as the differential dataset's manifest.txt).
--
-- Cross-validation: (a) the manifest GT should match the decoded values fed
-- in (Max accepted and re-derived them), and (b) the regenerated .max files'
-- 0x9155 records can be diffed against the originals chunk-by-chunk.
-- ============================================================================

global OUT_DIR = "C:\\biped_regen\\"   -- EDIT ME: output folder
makeDir OUT_DIR all:true

global gMan
fn openManifest = ( gMan = createFile (OUT_DIR + "manifest.txt") )
fn mlog s = ( if gMan != undefined do ( format "%\n" s to:gMan; flush gMan ); format "%\n" s )

fn enumBiped com = (
  local ctrl = com.transform.controller
  local nn = biped.maxNumNodes ctrl
  local nl = biped.maxNumLinks ctrl
  local res = #()
  for i = 1 to nn do
    for j = 1 to nl do (
      local nd = biped.getNode ctrl i link:j
      if nd != undefined do append res #(nd, i, j)
    )
  res
)

fn findBoneExact com nm = (
  for e in (enumBiped com) do
    if stricmp e[1].name nm == 0 do return e[1]
  undefined
)

fn dumpState com tag = (
  mlog ("STATE\t" + tag)
  for e in (enumBiped com) do (
    local nd = e[1]
    local idl = biped.getIdLink nd
    local wp  = biped.getTransform nd #pos
    local wr  = biped.getTransform nd #rotation
    mlog ("  BONE\t" + nd.name \
      + "\tid\t" + (idl.x as string) + "\tlink\t" + (idl.y as string) \
      + "\tpos\t" + (wp.x as string) + "," + (wp.y as string) + "," + (wp.z as string) \
      + "\trot\t" + (wr.x as string) + "," + (wr.y as string) + "," + (wr.z as string) + "," + (wr.w as string))
  )
)

-- Force one bone's figure-mode WORLD transform: rotation first (about the bone
-- pivot), then position (rubber-bands the parent's length to match).
fn S2 com nm p r = (
  local nd = findBoneExact com nm
  if nd == undefined then mlog ("MISS\t" + nm)
  else (
    biped.setTransform nd #rotation r false
    biped.setTransform nd #pos p false
  )
)

-- Force a bone's LENGTH via figure-mode scale (the leg chain does NOT rubber-band on
-- setTransform #pos, unlike arms/spine — v1/v2 regen legs came out grossly mis-sized).
-- Measures the current bone->child distance in-scene and applies the ratio on the scale X
-- (length) component.
fn SL com nm childNm targetLen = (
  local nd = findBoneExact com nm
  local ch = findBoneExact com childNm
  if nd == undefined or ch == undefined then mlog ("MISS\tSL " + nm)
  else (
    local cur = distance nd.transform.pos ch.transform.pos
    if cur > 0.00001 do (
      local sc = biped.getTransform nd #scale
      sc.x = sc.x * (targetLen / cur)
      biped.setTransform nd #scale sc false
    )
  )
)

-- Force the pelvis width via uniform pelvis scale so the thigh's distance from the COM
-- matches the decoded side offset (also not rubber-banded by position forcing).
fn SW com rootNm thighNm targetOff = (
  local nd = findBoneExact com (rootNm + " Pelvis")
  local th = findBoneExact com thighNm
  if nd == undefined or th == undefined then mlog ("MISS\tSW")
  else (
    local cur = distance com.transform.pos th.transform.pos
    if cur > 0.00001 do (
      local sc = biped.getTransform nd #scale
      local ratio = targetOff / cur
      sc.x = sc.x * ratio; sc.y = sc.y * ratio; sc.z = sc.z * ratio
      biped.setTransform nd #scale sc false
    )
  )
)

fn regenFinalize com name = (
  com.transform.controller.figureMode = true
  mlog ""
  mlog ("FILE\t" + name + ".max\tCHANGE\tregen from headless decode")
  dumpState com name
  saveMaxFile (OUT_DIR + name + ".max") quiet:true
)

openManifest()
mlog ("BIPED REGEN  out=" + OUT_DIR + "  maxver=" + ((maxVersion())[1] as string))
'''

FOOTER = r'''
mlog ""
mlog "DONE"
close gMan
-- end of file
'''


def main():
    home = os.path.expanduser("~")
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--graphics", default=os.path.join(home, "ryzomcore_graphics"))
    ap.add_argument("--workspace", default=os.path.join(home, "ryzomcore_leveldesign/workspace"))
    ap.add_argument("--bin", default=os.path.join(home, "ryzomcore/build/nel-pipeline/bin"))
    ap.add_argument("--out", default="biped_regen_max9.ms")
    args = ap.parse_args()

    export_skel = os.path.join(args.bin, "pipeline_max_export_skel")
    if not os.path.isfile(export_skel):
        print(f"SKIP: missing binary {export_skel}")
        sys.exit(SKIP_CODE)
    if not os.path.isdir(args.graphics) or not os.path.isdir(args.workspace):
        print("SKIP: asset checkouts not present")
        sys.exit(SKIP_CODE)

    files = enumerate_corpus(args.graphics, args.workspace)
    n_ok = n_skip = n_fail = 0
    with open(args.out, "w") as out:
        out.write(HEADER)
        with tempfile.TemporaryDirectory() as td:
            for d, name, full in files:
                if is_git_lfs_stub(full) or not is_biped(full):
                    continue
                base = os.path.splitext(name)[0]
                frag = os.path.join(td, base + ".ms")
                skel = os.path.join(td, base + ".skel")
                r = subprocess.run([export_skel, "--maxscript", frag, full, skel],
                                   capture_output=True, text=True, timeout=120)
                if r.returncode != 0 or not os.path.isfile(frag):
                    out.write(f"-- FAIL {base}: exporter rc={r.returncode}\n\n")
                    n_fail += 1
                    continue
                with open(frag) as f:
                    text = f.read()
                if text.startswith("-- SKIP"):
                    out.write(text)
                    n_skip += 1
                    continue
                # wrap so one bad rig doesn't kill the whole run
                out.write(f"try (\n{text}) catch ( mlog (\"ERROR\\t{base}\\t\" + getCurrentException()) )\n\n")
                n_ok += 1
        out.write(FOOTER)
    print(f"wrote {args.out}: {n_ok} rigs, {n_skip} skipped, {n_fail} failed")


if __name__ == "__main__":
    main()
