<?php

$this->def['XML/UTC__PVPFLAGLASTTIMECHANGE'] = array("debug");
$this->def['XML/UTC__PVPRECENTACTIONTIME'] = array("debug");
$this->def['XML/UTC__PVPFLAGTIMESETTEDON'] = array("debug");
$this->def['XML/_REGIONKILLEDINPVP'] = array("debug");
$this->def['XML/_CREATIONPOINTSREPARTITION'] = array("debug");
$this->def['XML/UTC__FORBIDAURAUSESTARTDATE'] = array("debug");
$this->def['XML/UTC__FORBIDAURAUSEENDDATE'] = array("debug");
array_push($this->def['XML/_TITLE'],"debug");
$this->def['XML/NAMESTRINGID'] = array("debug");
$this->def['XML/_HAIRCUTEDISCOUNT'] = array("debug");
	$this->addWildcard("XML/_FORBIDPOWERDATES","debug");
$this->def['XML/_INEFFECTIVEAURAS'] = array("debug");
$this->def['XML/_INEFFECTIVEAURAS/_AURAACTIVATIONDATES'] = array("debug");
$this->def['XML/_INEFFECTIVEAURAS/_AURAACTIVATIONDATES/DEACTIVATIONDATE'] = array("debug");
$this->def['XML/_INEFFECTIVEAURAS/_AURAACTIVATIONDATES/ACTIVATIONDATE'] = array("debug");
$this->def['XML/_INEFFECTIVEAURAS/_AURAACTIVATIONDATES/CONSUMABLEFAMILYID'] = array("debug");
$this->def['XML/_INEFFECTIVEAURAS/_AURAACTIVATIONDATES/POWERTYPE'] = array("debug");
$this->def['XML/_MODIFIERSINDB'] = array("debug");
	$this->addWildcard("XML/_MODIFIERSINDB/BONUS","debug");
	$this->addWildcard("XML/_MODIFIERSINDB/MALUS","debug");
$this->def['XML/ENTITYBASE'] = array("debug");
$this->def['XML/ENTITYBASE/_SHEETID'] = array("debug");
$this->def['XML/ENTITYBASE/MELEEATTACKMODIFIERONENEMY'] = array("debug");
$this->def['XML/ENTITYBASE/MELEEATTACKMODIFIERONSELF'] = array("debug");
$this->def['XML/ENTITYBASE/MAGICCASTINGMODIFIERONSELF'] = array("debug");
$this->def['XML/ENTITYBASE/MAGICCASTINGMODIFIERONENEMY'] = array("debug");
$this->def['XML/ENTITYBASE/RANGEATTACKMODIFIERONENEMY'] = array("debug");
$this->def['XML/ENTITYBASE/RANGEATTACKMODIFIERONSELF'] = array("debug");
$this->def['XML/ENTITYBASE/ATTACKMODIFIERONSELF'] = array("debug");
$this->def['XML/ENTITYBASE/CHANCETOFAILSTRATEGY'] = array("debug");
$this->def['XML/ENTITYBASE/CHANCETOFAILSPELL'] = array("debug");
$this->def['XML/ENTITYBASE/CHANCETOFAILFABER'] = array("debug");
$this->def['XML/ENTITYBASE/CHANCETOFAILHARVEST'] = array("debug");
$this->def['XML/ENTITYBASE/CHANCETOFAILTRACKING'] = array("debug");
$this->def['XML/ENTITYBASE/MELEEATTACKSLOW'] = array("debug");
$this->def['XML/ENTITYBASE/MELEESLASHINGDAMAGEARMOR'] = array("debug");
$this->def['XML/ENTITYBASE/MELEEBLUNTDAMAGEARMOR'] = array("debug");
$this->def['XML/ENTITYBASE/MELEEPIERCINGDAMAGEARMOR'] = array("debug");
$this->def['XML/ENTITYBASE/MELEEDAMAGEMODIFIERFACTOR'] = array("debug");
$this->def['XML/ENTITYBASE/RANGEDAMAGEMODIFIERFACTOR'] = array("debug");
$this->def['XML/ENTITYBASE/CREATUREMELEETAKENDAMAGEFACTOR'] = array("debug");
$this->def['XML/ENTITYBASE/CREATURERANGETAKENDAMAGEFACTOR'] = array("debug");
$this->def['XML/ENTITYBASE/COMBATBRICKLATENCYMULTIPLIER'] = array("debug");
$this->def['XML/ENTITYBASE/MAGICBRICKLATENCYMULTIPLIER'] = array("debug");
$this->def['XML/ENTITYBASE/ARMORQUALITYMODIFIER'] = array("debug");
$this->def['XML/ENTITYBASE/WEAPONQUALITYMODIFIER'] = array("debug");
$this->def['XML/ENTITYBASE/ARMORABSORBTIONMULTIPLIER'] = array("debug");
$this->def['XML/RINGREWARDPOINTS'] = array("debug");
$this->def['XML/RINGREWARDPOINTS/RINGREWARDPOINTS/__KEY__'] = array("debug");
$this->def['XML/RINGREWARDPOINTS/RINGREWARDPOINTS/__VAL__'] = array("debug");
	$this->addWildcard("XML/_PERSISTENTEFFECTS","debug");
$this->def['XML/_PACT'] = array("debug");
$this->def['XML/_PACT/PACTNATURE'] = array("debug");
$this->def['XML/_PACT/PACTTYPE'] = array("debug");
array_push($this->def['XML/_PLAYERPETS'],"debug");
array_push($this->def['XML/_PLAYERPETS/__KEY__'],"debug");
array_push($this->def['XML/_PLAYERPETS/__VAL__'],"debug");
$this->def['XML/_PLAYERPETS/__VAL__/TICKETPETSHEETID'] = array("debug");
$this->def['XML/_PLAYERPETS/__VAL__/PRICE'] = array("debug");
$this->def['XML/_PLAYERPETS/__VAL__/OWNERID'] = array("debug");
$this->def['XML/_PLAYERPETS/__VAL__/STABLEALIAS'] = array("debug");
$this->def['XML/_PLAYERPETS/__VAL__/SLOT'] = array("debug");
$this->def['XML/_PLAYERPETS/__VAL__/ISTPALLOWED'] = array("debug");
$this->def['XML/_PLAYERPETS/__VAL__/CUSTOMNAME'] = array("debug");
$this->def['XML/STARTINGCHARACTERISTICVALUES'] = array("debug");
$this->def['XML/STARTINGCHARACTERISTICVALUES/__KEY__'] = array("debug");
$this->def['XML/STARTINGCHARACTERISTICVALUES/__VAL__'] = array("debug");
$this->def['XML/_ENCYCLOCHAR'] = array("debug");
$this->def['XML/_ENCYCLOCHAR/_ENCYCHARALBUMS'] = array("debug");
$this->def['XML/_ENCYCLOCHAR/_ENCYCHARALBUMS/ALBUMSTATE'] = array("debug");
$this->def['XML/_ENCYCLOCHAR/_ENCYCHARALBUMS/THEMAS'] = array("debug");
$this->def['XML/_ENCYCLOCHAR/_ENCYCHARALBUMS/THEMAS/THEMASTATE'] = array("debug");
$this->def['XML/_ENCYCLOCHAR/_ENCYCHARALBUMS/THEMAS/RITETASKSTATEPACKED'] = array("debug");
$this->def['XML/_GAMEEVENT'] = array("debug");
$this->def['XML/_GAMEEVENT/UTC__DATE'] = array("debug");
	$this->addWildcard("XML/ENTITYBASE/_ENTITYPOSITION","debug");
	$this->addWildcard("XML/_ENTITYPOSITION","debug");
$this->def['XML/INVISIBLE'] = array("debug");
$this->def['XML/AGGROABLE'] = array("debug");
$this->def['XML/GODMODE'] = array("debug");

?>