//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mods.rc
//
#define IDD_BENDPARAM                   101
#define IDC_TH_SELCURSOR                101
#define IDD_TAPERPARAM                  102
#define IDC_EXTRUDECUR                  102
#define IDD_SINWAVEPARAM1               103
#define IDB_FACESELTYPES                103
#define IDC_OUTLINECUR                  103
#define IDB_MASK_FACESELTYPES           104
#define IDC_SEGBREAKCUR                 104
#define IDD_SINWAVEMODPARAM             105
#define IDC_SEGREFINECUR                105
#define IDC_VERTCONNECTCUR              106
#define IDC_VERTINSERTCUR               107
#define IDD_DETACH                      109
#define IDB_BOOLEANTYPES                110
#define IDD_EM_ATTACH_MATS              110
#define IDB_MASK_BOOLEANTYPES           111
#define IDD_AUTHMSG                     116
#define IDD_AUTHORIZE                   117
#define IDB_MASK_BULBS                  117
#define IDD_TWISTPARAM                  118
#define IDB_BULBS                       118
#define IDC_ADDVERTCUR                  119
#define IDB_MASK_MIRRORTYPES            119
#define IDD_EXTRUDEPARAM                120
#define IDB_MIRRORTYPES                 120
#define IDB_EM_SELTYPES                 123
#define IDD_BOMBPARAMS                  124
#define IDB_EM_SELMASK                  124
#define IDD_ELPARAM_OBJECT              125
#define IDD_ELPARAM_PATH                126
#define IDB_PATCHSELTYPES               126
#define IDD_ELPARAM_SECTION             127
#define IDB_SPLINESELTYPES              127
#define IDD_SKEWPARAM                   129
#define IDD_NOISEPARAM                  130
#define IDD_SINWAVEOMODPARAM            131
#define IDD_LINWAVEPARAM1               132
#define IDD_LINWAVEOMODPARAM            133
#define IDD_OPTIMIZEPARAM               134
#define IDD_DISPLACEPARAM               135
#define IDD_CLUSTNODEPARAM              136
#define IDD_EM_SELECTBYMAT              137
#define IDD_WINDPARAM                   138
#define IDD_GRAVITYPARAM                139
#define IDD_DEFLECTORPARAM              140
#define IDD_UVWMAPPARAM                 141
#define IDD_EM_SELECTBYSMOOTH           143
#define IDD_DISPLACE_SOT                144
#define IDD_WINDRAIN_SOT                145
#define IDD_SINWAVE_SOT                 146
#define IDD_BOMB_SOT                    147
#define IDD_SELECTPARAM                 148
#define IDD_MATERIALPARAM               149
#define IDD_SMOOTHPARAM                 150
#define IDD_NORMALPARAM                 151
#define IDC_CUR_TRIM                    151
#define IDD_SURFREVPARAM                152
#define IDD_DISPLACEPARAM_WS            154
#define IDD_UNWRAP_FLOATER              155
#define IDB_UNWRAPTOOL                  156
#define IDC_ES_CROSS_HAIR               156
#define IDB_MASK_UNWRAPTOOL             157
#define IDD_UNWRAP_PROP                 157
#define IDB_UNWRAP_VIEW_MASK            160
#define IDB_UNWRAP_OPTION_MASK          161
#define IDB_UNWRAP_TRANSFORM            162
#define IDB_UNWRAP_TRANSFORM_MASK       163
#define IDB_UNWRAP_VERT                 164
#define IDB_UNWRAP_VERT_MASK            165
#define IDB_UNWRAP_VIEW                 166
#define IDB_UNWRAP_OPTION               167
#define IDB_SPLINESELMASK               168
#define IDB_PATCHSELMASK                169
#define IDC_BEVEL                       170
#define IDR_UNWRAP_RIGHT_MENU           171
#define IDC_ECHAMFERCUR                 172
#define IDC_VCHAMFERCUR                 173
#define IDC_SCALEY                      176
#define IDC_MOVEY                       177
#define IDC_SCALEX                      178
#define IDC_MOVEX                       179
#define IDC_ZOOMREG                     180
#define IDC_PANHAND                     181
#define IDC_ZOOM                        182
#define IDR_SMALL                       185
#define IDR_MEDIUM                      187
#define IDR_LARGE                       188
#define IDR_128                         189
#define IDR_256                         190
#define IDC_PICK_COLOR                  192
#define IDC_FILL                        193
#define IDC_TRICK                       194
#define IDC_CURSOR1                     196
#define IDI_ICON1                       197
#define IDI_ICON2                       198
#define IDI_ICON3                       199
#define IDD_MAP_ACQUIRE                 201
#define IDD_RESETXFORM_PANEL            202
#define IDD_AFRPARAM                    203
#define IDD_TESSPARAM                   204
#define IDD_FACEEXTRUDEPARAM            209
#define IDD_UVWXFORMPARAM               210
#define IDD_MIRRORPARAM                 211
#define IDD_UNWRAP_PARAMS               212
#define IDD_PASTE_NAMEDSET              213
#define IDD_SEL_NAMEDSET                214
#define IDD_WINDGRAV_SOT                215
#define IDS_ADV_SURF_APPROX_WARNING_TITLE 322
#define IDS_ADV_SURF_APPROX_WARNING     323
#define IDS_PW_PICK                     324
#define IDS_PW_SNAP                     325
#define IDS_PW_WELD                     326
#define IDS_PW_FACEMAP                  327
#define IDS_PW_SELECTFACE               328
#define IDS_PW_UVWFILES                 329
#define IDS_PW_SAVEOBJECT               330
#define IDS_PW_FILEEXISTS               331
#define IDS_PW_LOADOBJECT               332
#define IDS_PW_MIRRORH                  333
#define IDS_PW_EXPANDSELECTION          334
#define IDS_PW_FALLOFF                  335
#define IDS_PW_FALLOFFSPACE             336
#define IDS_PW_BREAK                    337
#define IDS_PW_LOCKSELECTED             338
#define IDS_PW_HIDE                     339
#define IDS_PW_FREEZE                   340
#define IDS_PW_FACEFILTER               341
#define IDS_PW_LEVEL                    342
#define IDS_PW_USE_AR                   343
#define IDS_PW_PINCH                    344
#define IDS_PW_BUBBLE                   345
#define IDS_PW_METHOD                   346
#define IDS_PW_TYPE                     347
#define IDS_PW_VOLUME                   348
#define IDS_PW_INVERT                   349
#define IDS_PW_NODE                     350
#define IDS_PW_TEXMAP                   351
#define IDS_PW_CHANNEL                  352
#define IDS_PW_MAP                      353
#define IDS_PW_MIRRORV                  354
#define IDS_PW_CONTRACTSELECTION        355
#define IDS_PW_FALLOFFSPACEUVW          356
#define IDS_PW_UNHIDE                   357
#define IDS_PW_UNFREEZE                 358
#define IDS_PW_FALLOFF2                 359
#define IDD_SURF_APPROX_ADV             413
#define IDD_EM_SELECT                   414
#define IDD_EM_GEOM                     415
#define IDD_EM_SURF_VERT                416
#define IDD_EM_SURF_FACE                417
#define IDD_EM_SURF_EDGE                418
#define IDD_EM_CREATECURVE              419
#define IDD_EM_DETACH                   420
#define IDD_MESH_SELECT                 421
#define IDD_MESHSEL_AFFECTREGION        422
#define IDC_ANGLE                       1000
#define IDC_X                           1001
#define IDC_PHASE                       1001
#define IDC_Y                           1002
#define IDC_Z                           1003
#define IDC_DIR                         1004
#define IDC_TWIST_BIAS                  1004
#define IDC_EM_IGNORE_VISEDGE           1004
#define IDC_ANGLESPINNER                1005
#define IDC_MODNOISE_SEED               1005
#define IDC_EM_IGNORE_BACKFACES         1005
#define IDC_DIRSPINNER                  1006
#define IDC_TWIST_BIASSPIN              1006
#define IDC_CRV                         1007
#define IDC_PHASESPINNER                1007
#define IDC_MODNOISE_SEEDSPIN           1007
#define IDC_OPT_BIAS                    1007
#define IDC_DISP_UTILE                  1007
#define IDC_NS_LIST                     1007
#define IDC_AMT                         1008
#define IDC_DECAYSPINNER                1008
#define IDC_MODNOISE_ROUGHNESS          1008
#define IDC_OPT_BIASSPIN                1008
#define IDC_DISP_UTILESPIN              1008
#define IDC_SET_NAME                    1008
#define IDC_AMTSPINNER                  1009
#define IDC_DECAY                       1009
#define IDC_MODNOISE_ROUGHNESSSPIN      1009
#define IDC_DISP_VTILE                  1009
#define IDC_OPT_MAXEDGE                 1009
#define IDC_CRVSPINNER                  1010
#define IDC_MODNOISE_ITERATIONS         1010
#define IDC_DISP_VTILESPIN              1010
#define IDC_OPT_MAXEDGESPIN             1010
#define IDC_AMPLITUDE                   1011
#define IDC_TAPER_FROM                  1011
#define IDC_MODNOISE_ITERATIONSSPIN     1011
#define IDC_DISP_STRENGTH               1011
#define IDC_EM_DETACH_ELEM              1011
#define IDC_AMPSPINNER                  1012
#define IDC_TAPER_TO                    1012
#define IDC_DISP_STRENGTHSPIN           1012
#define IDC_WAVELEN                     1013
#define IDC_TAPER_FROMSPIN              1013
#define IDC_DISP_DECAY                  1013
#define IDC_EM_NUMBER_SEL               1013
#define IDC_NUMSEL_LABEL                1013
#define IDC_EM_DETACH_CLONE             1013
#define IDC_WAVELENSPINNER              1014
#define IDC_TAPER_TOSPIN                1014
#define IDC_DISP_DECAYSPIN              1014
#define IDC_CIRCLES                     1015
#define IDC_DISP_BLUR                   1015
#define IDC_CIRCLESSPINNER              1016
#define IDC_DISP_BLURSPIN               1016
#define IDC_EMCURVE_NAME                1016
#define IDC_SEGS                        1017
#define IDC_DISP_CENTERL                1017
#define IDC_EMCURVE_SMOOTH              1017
#define IDC_SVN_SELECTED                1017
#define IDC_WELDTESS                    1017
#define IDC_SEGSPINNER                  1018
#define IDC_DISP_CENTERLSPIN            1018
#define IDC_EMCURVE_LINEAR              1018
#define IDC_DIVISIONS                   1019
#define IDC_EMCURVE_IGNOREHIDDEN        1019
#define IDC_DIVSPINNER                  1020
#define IDC_FLEX                        1021
#define IDC_STRENGTH                    1021
#define IDC_AMPSPINNER2                 1021
#define IDC_FLEXSPINNER                 1022
#define IDC_STRENGTHSPIN                1022
#define IDC_AMPLITUDE2                  1022
#define IDC_AUTHORIZE                   1023
#define IDC_GRAVITYSPIN                 1023
#define IDC_LOCKID                      1024
#define IDC_GRAVITY                     1024
#define IDC_EDIT2                       1025
#define IDC_DETONATIONSPIN              1025
#define IDC_DETACH                      1026
#define IDC_DETONATION                  1026
#define IDC_BOMB_CHAOSSPIN              1027
#define IDC_BOMB_CHAOS                  1028
#define IDC_WELDTHRESH                  1030
#define IDC_THRESHSPINNER               1031
#define IDC_LENGTH_EDIT                 1031
#define IDC_SMOOTH_THRESHSPIN           1035
#define IDC_EM_VERT_SELG                1035
#define IDC_TES_EDGE                    1036
#define IDC_SMOOTH_THRESH               1036
#define IDC_TES_CENTER                  1037
#define IDC_TENSION                     1039
#define IDC_MAT_IDSPIN                  1039
#define IDC_MAT_ID                      1040
#define IDC_WELD                        1041
#define IDC_WELDCUR                     1041
#define IDC_ES_INSERT                   1042
#define IDC_TESS_U_SPIN                 1042
#define IDC_LEVEL                       1043
#define IDC_ES_BREAK                    1043
#define IDC_LEVELSPINNER                1044
#define IDC_ES_MAKEFIRST                1044
#define IDC_TESS_V_SPIN                 1044
#define IDC_TES_FACE_TRI                1045
#define IDC_SELTYPE                     1045
#define IDC_ES_FUSE                     1045
#define IDC_ES_CLOSE                    1046
#define IDC_TES_FACE_POLY               1047
#define IDC_ES_OUTLINE                  1047
#define IDC_ES_BOOLEAN                  1048
#define IDC_ES_OUTCENTER                1049
#define IDC_DETACHCOPY                  1050
#define IDC_LENGTH_SPIN                 1050
#define IDC_ES_FILLET                   1050
#define IDC_EM_ALIGNCONST               1051
#define IDC_ES_EXPLODE                  1051
#define IDC_ATTACH                      1052
#define IDC_ATTACHCUR                   1052
#define IDC_EM_ANGLETHRESH              1052
#define IDC_ES_CHAMFER                  1052
#define IDC_EM_REMOVE_ISO_VERTS         1053
#define IDC_ES_CREATELINE               1053
#define IDC_EM_CREATE_CURVE             1054
#define IDC_ES_ATTACH_MULTIPLE          1054
#define IDC_DETACH_NAME                 1055
#define IDC_ALIGNMIN                    1055
#define IDC_ES_CROSS_INSERT             1055
#define IDD_EDSPLINE_OPS                1055
#define IDC_GETSHAPE                    1056
#define IDC_EM_SPLIT                    1056
#define IDD_EDSPLINE_SELECT             1056
#define IDC_LOCK_HANDLES                1057
#define IDC_EM_REFINE                   1057
#define IDD_EDPATCH_SELECT              1057
#define IDC_LOCKALIKE                   1058
#define IDC_ALIGNCENTER                 1058
#define IDC_EM_CUT                      1058
#define IDC_ES_SEGDIVIDE                1058
#define IDD_EDPATCH_OPS                 1058
#define IDC_LOCKALL                     1059
#define IDC_ALIGNMAX                    1059
#define IDC_EM_SLICEPLANE               1059
#define IDD_SELECTBYMAT                 1059
#define IDC_ATTACHREORIENT              1060
#define IDC_EM_SLICE                    1060
#define IDC_SHOW_VERTEX_NUMBERS         1060
#define IDC_DETACHREORIENT              1061
#define IDC_EM_TES_TEXT                 1061
#define IDD_EM_CLONE                    1061
#define IDC_AREA_SELECTION              1061
#define IDC_EM_EXP_TEXT                 1062
#define IDC_ES_SAMESHAPE                1062
#define IDD_EM_EXPLODE                  1062
#define IDC_AMOUNT                      1063
#define IDC_EM_PIXELS_TEXT              1063
#define IDC_ES_OUTLINESPINNER           1063
#define IDD_DISP_APPROX_ADV             1063
#define IDC_AMOUNTSPINNER               1064
#define IDC_ES_OUTLINEWIDTH             1064
#define IDC_NO_SMOOTH                   1064
#define IDC_SEGMENTSPINNER              1065
#define IDC_ADDTRI                      1065
#define IDC_ES_BOOL_TYPE                1065
#define IDC_SEGMENTS                    1066
#define IDC_ADDQUAD                     1066
#define IDC_ES_FILLETWIDTH              1066
#define IDC_CAPSTART                    1067
#define IDC_ES_MIRROR                   1067
#define IDC_CAPEND                      1068
#define IDC_ES_MIRROR_TYPE              1068
#define IDC_ES_COPY_MIRROR              1069
#define IDC_HIDE                        1069
#define IDC_SECDELETE                   1070
#define IDC_ES_REVERSE                  1070
#define IDC_UNHIDE                      1070
#define IDC_GETPATH                     1071
#define IDC_SECALIGN                    1071
#define IDC_BIND                        1071
#define IDC_ES_FILLETSPINNER            1071
#define IDC_SECCENTER                   1072
#define IDC_UNBIND                      1072
#define IDC_ES_CHAMFERWIDTH             1072
#define IDC_ALIGNTYPES                  1073
#define IDC_ES_CHAMFERSPINNER           1073
#define IDC_PAINT                       1073
#define IDC_ES_ABOUT_PIVOT              1074
#define IDC_TURN                        1074
#define IDC_ES_RCLINEAR                 1075
#define IDC_TURN2                       1075
#define IDC_ES_SHOW_SELECTED            1076
#define IDC_ES_TRIM                     1077
#define IDC_ES_RCCLOSED                 1078
#define IDC_ES_BINDFIRST                1079
#define IDC_ES_BINDLAST                 1080
#define IDC_ES_EXTEND                   1081
#define IDC_ES_TRIM_INFINITE            1082
#define IDC_ES_RCONNECT                 1083
#define IDC_FALLOFF                     1086
#define IDC_EM_DELETE                   1086
#define IDC_FALLOFFSPIN                 1087
#define IDC_PINCHSPIN                   1088
#define IDC_SPIN                        1088
#define IDC_EM_T_THR_SPIN               1088
#define IDC_PINCH                       1089
#define IDC_SPINSPIN                    1089
#define IDC_BUBBLESPIN                  1090
#define IDC_MINFRAG                     1090
#define IDC_BUBBLE                      1091
#define IDC_MINFRAGSPIN                 1091
#define IDC_NEARLABEL                   1092
#define IDC_MAXFRAG                     1092
#define IDC_FARLEFTLABEL                1093
#define IDC_MAXFRAGSPIN                 1093
#define IDC_FARRIGHTLABEL               1094
#define IDC_SEED                        1094
#define IDC_AR_GRAPH                    1095
#define IDC_SEEDSPIN                    1095
#define IDC_TENSTEXT                    1096
#define IDC_EM_VERT_SELRSPIN            1096
#define IDC_EM_E_ITER_SPIN              1096
#define IDC_EM_VERT_SELGSPIN            1097
#define IDC_TAPER_AFFECTREGION          1098
#define IDC_EM_VERT_SELBSPIN            1098
#define IDC_EFFECT_X                    1104
#define IDC_EFFECT_Y                    1105
#define IDC_EFFECT_BOTH                 1106
#define IDC_TAPER_SYMMETRY              1107
#define IDC_BEND_AFFECTREGION           1108
#define IDC_BEND_TO                     1109
#define IDC_BEND_TOSPIN                 1110
#define IDC_BEND_FROM                   1111
#define IDC_BEND_FROMSPIN               1112
#define IDC_TWIST_AFFECTREGION          1113
#define IDC_MODNOISE_FRACTAL            1113
#define IDC_MERGE_SPINNER               1113
#define IDC_TWIST_TO                    1114
#define IDC_MODNOISE_ANIMATE            1114
#define IDC_TWIST_TOSPIN                1115
#define IDC_EM_EXTYPE_A                 1115
#define IDC_TWIST_FROM                  1116
#define IDC_EM_EXTYPE_B                 1116
#define IDC_TWIST_FROMSPIN              1117
#define IDC_MERGE                       1117
#define IDC_SKEW_AMOUNT                 1118
#define IDC_EP_SM_SMOOTH                1118
#define IDC_SKEW_AMOUNTSPIN             1119
#define IDC_EP_SM_SMOOTH2               1119
#define IDC_SKEW_AFFECTREGION           1120
#define IDC_EP_SM_SMOOTH3               1120
#define IDC_SKEW_TO                     1121
#define IDC_EM_CLONE_OBJ                1121
#define IDC_EP_SM_SMOOTH4               1121
#define IDC_SKEW_TOSPIN                 1122
#define IDC_EM_CLONE_ELEM               1122
#define IDC_EP_SM_SMOOTH5               1122
#define IDC_SKEW_FROM                   1123
#define IDC_DO_SUBDIV                   1123
#define IDC_EP_SM_SMOOTH6               1123
#define IDC_SKEW_FROMSPIN               1124
#define IDC_MODNOISE_XSTRENGTH          1127
#define IDC_MODNOISE_XSTRENGTHSPIN      1128
#define IDC_MODNOISE_YSTRENGTH          1129
#define IDC_MODNOISE_YSTRENGTHSPIN      1130
#define IDC_MODNOISE_ZSTRENGTH          1131
#define IDC_TESS_MIN_REC_SPINNER        1131
#define IDC_MODNOISE_ZSTRENGTHSPIN      1132
#define IDC_TESS_MAX_REC_SPINNER        1132
#define IDC_MODNOISE_SCALE              1133
#define IDC_TESS_MAX_TRIS_SPINNER       1133
#define IDC_MODNOISE_SCALESPIN          1134
#define IDC_MODNOISE_ROUGHNESSLABEL     1135
#define IDC_TESS_MIN_REC                1135
#define IDC_MODNOISE_FREQ               1136
#define IDC_OPT_PRESERVEMAT             1136
#define IDC_TESS_MAX_REC                1136
#define IDC_MODNOISE_FREQSPIN           1137
#define IDC_OPT_RENDERL1                1137
#define IDC_TESS_MAX_TRIS               1137
#define IDC_OPT_RENDERL2                1138
#define IDC_MODNOISE_PHASE              1138
#define IDC_OPT_VIEWSL1                 1139
#define IDC_MODNOISE_PHASESPIN          1139
#define IDC_OPT_VIEWSL2                 1140
#define IDC_MODNOISE_ITERATIONSLABEL    1140
#define IDC_OPT_FACETHRESH              1141
#define IDC_OPT_FACETHRESHSPIN          1142
#define IDD_DISP_APPROX                 1142
#define IDC_OPT_EDGETHRESH              1143
#define IDD_MESHER_DISP_APPROX          1143
#define IDC_OPT_EDGETHRESHSPIN          1144
#define IDD_NSPLINE                     1144
#define IDC_OPT_PRESERVESMOOTH          1145
#define IDD_EM_AFFECTREGION             1145
#define IDC_OPT_AUTOEDGE                1146
#define IDD_ES_EXPLODE                  1146
#define IDC_OPT_VERTCOUNT               1147
#define IDC_TESS_LDA                    1147
#define IDC_OPT_FACECOUNT               1148
#define IDD_EDSPLINE_SURF               1148
#define IDC_DISP_PLANAR                 1149
#define IDD_EDPATCH_SURF                1149
#define IDC_DISP_CYL                    1150
#define IDD_EDPATCH_SURF_OBJ            1150
#define IDC_DISP_SPHERE                 1151
#define IDD_NOISEPARAM_VIZ              1151
#define IDD_EDPATCH_TILE                1151
#define IDC_DISP_USEMAP                 1152
#define IDD_EDPATCH_EDGE                1152
#define IDC_DISP_APPLYMAP               1153
#define IDC_DISP_CENTERLUM              1154
#define IDC_DISP_PICKIMAGE              1155
#define IDC_DISP_REMOVEIMAGE            1156
#define IDC_CLUST_PICKNODE              1157
#define IDC_DISP_PICKMAP                1157
#define IDC_CLUST_NODENAME              1158
#define IDC_DISP_REMOVEMAP              1158
#define IDC_DISPLENGTH                  1161
#define IDC_DISPLENGTHSPIN              1162
#define IDC_WIND_STRENGTH               1163
#define IDC_WIND_STRENGTHSPIN           1164
#define IDC_FORCE_PLANAR                1165
#define IDC_FORCE_SPHERICAL             1166
#define IDC_WIND_DECAYSPIN              1167
#define IDC_WIND_DECAY                  1168
#define IDC_WIND_TURBSPIN               1169
#define IDC_WIND_TURB                   1170
#define IDC_GRAV_STRENGTH               1171
#define IDC_WIND_FREQSPIN               1171
#define IDC_GRAV_STRENGTHSPIN           1172
#define IDC_WIND_FREQ                   1172
#define IDC_GRAV_DECAY                  1173
#define IDC_WIND_SCALESPIN              1173
#define IDC_GRAV_DECAYSPIN              1174
#define IDC_WIND_SCALE                  1174
#define IDC_DEFLECT_BOUNCE              1175
#define IDC_DEFLECT_BOUNCESPIN          1176
#define IDC_DEFLECT_WIDTH               1177
#define IDC_DEFLECT_WIDTHSPIN           1178
#define IDC_DEFLECT_HEIGHTSPIN          1179
#define IDC_MAP_PLANAR                  1179
#define IDC_DEFLECT_HEIGHT              1180
#define IDC_MAP_CYL                     1180
#define IDC_ES_DIVISIONS                1180
#define IDC_MAP_SPHERE                  1181
#define IDC_ES_DIVSSPINNER              1181
#define IDC_MAP_BALL                    1182
#define IDC_MAP_FIT                     1183
#define IDC_MAP_CENTER                  1184
#define IDC_MAP_VIEWALIGN               1185
#define IDC_MAP_NORMALALIGN             1186
#define IDC_MAP_BOX                     1187
#define IDC_MAP_FITREGION               1188
#define IDC_PATCH_DELETE                1188
#define IDC_MAP_BITMAPFIT               1189
#define IDC_RESET                       1189
#define IDC_MAP_UFLIP                   1190
#define IDC_MAP_VFLIP                   1191
#define IDC_MAP_UTILESPIN               1192
#define IDC_MAP_VTILESPIN               1193
#define IDC_MAP_VTILE                   1194
#define IDC_MAP_UTILE                   1195
#define IDC_MAP_WTILE                   1196
#define IDC_SMOOTH_AUTO                 1196
#define IDC_MAP_WTILESPIN               1197
#define IDC_SMOOTH_PREVENTINDIRECT      1197
#define IDC_MAP_WFLIP                   1198
#define IDC_MAP_UOFFSET                 1199
#define IDC_MAP_RESET                   1199
#define IDC_SELECT_BYID                 1200
#define IDC_CLEARSELECTION              1200
#define IDC_MAP_VOFFSET                 1200
#define IDC_MAP_ACQUIRE                 1200
#define IDC_SEL_OBJECT                  1201
#define IDC_MAP_WOFFSET                 1201
#define IDC_MAP_FACE                    1201
#define IDC_SELECTBYSMOOTH              1201
#define IDC_SEL_VERTEX                  1202
#define IDC_MAP_UOFFSETSPIN             1202
#define IDC_MAP_LENGTH                  1202
#define IDC_EM_SMOOTH_CLEAR             1202
#define IDC_SMOOTH_CLEAR                1202
#define IDC_SEL_FACE                    1203
#define IDC_MAP_VOFFSETSPIN             1203
#define IDC_MAP_WIDTH                   1203
#define IDC_BALANCE_SELECTED            1203
#define IDC_SEL_ADD                     1204
#define IDC_MAP_WOFFSETSPIN             1204
#define IDC_MAP_HEIGHT                  1204
#define IDC_EM_NORMAL_FLIPMODE          1204
#define IDC_SEL_SUBTRACT                1205
#define IDC_MAP_LENGTHSPIN              1205
#define IDC_SEL_REPLACE                 1206
#define IDC_MAP_WIDTHSPIN               1206
#define IDC_SEL_WINDOW                  1207
#define IDC_MAP_HEIGHTSPIN              1207
#define IDC_SEL_CROSSING                1208
#define IDC_MAP_XYZTOUVW                1208
#define IDC_SEL_FIT                     1212
#define IDC_SEL_CENTER                  1213
#define IDC_SEL_RESET                   1214
#define IDC_MATID                       1215
#define IDC_MATIDSPIN                   1216
#define IDC_SEL_OBJECT_BUTTON           1217
#define IDC_SEL_INVERT                  1218
#define IDC_NORM_UNIFY                  1219
#define IDC_SEL_TEXTURE_BUTTON          1219
#define IDC_NORM_FLIP                   1220
#define IDC_MAP_CAP                     1220
#define IDC_SEL_BOXB                    1220
#define IDC_DEGREES                     1221
#define IDC_SEL_SPHEREB                 1221
#define IDC_DEGREESSPINNER              1222
#define IDC_SEL_CYLINDERB               1222
#define IDC_MORPHCAP                    1223
#define IDC_SEL_MESH_OBJECTB            1223
#define IDC_GRIDCAP                     1224
#define IDC_SEL_AUTOFIT                 1224
#define IDC_SEL_MATB                    1225
#define IDC_WELDCORE                    1226
#define IDC_SEL_SMGROUPB                1226
#define IDC_SEL_TEXTURE_MAPB            1227
#define IDC_DISPLATTICE                 1229
#define IDC_DISPSURFACE                 1230
#define IDC_SUBDIVIDE                   1233
#define IDC_PROPAGATE                   1235
#define IDC_STEPS                       1237
#define IDC_STEPSSPINNER                1238
#define IDC_DISP_BALL                   1239
#define IDC_TESS_U_SPINNER              1239
#define IDC_STEPS_RENDER                1239
#define IDC_TESS_U                      1240
#define IDC_STEPSRENDERSPINNER          1240
#define IDC_TESS_V_SPINNER              1241
#define IDC_TILESTEPS                   1241
#define IDC_DISP_WTILE                  1242
#define IDC_TESS_V                      1242
#define IDC_TILESTEPSSPINNER            1242
#define IDC_DISP_WTILESPIN              1243
#define IDC_TESS_DIST_SPINNER           1243
#define IDC_TRANSITION                  1243
#define IDC_DISP_WFLIP                  1244
#define IDC_TESS_DIST                   1244
#define IDC_TRANSITIONSPINNER           1244
#define IDC_DISP_VFLIP                  1245
#define IDC_TESS_ANG_SPINNER            1245
#define IDC_DISP_UFLIP                  1246
#define IDC_TESS_ANG                    1246
#define IDC_DISP_FIT                    1247
#define IDC_TESS_EDGE_SPINNER           1247
#define IDC_DISP_CENTER                 1248
#define IDC_TESS_EDGE                   1248
#define IDC_DISP_BITMAPFIT              1249
#define IDC_DISP_NORMALALIGN            1250
#define IDC_DISP_RESET                  1251
#define IDC_DISP_ACQUIRE                1252
#define IDC_PATCH                       1254
#define IDC_MESH                        1255
#define IDC_FILTVERTS                   1255
#define IDC_FILTVECS                    1256
#define IDC_GENMAPPING                  1257
#define IDC_EM_VERT_SELBYCOLOR          1257
#define IDC_FLIPNORMALS                 1258
#define IDC_SPLINE_VERT_COUNT           1259
#define IDC_GEN_MATIDS                  1259
#define IDC_USE_SHAPE_IDS               1260
#define IDC_RESETTM_SELECTED            1261
#define IDC_SMOOTH                      1261
#define IDC_AFR_FALLOFF                 1262
#define IDC_AFR_FALLOFFSPIN             1263
#define IDC_AFR_BACKFACE                1264
#define IDC_EXT_SCALE                   1264
#define IDC_EXT_SCALESPIN               1265
#define IDC_AFR_PINCH                   1266
#define IDC_TENSIONSPIN                 1266
#define IDC_AFR_PINCHSPIN               1267
#define IDC_ITERATIONS1                 1267
#define IDC_AFR_BUBBLE                  1268
#define IDC_ITERATIONS2                 1268
#define IDC_AFR_BUBBLESPIN              1269
#define IDC_ITERATIONS3                 1269
#define IDC_ITERATIONS4                 1270
#define IDC_EXT_CENTER                  1271
#define IDC_EXT_AMOUNT                  1272
#define IDC_EXT_AMOUNTSPIN              1273
#define IDC_DISP_VIEWALIGN              1274
#define IDC_DISP_FITREGION              1275
#define IDS_MIRROR_X                    1277
#define IDS_MIRROR_Y                    1278
#define IDS_MIRROR_Z                    1279
#define IDS_MIRROR_XY                   1280
#define IDS_MIRROR_YZ                   1281
#define IDS_MIRROR_ZX                   1282
#define IDC_MIRROR_COPY                 1283
#define IDC_MIRROR_OFFSET               1284
#define IDC_MIRROR_OFFSETSPIN           1285
#define IDC_UNWRAP_EDIT                 1287
#define IDC_UNWARP_TOOLBAR              1288
#define IDC_UNWRAP_RESET                1288
#define IDC_GRID                        1288
#define IDC_TREE                        1289
#define IDC_UNWRAP_VERTS_TOOLBAR        1289
#define IDC_UNWRAP_SAVE                 1289
#define IDC_UNWRAP_VIEW                 1290
#define IDC_UNWRAP_LOAD                 1290
#define IDC_UNWRAP_LINECOLOR            1291
#define IDC_UNWRAP_OPTION_TOOLBAR       1291
#define IDC_UNWARP_VIEW_TOOLBAR         1292
#define IDC_UNWRAP_SELCOLOR             1293
#define IDC_UNWRAP_FILTER_TOOLBAR       1293
#define IDC_UNWRAP_CONSTANTUPDATE       1294
#define IDC_UNWRAP_WIDTH                1295
#define IDC_UNWRAP_WIDTHSPIN            1296
#define IDC_UNWRAP_HEIGHT               1297
#define IDC_UNWRAP_HEIGHTSPIN           1298
#define IDC_UNWRAP_DEFAULTS             1299
#define IDC_UNWRAP_SELECT_VERTS         1300
#define IDC_TESS_VIEW                   1301
#define IDC_UNWRAP_MIDPIXEL_SNAP        1301
#define IDC_TESS_RENDERER               1302
#define IDC_UNWRAP_WELDTHRESH           1302
#define IDC_TESS_SET                    1303
#define IDC_UNWRAP_WELDTHRESHSPIN       1303
#define IDC_UNWRAP_USEBITMAPRES         1304
#define IDC_OPT_UPDATE                  1305
#define IDC_TESS_PARAM                  1305
#define IDC_OPT_MANUPDATE               1306
#define IDC_TESS_SPATIAL                1306
#define IDC_TESS_CURV                   1307
#define IDC_DISP_CAP                    1307
#define IDC_TESS_VIEW_DEP               1308
#define IDC_SHOW_INTERIOR_FACES         1309
#define IDC_MAP_CHAN1                   1310
#define IDC_TILE_MODE                   1310
#define IDC_LENGTH_LABEL                1311
#define IDC_KEEP_MAPPING                1311
#define IDC_MAP_CHAN2                   1312
#define IDC_INCLUDE_MESHES              1312
#define IDC_WIDTH_LABEL                 1313
#define IDC_HEIGHT_LABEL                1314
#define IDC_MAP_X                       1315
#define IDC_MAP_Y                       1316
#define IDC_EM_VERT_SELCOLOR            1316
#define IDC_MAP_Z                       1317
#define IDC_DISP_LENGTH                 1318
#define IDC_DISP_LENGTHSPIN             1319
#define IDC_DISP_WIDTH                  1320
#define IDC_DISP_WIDTHSPIN              1321
#define IDC_DISP_HEIGHT                 1322
#define IDC_DISP_HEIGHTSPIN             1323
#define IDC_DISP_X                      1324
#define IDC_DISP_Y                      1325
#define IDC_DISP_Z                      1326
#define IDC_NURBS                       1327
#define IDC_UNWRAP_U                    1328
#define IDC_ADVANCED                    1328
#define IDC_EM_EXPLODE                  1328
#define IDC_ADVANCED_PARAMETERS         1328
#define IDC_UNWRAP_USPIN                1329
#define IDC_EM_CREATE                   1329
#define IDC_UNWRAP_ULABEL               1330
#define IDC_EM_DETACH                   1330
#define IDC_UNWRAP_V                    1331
#define IDC_FALLOFF_ON                  1331
#define IDC_UNWRAP_VSPIN                1332
#define IDC_TESS_REGULAR                1332
#define IDC_EM_WELDTOVERT               1332
#define IDC_UNWRAP_VLABEL               1333
#define IDC_EM_SELTYPE                  1333
#define IDC_UNWRAP_W                    1334
#define IDC_EM_SEL_BYVERT               1334
#define IDC_EM_VERT_SELR                1334
#define IDC_UNWRAP_WSPIN                1335
#define IDC_EM_PLANAR                   1335
#define IDC_EM_SMOOTH_THRESHSPIN        1335
#define IDC_UNWRAP_WLABEL               1336
#define IDC_EM_PLANARSPINNER            1336
#define IDC_EM_SMOOTH_THRESH            1336
#define IDC_EM_MAKEPLANAR               1337
#define IDC_EM_NORMAL_SCALESPIN         1337
#define IDC_UNWRAP_STR                  1337
#define IDC_EM_EXTRUDE                  1338
#define IDC_EM_NORMAL_SCALE             1338
#define IDC_UNWRAP_STRSPIN              1338
#define IDC_EP_EXTRUDE                  1338
#define IDC_EM_EXTRUDEAMOUNT            1339
#define IDC_EM_MAT_IDSPIN               1339
#define IDC_EP_EXTRUDEAMOUNT            1339
#define IDC_EM_EXTRUDESPINNER           1340
#define IDC_EM_MAT_ID                   1340
#define IDC_EP_EXTRUDESPINNER           1340
#define IDC_EM_AFFECT_REGION            1341
#define IDC_EM_TESSELLATE               1342
#define IDC_EM_TENSION                  1343
#define IDC_EM_E_DIST                   1345
#define IDC_EM_TENSIONSPINNER           1346
#define IDC_EM_COLLAPSE                 1347
#define IDC_EM_E_ITER                   1348
#define IDC_EM_HIDE                     1349
#define IDC_EM_TES_EDGE                 1349
#define IDC_EM_UNHIDEALL                1350
#define IDC_EM_TES_CENTER               1350
#define IDC_EM_ANGLETHRESHSPIN          1351
#define IDC_EM_COPYNS                   1351
#define IDC_EM_NORMAL_SHOW              1352
#define IDC_EM_PASTENS                  1352
#define IDC_EM_OUTLINEAMOUNT            1352
#define IDC_EP_OUTLINEAMOUNT            1352
#define IDC_EM_NORMAL_FLIP              1353
#define IDC_EM_OUTLINESPINNER           1353
#define IDC_EP_OUTLINESPINNER           1353
#define IDC_EM_NORMAL_UNIFY             1354
#define IDC_EM_SELECT_OPEN              1355
#define IDC_EM_VERT_COLOR               1355
#define IDC_EM_SELECT_BYID              1356
#define IDC_EM_SELECTBYSMOOTH           1357
#define IDC_EM_SMOOTH_AUTO              1358
#define IDC_EM_DETACH_NAME              1359
#define IDC_EM_DETACH_NAMELABEL         1360
#define IDC_MS_IGNORE_BACKFACES         1361
#define IDC_MS_IGNORE_VISEDGE           1362
#define IDC_MS_SEL_BYVERT               1363
#define IDC_MS_PLANAR_TEXT              1364
#define IDC_MS_PLANAR                   1365
#define IDC_MS_PLANARSPINNER            1366
#define IDC_MS_GETVERT                  1367
#define IDC_MS_GETFACE                  1368
#define IDC_MS_GETEDGE                  1369
#define IDC_MS_COPYNS                   1370
#define IDC_MS_PASTENS                  1371
#define IDC_MS_NUMBER_SEL               1372
#define IDC_MS_SELTYPE                  1373
#define IDC_MS_MATID                    1374
#define IDC_MS_MATIDSPIN                1375
#define IDC_MS_SELBYMAT                 1376
#define IDC_EM_EXP_OBJECTS              1377
#define IDC_MS_SELBYMAT_BOX             1377
#define IDC_EM_EXP_ELEMENTS             1378
#define IDC_MS_SELBYMAT_TEXT            1378
#define IDC_EM_OBJ_ATTACH               1379
#define IDC_MS_SELOPEN                  1379
#define IDC_MS_AR_USE                   1380
#define IDC_FALLOFF_LABEL               1381
#define IDC_PINCH_LABEL                 1382
#define IDC_BUBBLE_LABEL                1383
#define IDC_DISP                        1386
#define IDC_UNWRAP_APPLY                1390
#define IDC_FOO                         1391
#define IDC_UNWRAP_ALIGN_TO_NORMAL      1391
#define IDC_MAP_TEXMAP                  1392
#define IDC_UNWRAP_FIT                  1392
#define IDC_MAP_VERTCOL                 1393
#define IDC_MAP_CHAN                    1394
#define IDC_MAP_CHAN_SPIN               1395
#define IDC_VS_MATID                    1396
#define IDC_VS_MATIDSPIN                1397
#define IDC_VS_SMG                      1398
#define IDC_VS_SMGSPIN                  1399
#define IDC_DELAUNAY                    1416
#define IDC_PRESET3                     1425
#define IDC_PRESET2                     1427
#define IDC_PRESET1                     1429
#define IDC_EM_W_THR                    1431
#define IDC_ES_DELETE                   1434
#define IDC_EM_T_THR                    1435
#define IDC_NS_COPY                     1435
#define IDC_EM_VERT_SELB                1436
#define IDC_NS_PASTE                    1436
#define IDC_ES_BIND                     1436
#define IDC_ES_REFINE                   1437
#define IDC_ES_DETACH                   1438
#define IDC_ES_CONNECT                  1439
#define IDC_ES_ATTACH                   1440
#define IDC_ES_ATTACHREORIENT           1441
#define IDC_ES_WELD                     1442
#define IDC_ES_WELDTHRESH               1443
#define IDC_ES_THRESHSPINNER            1444
#define IDC_ES_DETACHREORIENT           1445
#define IDC_ES_DETACHCOPY               1446
#define IDC_ES_UNBIND                   1447
#define IDC_ES_HIDE                     1448
#define IDC_EM_DIVIDE                   1449
#define IDC_ES_CROSSTHRESH              1449
#define IDC_EM_ALIGNVIEW                1450
#define IDC_ES_CROSSTHRESHSPINNER       1450
#define IDC_TESS_NORMALS                1451
#define IDC_ES_UNHIDE                   1451
#define IDC_ES_CYCLE                    1452
#define IDC_TO_SPLINES                  1480
#define IDC_EM_TURN                     1481
#define IDC_TO_OBJECTS                  1481
#define IDC_EM_EDGE_VIS                 1482
#define IDC_EM_EDGE_INVIS               1483
#define IDC_EM_EDGE_AUTO                1484
#define IDC_SELECTAREA                  1484
#define IDC_SELECTAREA_SPIN             1485
#define IDC_ACQUIRE_REL                 1552
#define IDC_ACQUIRE_ABS                 1553
#define IDC_EM_WELD                     1584
#define IDC_EM_W_THR_SPIN               1685
#define IDC_SMOOTH_GRP1                 1701
#define IDC_SMOOTH_GRP2                 1702
#define IDC_SMOOTH_GRP3                 1703
#define IDC_SMOOTH_GRP4                 1704
#define IDC_SMOOTH_GRP5                 1705
#define IDC_SMOOTH_GRP6                 1706
#define IDC_SMOOTH_GRP7                 1707
#define IDC_SMOOTH_GRP8                 1708
#define IDC_SMOOTH_GRP9                 1709
#define IDC_SMOOTH_GRP10                1710
#define IDC_SMOOTH_GRP11                1711
#define IDC_SMOOTH_GRP12                1712
#define IDC_SMOOTH_GRP13                1713
#define IDC_SMOOTH_GRP14                1714
#define IDC_SMOOTH_GRP15                1715
#define IDC_SMOOTH_GRP16                1716
#define IDC_SMOOTH_GRP17                1717
#define IDC_SMOOTH_GRP18                1718
#define IDC_SMOOTH_GRP19                1719
#define IDC_SMOOTH_GRP20                1720
#define IDC_SMOOTH_GRP21                1721
#define IDC_SMOOTH_GRP22                1722
#define IDC_SMOOTH_GRP23                1723
#define IDC_SMOOTH_GRP24                1724
#define IDC_SMOOTH_GRP25                1725
#define IDC_SMOOTH_GRP26                1726
#define IDC_SMOOTH_GRP27                1727
#define IDC_SMOOTH_GRP28                1728
#define IDC_SMOOTH_GRP29                1729
#define IDC_SMOOTH_GRP30                1730
#define IDC_SMOOTH_GRP31                1731
#define IDC_SMOOTH_GRP32                1732
#define IDC_EP_HOOPSON                  1734
#define IDC_EM_CLONE_NAME               1735
#define IDC_EM_EXPLODE_NAMELABEL        1736
#define IDC_ES_EXPLODE_NAMELABEL        1736
#define IDC_EM_EXPLODE_NAME             1737
#define IDC_ES_EXPLODE_NAME             1737
#define IDC_EM_BEVEL                    1738
#define IDC_EP_BEVEL                    1738
#define IDC_EM_AE_SET                   1739
#define IDC_EM_AR_BACK                  1740
#define IDC_EM_AE_CLEAR                 1741
#define IDC_RADIO1                      1741
#define IDC_EM_AE_SETCLEAR              1742
#define IDC_RADIO2                      1742
#define IDC_CUSTOM                      1742
#define IDC_RADIO3                      1743
#define IDC_UPDATE                      1743
#define IDC_RADIO4                      1744
#define IDC_SPLITMESH                   1744
#define IDC_NURBS_TXT_SRF               1746
#define IDC_EM_WEIGHT                   1749
#define IDC_EM_WEIGHTSPIN               1750
#define IDC_EM_WEIGHT_LABEL             1751
#define IDC_DISP_CHAN                   1752
#define IDC_DISP_CHAN_SPIN              1753
#define IDC_DISP_TEXMAP                 1754
#define IDC_DISP_VERTCOL                1755
#define ID_VERSION                      1756
#define IDC_TESS_U2                     1757
#define IDC_TESS_V2                     1758
#define IDC_TILE_MAT                    1759
#define IDC_TILE_MAT_SPIN               1760
#define IDC_TILE_ROT                    1761
#define IDC_TILE_ROT_SPIN               1762
#define IDC_VERSION                     1764
#define IDC_TESS_RECALC                 3012
#define IDC_TESS_UPDATE_RENDER          3016
#define IDC_TESS_UPDATE_MANUAL          3017
#define IDC_TESS_UPDATE_ALWAYS          3018
#define IDC_BOOLUNION                   5010
#define IDC_BOOLSUBTRACTION             5011
#define IDC_BOOLINTERSECTION            5012
#define IDC_CROSSINSERTCUR              5016
#define IDC_FILLETCUR                   5017
#define IDC_CHAMFERCUR                  5018
#define IDS_DS_MOVE2                    10004
#define IDS_DS_SELECT                   10007
#define IDS_DS_CREATE                   10008
#define IDS_RB_EXTRUDE                  30001
#define IDS_RB_TAPER                    30003
#define IDS_RB_OBJECT                   30004
#define IDS_RB_EDITMESH                 30009
#define IDS_RB_VERTEX                   30011
#define IDS_RB_FACE                     30012
#define IDS_RB_EDGE                     30013
#define IDS_RB_CENTER                   30014
#define IDS_RB_APPARATUS                30015
#define IDS_RB_EDITMESH_CLASS           30022
#define IDS_RB_PARAMETERS               30028
#define IDS_RB_ANGLE                    30029
#define IDS_RB_DIRECTION                30030
#define IDS_RB_AMOUNT                   30031
#define IDS_RB_AMOUNT2                  30032
#define IDS_RB_CURVITURE                30033
#define IDS_RB_AMPLITUDE                30034
#define IDS_RB_WAVELEN                  30035
#define IDS_RB_PHASE                    30036
#define IDS_RB_DECAY                    30037
#define IDS_RB_FLEXIBILITY              30038
#define IDS_RB_WIDTH                    30039
#define IDS_RB_HEIGHT                   30040
#define IDS_DB_EXTRUDE                  30041
#define IDS_RB_NONE                     30137
#define IDS_RB_RIPPLE                   30155
#define IDS_RB_RIPPLE_BINDING           30156
#define IDS_RB_DELETEVERT               30211
#define IDS_RB_DELETEFACE               30212
#define IDS_RB_ADDVERTS                 30213
#define IDS_RB_ATTACHOBJECT             30214
#define IDS_RB_FACECOLLAPSE             30215
#define IDS_RB_MAKEPLANAR               30216
#define IDS_RB_BUILDFACE                30217
#define IDS_RB_HIDEFACE                 30218
#define IDS_RB_UNHIDEALLFACES           30219
#define IDS_RB_EDGEVISIBLE              30220
#define IDS_RB_EDGEINVISIBLE            30221
#define IDS_RB_AUTOEDGE                 30222
#define IDS_RB_EDGEDIVIDE               30223
#define IDS_RB_EDGETURN                 30224
#define IDS_RB_DELETEEDGE               30225
#define IDS_RB_COLLAPSEEDGE             30226
#define IDS_RB_CLONE                    30227
#define IDS_RB_TESSELLATE               30228
#define IDS_RB_DELETEISOLATED           30229
#define IDS_PW_PLANAR                   30230
#define IDS_PW_LATTICE                  30231
#define IDS_RB_DEFDEFORMATIONS          30270
#define IDS_RB_DEFEDIT                  30271
#define IDS_RB_NODEXFORM                30276
#define IDS_RB_NODEXFORM_CLASS          30277
#define IDS_RB_XFORM_CLASS              30278
#define IDS_RB_EDITSURFACE              30279
#define IDS_RB_SETSMOOTHGROUP           30280
#define IDS_RB_ASSIGNMATID              30281
#define IDS_RB_FLIPNORMALS              30282
#define IDS_RB_UNIFYNORMALS             30283
#define IDS_RB_AUTOSMOOTH               30284
#define IDS_RB_SELECTBYMATID            30285
#define IDS_RB_SELECTBYSMOOTH           30286
#define IDS_RB_SOT                      30287
#define IDS_RB_DEFLECTOR_CLASS          30288
#define IDS_RB_HIDEVERT                 30294
#define IDS_RB_DEFSURFACE               30298
#define IDS_RB_SCALE                    30377
#define IDS_RB_NOISE                    30411
#define IDS_RB_ROTATION2                30521
#define IDS_RB_TWIST                    30522
#define IDS_RB_BENDMOD                  30543
#define IDS_RB_BEND2                    30544
#define IDS_RB_FROM                     30545
#define IDS_RB_TO                       30546
#define IDS_RB_BOMBOBJECT               30547
#define IDS_RB_BOMB                     30548
#define IDS_RB_BOMBMOD                  30549
#define IDS_RB_BOMBBINDING              30550
#define IDS_RB_CLUSTNODEMOD             30551
#define IDS_RB_XFORM                    30552
#define IDS_RB_DEFLECTOR                30553
#define IDS_RB_DEFLECTMOD               30554
#define IDS_RB_DEFLECTORBINDING         30555
#define IDS_RB_BOUNCE                   30556
#define IDS_RB_DISPMOD                  30557
#define IDS_RB_DISPLACE                 30558
#define IDS_RB_DISPLACEMOD              30559
#define IDS_RB_DISPLACEBINDING          30560
#define IDS_RB_SELECTDISPIMAGE          30561
#define IDS_RB_SELECTIMAGE              30562
#define IDS_RB_UTILE                    30563
#define IDS_RB_VTILE                    30564
#define IDS_RB_WTILE                    30565
#define IDS_RB_BLUR                     30566
#define IDS_RB_DOCREATENEWOBJECT        30567
#define IDS_RB_EDITMESH2                30568
#define IDS_RB_GRAVITY                  30569
#define IDS_RB_WIND                     30570
#define IDS_RB_GRAVITYMOD               30571
#define IDS_RB_GRAVITYBINDING           30572
#define IDS_RB_WINDMOD                  30573
#define IDS_RB_WINDBINDING              30574
#define IDS_RB_TURBULENCE               30575
#define IDS_RB_FREQUENCY                30576
#define IDS_RB_MAPMOD                   30577
#define IDS_RB_UVWMAPPING               30578
#define IDS_RB_UVWMAP                   30579
#define IDS_RB_NOISEMOD                 30580
#define IDS_RB_SEED                     30581
#define IDS_RB_FRACTAL                  30582
#define IDS_RB_ROUGH                    30583
#define IDS_RB_ITERATIONS               30584
#define IDS_RB_OPTMOD                   30585
#define IDS_RB_OPTIMIZE                 30586
#define IDS_RB_FACETHRESHL1             30587
#define IDS_RB_FACETHRESHL2             30588
#define IDS_RB_EDGETHRESHL1             30589
#define IDS_RB_EDGETHRESHL2             30590
#define IDS_RB_BIASL1                   30591
#define IDS_RB_BIASL2                   30592
#define IDS_RB_EDITMESHMOD              30593
#define IDS_RB_TWISTMOD                 30594
#define IDS_RB_TWIST2                   30595
#define IDS_RB_TWISTPLUGIN              30596
#define IDS_RB_BIAS                     30597
#define IDS_RB_INCORRECTSTRING          30598
#define IDS_RB_AUTHORIZATION            30599
#define IDS_RB_TAPERMOD                 30600
#define IDS_RB_SYMMETRY                 30601
#define IDS_RB_MATMOD                   30602
#define IDS_RB_MATERIAL3                30603
#define IDS_RB_MATERIALID               30604
#define IDS_RB_MATERIAL4                30605
#define IDS_RB_MATERIALID2              30606
#define IDS_RB_SMOOTHMOD                30607
#define IDS_RB_NORMALMOD                30608
#define IDS_RB_SKEWMOD                  30609
#define IDS_RB_SKEW                     30610
#define IDS_RB_SMOOTH2                  30611
#define IDS_RB_WAVE                     30612
#define IDS_RB_WAVEMOD                  30613
#define IDS_RB_WAVEBINDING              30614
#define IDS_RB_AMPLITUDE1               30615
#define IDS_RB_AMPLITUDE2               30616
#define IDS_RB_VOLSELECT                30617
#define IDS_RB_THRESHOLD                30618
#define IDS_RB_GIZMO                    30619
#define IDS_RB_NORMAL                   30620
#define IDS_RB_BEND_CLASS               30621
#define IDS_RB_DISPLACE_CLASS           30622
#define IDS_RB_VOLSELECT_CLASS          30623
#define IDS_RB_SKEW_CLASS               30624
#define IDS_RB_MATERIAL3_CLASS          30625
#define IDS_RB_SMOOTH2_CLASS            30626
#define IDS_RB_NORMAL_CLASS             30627
#define IDS_TH_LATHE_CLASS              30628
#define IDS_RB_EXPLODE                  30629
#define IDS_RB_COLLAPSE                 30630
#define IDS_RB_WELDVERTS                30631
#define IDS_RB_TAPER_CLASS              30632
#define IDS_RB_TWIST2_CLASS             30633
#define IDS_RB_TWIST_CLASS              30634
#define IDS_RB_BOMBOBJECT_CLASS         30635
#define IDS_RB_BOMB_CLASS               30636
#define IDS_RB_RIPPLE_CLASS             30637
#define IDS_RB_WAVE_CLASS               30638
#define IDS_RB_STRENGTH2                30646
#define IDS_DS_MOVE                     30647
#define IDS_RB_FACESEL                  30651
#define IDS_RB_POLYGONSEL               30652
#define IDS_RB_ELEMENTSEL               30653
#define IDS_RB_NOVERTSTOWELD            30680
#define IDS_RB_CHAOS                    30681
#define IDS_RB_DETONATION               30682
#define IDS_RB_BOMBPARAMS               30683
#define IDS_RB_EDITMESHTITLE            30684
#define IDS_RB_DUPFACEWARNING           30685
#define IDS_RB_NUMVERTSELP              30699
#define IDS_RB_NUMFACESELP              30701
#define IDS_RB_NUMEDGESELP              30703
#define IDS_EM_BEVEL                    30738
#define IDS_EM_OUTLINE                  30739
#define IDS_ADV_DISP_APPROX_WARNING_TITLE 30740
#define IDS_ADV_DISP_APPROX_WARNING     30741
#define ID_UNWRAP_MOVE                  40002
#define ID_UNWRAP_ROTATE                40003
#define ID_UNWRAP_SCALE                 40004
#define ID_UNWRAP                       40005
#define ID_UNWRAP_BREAK                 40006
#define ID_UNWRAP_WELD                  40007
#define ID_UNWRAP_WELDSELECTED          40008
#define ID_UNWRAP_PAN                   40010
#define ID_UNWRAP_ZOOM                  40011
#define ID_UNWRAP_ZOOMREGION            40012
#define ID_UNWRAP_EXTENT                40013
#define ID_UNWRAP_MIRROR                40014
#define IDS_TH_EDITSPLINE               40025
#define IDS_TH_EDITSEGMENT              40026
#define IDS_TH_EDITVERTEX               40027
#define IDS_TH_SPLINE                   40028
#define IDS_TH_SEGMENT                  40029
#define IDS_TH_VERTEX                   40030
#define IDS_TH_EDITOBJECT               40031
#define IDS_TH_EDITPATCH_CLASS          40032
#define IDS_TH_EDITSPLINE_CLASS         40033
#define IDS_RB_EXTRUDE_CLASS            40034
#define IDS_RB_GRAVITY_CLASS            40035
#define IDS_RB_WIND_CLASS               40036
#define IDS_RB_UVWMAP_CLASS             40037
#define IDS_RB_NOISE_CLASS              40038
#define IDS_TH_CLOSESPLINE              40039
#define IDS_RB_OPTIMIZE_CLASS           40040
#define IDS_TH_DELETESPLINE             40041
#define IDS_TH_NOVALIDSPLINESSEL        40042
#define IDS_TH_NOSPLINESSEL             40043
#define IDS_TH_VERTBREAK                40044
#define IDS_TH_NOVALIDVERTSSEL          40045
#define IDS_TH_SEGDELETE                40046
#define IDS_TH_NOSEGSSEL                40047
#define IDS_TH_DETACHSPLINE             40048
#define IDS_TH_OUTLINE                  40049
#define IDS_TH_SEGDETACH                40050
#define IDS_TH_SHAPE                    40051
#define IDS_TH_REFINE                   40052
#define IDS_TH_SEGBREAK                 40053
#define IDS_TH_VERTCONNECT              40054
#define IDS_TH_VERTINSERT               40055
#define IDS_TH_VERTWELD                 40056
#define IDS_TH_NOWELDPERFORMED          40057
#define IDS_TH_SELECTONESPLINE          40058
#define IDS_TH_MORETHANONESPLINESEL     40059
#define IDS_TH_BOOLEAN                  40060
#define IDS_TH_UNION                    40061
#define IDS_TH_SUBTRACTION              40062
#define IDS_TH_INTERSECTION             40063
#define IDS_TH_BOOLWELDFAILED           40064
#define IDS_TH_COINCIDENTVERTEX         40065
#define IDS_TH_SPLINESMUSTOVERLAP       40066
#define IDS_TH_SELECTCLOSEDSPLINE       40067
#define IDS_TH_SPLINESELFINTERSECTS     40068
#define IDS_TH_ATTACH                   40069
#define IDS_TH_CANHAVEONLYONESHAPE      40070
#define IDS_TH_NOVERTSSEL               40071
#define IDS_TH_VERTCHANGE               40072
#define IDS_TH_SMOOTH                   40073
#define IDS_TH_CORNER                   40074
#define IDS_RB_RESETXFORM_CLASS         40075
#define IDS_TH_BEZIER                   40076
#define IDS_TH_SEGCHANGE                40077
#define IDS_TH_CURVE                    40078
#define IDS_TH_LINE                     40079
#define IDS_TH_VERTDELETE               40080
#define IDS_TH_BEZIERCORNER             40081
#define IDS_TH_AMOUNT                   40082
#define IDS_TH_EDITPATCH                40083
#define IDS_TH_PATCH                    40084
#define IDS_TH_SEGMENTS                 40085
#define IDS_TH_PATCHDELETE              40086
#define IDS_TH_NOPATCHESSEL             40087
#define IDS_TH_MAKEFIRST                40160
#define IDS_TH_EDITEDGE                 40170
#define IDS_TH_EDGE                     40171
#define IDS_TH_AUTOINTERIOR             40172
#define IDS_TH_MANUALINTERIOR           40173
#define IDS_TH_NOVALIDEDGESSEL          40174
#define IDS_TH_PATCHADD                 40175
#define IDS_TH_EDGESUBDIVIDE            40176
#define IDS_TH_PATCHSUBDIVIDE           40177
#define IDS_TH_CREATELINE               40178
#define IDS_TH_MIRROR_H                 40179
#define IDS_TH_MIRROR_V                 40180
#define IDS_TH_MIRROR_BOTH              40181
#define IDS_TH_MIRROR                   40182
#define IDS_TH_PATCHCHANGE              40186
#define IDS_TH_COPLANAR                 40187
#define IDS_TH_POLYCONNECT              40190
#define IDS_TH_CONNECT_COINCIDENT       40191
#define IDS_TH_CANHAVEONLYONEPATCH      40192
#define IDS_TH_DETACHPATCH              40193
#define IDS_TH_COPY_SPLINE              40196
#define IDS_TH_COPY_SEGMENT             40197
#define IDS_TH_SPLINECHANGE             40201
#define IDS_TH_MIRRORSPLINE             40279
#define IDS_TH_DEGREES                  40308
#define IDS_TH_AXIS                     40309
#define IDS_TH_LATHE                    40310
#define IDS_TH_VERTWELDRESULT           40316
#define IDS_RB_RESETXFORM               40317
#define IDS_RB_AFRMOD                   40318
#define IDS_RB_STARTPOINT               40319
#define IDS_RB_ENDPOINT                 40320
#define IDS_RB_AFRPOINTS                40321
#define IDS_AFR_FALLOFF                 40322
#define IDS_AFR_PINCH                   40323
#define IDS_AFR_BUBBLE                  40324
#define IDS_RB_TESSMOD                  40325
#define IDS_TESS_TENSION                40326
#define IDS_RB_DELETEMOD                40327
#define IDS_RB_MESHSELMOD               40328
#define IDS_RB_FACEEXTRUDEMOD           40329
#define IDS_RB_EXTRUDECENT              40330
#define IDS_EXT_AMOUNT                  40331
#define IDS_EXT_SCALE                   40332
#define IDS_RB_UVWXFORMMOD              40333
#define IDS_RB_UOFFSET                  40334
#define IDS_RB_VOFFSET                  40335
#define IDS_RB_WOFFSET                  40336
#define IDS_RB_MAXEDGE1                 40337
#define IDS_RB_MAXEDGE2                 40338
#define IDS_RB_CENTERPOINT              40339
#define IDS_RB_MIRRORMOD                40340
#define IDS_RB_MIRRORCENTER             40341
#define IDS_RB_OFFSET                   40342
#define IDS_RB_SELVERTEX                40343
#define IDS_RB_SELFACE                  40344
#define IDS_RB_SELEDGE                  40345
#define IDS_RB_SELOBJECT                40346
#define IDS_RB_UNWRAPMOD                40347
#define IDS_AP_SDELETEMOD               40348
#define IDS_RB_RESETUVWS                40349
#define IDS_RB_SETCHANNEL               40350
#define IDS_RB_SHOULDRESET              40351
#define IDS_RB_RESETUNWRAPUVWS          40352
#define IDS_RB_LENGTH                   40353
#define IDS_SA_TRIANGLE                 40354
#define IDS_SA_POLYGON                  40355
#define IDS_SA_TRI_POLY_RESTORE         40356
#define IDS_RB_SPIN                     40357
#define IDS_RB_FALLOFF                  40358
#define IDS_TH_PATCHMTLCHANGE           40359
#define IDS_RB_MOVE                     40360
#define IDS_RB_ROTATE                   40361
#define IDS_RB_PAN                      40362
#define IDS_RB_ZOOM                     40363
#define IDS_RB_PICKMAP                  40364
#define IDS_RB_UPDATE                   40365
#define IDS_RB_ZOOMEXT                  40366
#define IDS_RB_ZOOMREG                  40367
#define IDS_RB_UVW                      40368
#define IDS_RB_PROP                     40369
#define IDS_RB_SHOWMAP                  40370
#define IDS_RB_DEFMODS                  40371
#define SPACEWARPS_FOR_BOTH             40372
#define SPACEWARPS_FOR_PARTICLES        40373
#define SW_TEST                         40374
#define IDS_EM_SELECTION                40375
#define IDS_EM_POLY                     40376
#define IDS_EM_ELEMENT                  40377
#define IDS_EM_OBJECT_SEL               40378
#define IDS_EM_WHICHVERTSEL             40379
#define IDS_EM_WHICHEDGESEL             40380
#define IDS_EM_WHICHFACESEL             40381
#define IDS_EM_EDIT_GEOM                40382
#define IDS_EM_SHAPE                    40383
#define IDS_EM_SELBYCOLOR               40384
#define IDS_EM_VERTEXCOLOR              40385
#define IDS_EM_SETVERTCOLOR             40386
#define IDS_EM_CREATE_MESH              40387
#define IDS_EM_NEWOBJECTNAME            40388
#define IDS_MS_PARAMS                   40389
#define IDS_EM_FACE_DIVIDE              40390
#define IDS_EM_SELECT_OPEN              40391
#define IDS_EM_CREATECURVE              40392
#define IDS_EM_DELETE_ISOVERTS          40393
#define IDS_MS_AFFECTREGION             40394
#define IDS_EM_ALIGN                    40395
#define IDS_EM_VERT_BREAK               40396
#define IDS_EM_SLICE                    40397
#define IDS_EM_CUT                      40398
#define IDS_EM_DETACHFACES              40399
#define IDS_EM_DETACHVERTS              40400
#define IDS_EM_INHERIT_MATERIAL         40401
#define IDS_EM_COMBINE_MATERIALS        40402
#define IDS_EM_NOEDGESSELECTED          40403
#define IDS_UVWX_CHANNEL                40404
#define IDS_UVWX_MAPCHANNEL             40405
#define IDS_UVWX_UFLIP                  40406
#define IDS_UVWX_VFLIP                  40407
#define IDS_UVWX_WFLIP                  40408
#define IDS_EM_FLIP_NORMAL              40409
#define IDS_TH_SPLSEGSEL                40410
#define IDS_TH_NUMSEGSELP               40411
#define IDS_TH_NUMSPLINESEL             40412
#define IDS_TH_NUMSPLINESELP            40413
#define IDS_TH_SPLVERTSEL               40414
#define IDS_TH_SPLINE_VERT_COUNT        40415
#define IDS_TH_SELECTION                40416
#define IDS_TH_OBJECT_SEL               40417
#define IDS_TH_NUMVERTSEL               40418
#define IDS_TH_NUMVERTSELP              40419
#define IDS_TH_GEOMETRY                 40420
#define IDS_TH_MULTIATTACH              40421
#define IDS_TH_NUMEDGESEL               40422
#define IDS_TH_NUMEDGESELP              40423
#define IDS_TH_NUMPATCHSEL              40424
#define IDS_TH_NUMPATCHSELP             40425
#define IDS_MS_USE_AR                   40426
#define IDS_TH_EXPLODE                  40427
#define IDS_TH_DIVIDE_SEGMENT           40428
#define IDS_TH_REVERSE_SPLINE           40429
#define IDS_TH_MULTIPLE_NODES           40430
#define IDS_TH_CROSS_INSERT             40431
#define IDS_TH_CROSS_NOT_IN_THRESHOLD   40432
#define IDS_TH_EDGEDELETE               40433
#define IDS_TH_NOEDGESSEL               40434
#define IDS_TH_SEGMTLCHANGE             40435
#define IDS_CT_DISPAPPROX_CLASS         40436
#define IDS_CT_DISP_APPROX              40437
#define IDS_CT_DISP_APPROX_CHANGE       40438
#define IDS_CT_MESH_MESHER_CLASS        40439
#define IDS_CT_MESH_MESHER              40440
#define IDS_PW_NSPLINE                  40441
#define IDS_EM_CHAMFER                  40442
#define IDS_EM_BREAK                    40445
#define IDS_EM_DIVIDE                   40446
#define IDS_TH_OPEN                     40447
#define IDS_TH_CLOSED                   40448
#define IDS_EM_ATTACH_LIST              40449
#define IDS_EM_DETACH                   40450
#define IDS_VS_MATID                    40451
#define IDS_VS_SMGROUP                  40452
#define IDS_TH_TRIM                     40453
#define IDS_TH_EXTEND                   40454
#define IDS_TH_FILLET                   40455
#define IDS_TH_CHAMFER                  40456
#define IDS_CHANGEWEIGHT                40457
#define IDS_TH_PASTE_NAMED_SEL          40458
#define IDS_TH_SURFACEPROPERTIES        40459
#define IDS_PW_MOVEH                    40460
#define IDS_PW_MOVEV                    40461
#define IDS_PW_SCALEH                   40462
#define IDS_PW_SCALEV                   40463
#define IDS_PW_WELDSELECTED             40464
#define IDS_PW_APPLYPLANAR              40465
#define IDS_PW_FACEMODE                 40466
#define IDS_PW_UVW_VERT_EDIT            40467
#define IDS_PW_UVW_EDIT                 40468
#define IDS_PW_SELECT_UVW               40469
#define IDS_PW_RESET_UNWRAP             40470
#define IDS_PW_SELECTRESTORE            40471
#define IDS_PW_PLANARMAP                40472
#define IDS_PW_POINT                    40473
#define IDS_PW_MOVE_UVW                 40474
#define IDS_PW_ID_ALLID                 40475
#define IDS_PW_UNWRAPVIEW               40476
#define IDS_PW_DELETE_SELECTED          40477
#define IDS_PW_HIDE_SELECTED            40478
#define IDS_PW_UNHIDEALL                40479
#define IDS_PW_FREEZE_SELECTED          40480
#define IDS_PW_UNFREEZEALL              40481
#define IDS_PW_ASSIGN_CONTROLLER        40482
#define IDS_PW_ROTATE_UVW               40483
#define IDS_PW_SCALE_UVW                40484
#define IDS_PW_WELD_UVW                 40485
#define IDS_PW_LINECOLOR                40486
#define IDS_RB_UNSUPPORTED_MAP_TYPE     40487
#define IDS_MM_ACQ_MAPPING              40488
#define IDS_PARAM_CHANGE                40489
#define IDS_PW_UNDO_RESET               40490
#define IDS_PW_UNDO_FIT                 40491
#define IDS_PW_MOUSE_CENTER             40492
#define IDS_PW_MOUSE_ADD                40493
#define IDS_PW_MOUSE_SUBTRACT           40494
#define IDS_PW_MOUSE_CONSTRAIN          40495
#define IDS_PW_MOUSE_SELECTTV           40496
#define IDS_PW_MOUSE_SELECTTRI          40497
#define IDS_PW_MOUSE_SELECTFACE         40498
#define IDS_PW_CYCLE                    40499
#define IDS_PW_FUSE                     40500
#define IDS_PW_AUTOFIT                  40501
#define IDS_PW_BIND                     40502
#define IDS_PW_UNBIND                   40503
#define IDS_PW_SURFACEERROR             40504
#define IDS_PW_VOLDATA                  40505
#define IDS_PW_ERROR                    40506
#define IDS_PW_INSTANCEERROR            40507
#define IDC_STATIC                      -1
#define IDC_EM_SEL_PT_TEXT              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1765
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
