#!/usr/bin/python
# 
# \file directories.py
# \brief Directories configuration
# \date 2010-08-27 17:13GMT
# \author Jan Boon (Kaetemi)
# \date 2001-2005
# \author Nevrax
# Python port of game data build pipeline.
# Directories configuration.
# 
# NeL - MMORPG Framework <http://dev.ryzom.com/projects/nel/>
# Copyright (C) 2010  Winch Gate Property Limited
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 


# *** COMMON PATH ***

CommonName = "sky"
CommonPath = "common/" + CommonName


# *** SOURCE DIRECTORIES IN THE DATABASE ***

# Shape directories
ShapeSourceDirectories = [ ]
ShapeSourceDirectories += [ "sky_v2/max" ]

# Maps directories
MapSourceDirectories = [ ]
MapSourceDirectories += [ "sky_v2/textures/textures" ]

MapUncompressedSourceDirectories = [ ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/textures/desert" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/textures/forest" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/textures/jungle" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/textures/lacustre" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/setup/desert" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/setup/forest" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/setup/jungle" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/setup/lacustre" ]
MapUncompressedSourceDirectories += [ "sky_v2/textures/textures/nodds" ]

# Ig directories
IgLandSourceDirectories = [ ]
IgOtherSourceDirectories = [ ]
IgOtherSourceDirectories += [ "sky_v2/max" ]
IgPrimitiveSourceDirectories = [ ]

# Animation directories
AnimSourceDirectories = [ ]
AnimSourceDirectories += [ "sky_v2/max" ]


# *** EXPORT DIRECTORIES FOR THE BUILD PIPELINE ***

# Shape directories
ShapeTagExportDirectory = CommonPath + "/shape_tag"
ShapeExportDirectory = CommonPath + "/shape"
ShapeWithCoarseMeshExportDirectory = CommonPath + "/shape_with_coarse_mesh"
ShapeLightmapNotOptimizedExportDirectory = CommonPath + "/shape_lightmap_not_optimized"
ShapeAnimExportDirectory = CommonPath + "/shape_anim"

# Ig directories
IgStaticLandExportDirectory = CommonPath + "/ig_static_land" # Landscape IG eported from 3dsmax not elevated by the heightmap
IgStaticOtherExportDirectory = CommonPath + "/ig_static_other" # Village or construction IGs exported from 3dsmax
IgStaticTagExportDirectory = CommonPath + "/ig_static_tag" # Tag for exported 3dsmax files


# *** BUILD DIRECTORIES FOR THE BUILD PIPELINE ***

# Map directories
MapBuildDirectory = CommonPath + "/map"
MapPanoplyBuildDirectory = CommonPath + "/map_panoply"

# Shape directories
ShapeWithCoarseMeshBuildDirectory = CommonPath + "/shape_with_coarse_mesh_builded"
ShapeLightmapBuildDirectory = CommonPath + "/shape_lightmap"
ShapeLightmap16BitsBuildDirectory = CommonPath + "/shape_lightmap_16_bits"

# Ig directories 
IgElevLandPrimBuildDirectory = CommonPath + "/ig_elev_land_prim" # landscape IG generated by the prim exporter (already elevated by the land exporter)
IgElevLandLigoBuildDirectory = CommonPath + "/ig_elev_land_ligo" # Landscape IG found in ligo bricks from 3dsmax elevated by the heightmap
IgElevLandStaticBuildDirectory = CommonPath + "/ig_elev_land_static" # Landscape IG eported from 3dsmax elevated by the heightmap
IgTempLandMergeBuildDirectory = CommonPath + "/ig_temp_land_merge"
IgTempLandCompareBuildDirectory = CommonPath + "/ig_temp_land_compare" # Tmp final IG directory for landscape IGs before comparison
IgLandBuildDirectory = CommonPath + "/ig_land" # Final IG directory for landscape IGs
IgOtherBuildDirectory = CommonPath + "/ig_other" # Final IG directory for village or construction IGs
IgOtherLightedBuildDirectory = CommonPath + "/ig_other_lighted"


# *** INSTALL DIRECTORIES IN THE CLIENT DATA ***

# Map directory
MapClientDirectory = CommonName

# Map directory
BitmapClientDirectory = MapClientDirectory

# Shape directory
ShapeClientDirectory = CommonName

# Lightmap directory
LightmapClientDirectory = CommonName

# Animation directory
AnimClientDirectory = CommonName

# Ig directory
IgClientDirectory = CommonName
