// NeLNS - MMORPG Framework <http://dev.ryzom.com/projects/nel/>
// Copyright (C) 2010  Winch Gate Property Limited
//
// This source file has been modified by the following contributors:
// Copyright (C) 2014  Jan BOON (Kaetemi) <jan.boon@kaetemi.be>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#ifndef NL_LOGIN_SERVICE_H
#define NL_LOGIN_SERVICE_H

// we have to include windows.h because mysql.h uses it but not include it
#ifdef NL_OS_WINDOWS
#	ifndef NL_COMP_MINGW
#		define NOMINMAX
#	endif
#	include <winsock2.h>
#	include <windows.h>
typedef unsigned long ulong;
#endif

#include <memory>
#include <string>
#include <vector>

#include <nel/misc/types_nl.h>
#include <nel/net/service.h>
#include <nel/net/unified_network.h>

#include <nelns/login_service/persistence.h>
#include <nelns/login_service/connection_client.h>
#include <nelns/login_service/connection_ws.h>

// Structures

struct CFrontEnd
{
	CFrontEnd(NLNET::TServiceId sid, bool patching, const std::string& patchingURI) : SId(sid), Patching(patching), PatchURI(patchingURI)	{}

	NLNET::TServiceId	SId;		// Service Id of the frontend on the remote shard
	bool		Patching;	// Is FS in patching mode
	std::string	PatchURI;	// Patch URI
};

struct CShard
{
	CShard (uint32 shardId, NLNET::TServiceId sid) : ShardId(shardId), NbPlayers(0), SId(sid) {}
	
	sint32	ShardId;	// unique shard id generated by the database, used to identify a WS
	uint32	NbPlayers;	// number of player for *this* LS, the total number of player for a shard is in the database
	NLNET::TServiceId	SId;		// unique service id used to identify the connection when a callback happen

	std::vector<CFrontEnd>	FrontEnds;	// frontends on the shard
};


/*
 * disconnectClient is true if we need to disconnect the client on connected on the login system (during the login process)
 * disconnectShard is true if we need to send a message to the shard to disconnect the client from the shard
 */
//void disconnectClient (CUser &user, bool disconnectClient, bool disconnectShard);


class CLoginService : public NLNET::IService
{
public:

	CLoginService();
	explicit CLoginService(std::shared_ptr<IPersistence>&& persistence);

	~CLoginService() override = default;

	/// Init the service, load the universal time.
	void init();

	bool update();

	/// release the service, save the universal time
	void release();

	uint nbPlayers() const
	{
		return m_connection_ws->nbPlayers();
	}

private:
	bool UseDirectClient;
	std::shared_ptr<IPersistence> m_persistence;
	std::unique_ptr<ConnectionClient> m_connection_client;
	std::unique_ptr<ConnectionWS> m_connection_ws;

};

#endif // NL_LOGIN_SERVICE_H

/* End of login_service.h */
