#!/bin/bash

# Trap interrupts and exit instead of continuing the loop
trap "echo Exited!; exit;" SIGINT SIGTERM

cd ~/scripts/

AIS=ais_roots

while true
do
	touch $SHARD_PATH/logs/ai_service_${AIS}.log
	export PYTHONPATH=$PYTHONPATH:$SHARD_PATH/tools
	export PYTHONIOENCODING=UTF-8
	python3 ais_check.py $SHARD_PATH/logs/ai_service_${AIS}.log $AIS $(hostname -s)
done
