name: "NeL Network Services: CI / CD"

on:
  push:
    branches: [ "core4", "feature/*" ]
    paths:
      - .github/workflows/ci-nelns.yml
      - nelns/**
      - CMakeLists.txt
      - CMakePresets.json

  pull_request:
    branches: [ "core4" ]
    paths:
      - .github/workflows/ci-nelns.yml
      - nelns/**
      - CMakeLists.txt
      - CMakePresets.json
  workflow_run:
    workflows: [ "NeL: CI / CD" ]
    types:
      - completed

env:
  DEFAULT_BRANCH: core4
  PROJECT_NAME: nelns
  IMAGE_NAME: ryzomcore-nelns

jobs:
  strings:
    runs-on: ubuntu-latest
    outputs:
      build-dir: ${{ steps.strings.outputs.build-dir }}
      build-output-dir: ${{ steps.strings.outputs.build-output-dir }}
      install-dir: ${{ steps.strings.outputs.install-dir }}
      build-version: ${{ steps.strings.outputs.build-version }}
      docker-image-tag: ${{ steps.strings.outputs.docker-image-tag }}
    steps:
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          BUILD_DIR=${{ github.workspace }}/build
          echo "build-dir=${BUILD_DIR}" >> "$GITHUB_OUTPUT"
          echo "build-output-dir=${BUILD_DIR}/$PROJECT_NAME" >> "$GITHUB_OUTPUT"
          echo "install-dir=${BUILD_DIR}/install" >> "$GITHUB_OUTPUT"
          COMMIT_HASH=${{ github.sha }}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "$DEFAULT_BRANCH" ] && VERSION=latest
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo VERSION=$VERSION
          echo IMAGE_ID=$IMAGE_ID
          echo "build-version=${VERSION}+sha.${COMMIT_HASH:0:8}" >> "$GITHUB_OUTPUT"
          echo "docker-image-tag=${IMAGE_ID}:${VERSION}" >> "$GITHUB_OUTPUT"

  build:
    needs: [ strings ]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        include:
          - os: ubuntu-22.04
          - os: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.29.5"

      - name: Dependencies Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt install --yes \
            build-essential ccache \
            bison autoconf automake \
            libpng-dev \
            libjpeg-dev \
            libgif-dev libfreetype6-dev \
            freeglut3-dev \
            liblua5.2-dev libluabind-dev libcpptest-dev \
            libogg-dev libvorbis-dev libopenal-dev \
            libavcodec-dev libavformat-dev libavdevice-dev libswscale-dev libpostproc-dev \
            libmysqlclient-dev \
            libcurl4-openssl-dev libssl-dev \
            libsquish-dev \
            liblzma-dev \
            libgsf-1-dev \
            qtbase5-dev qttools5-dev qttools5-dev-tools \

      - uses: dawidd6/action-download-artifact@v6
        id: download-from-branch
        with:
          workflow: ci-nel.yml
          workflow_conclusion: success
          branch: "${{ github.ref }}"
          event: push
          name: package-nel-${{ matrix.os }}-.*
          name_is_regexp: true
          path: build
          if_no_artifact_found: ignore

      - uses: dawidd6/action-download-artifact@v6
        if: ${{ steps.download-from-branch.outputs.found_artifact != 'true' }}
        with:
          workflow: ci-nel.yml
          workflow_conclusion: success
          branch: "${{ env.DEFAULT_BRANCH }}"
          event: push
          name: package-nel-${{ matrix.os }}-.*
          name_is_regexp: true
          path: build

      - name: Install Dependency
        run: >
          sh ${{ needs.strings.outputs.build-dir }}/package-nel-*/nel-*.sh
          --skip-license
          --include-subdir
          --prefix=${{ needs.strings.outputs.install-dir }}

      - name: Configure CMake
        if: runner.os == 'Linux'
        run: cmake --preset ci-linux-${{ env.PROJECT_NAME }}

      - name: Build
        run: cmake --build --preset ${{ env.PROJECT_NAME }}

      - name: Test
        run: ctest --preset ${{ env.PROJECT_NAME }}

      - name: Package
        run: cpack --preset ${{ env.PROJECT_NAME }} -R "${{ needs.strings.outputs.build-version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: package-${{ env.PROJECT_NAME }}-${{ matrix.os }}-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-output-dir }}/${{ env.PROJECT_NAME }}-*

  docker:
    runs-on: ubuntu-latest
    needs: [ strings, build ]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: package-${{ env.PROJECT_NAME }}-ubuntu-24.04-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-output-dir }}

      - name: Build the Docker image
        run: |
          docker build . --file nelns/docker/Dockerfile --tag "${{ needs.strings.outputs.docker-image-tag }}"
          docker save --output=${{ needs.strings.outputs.build-output-dir }}/docker-$IMAGE_NAME-${{ needs.strings.outputs.build-version }} "${{ needs.strings.outputs.docker-image-tag }}"

      - uses: actions/upload-artifact@v4
        with:
          name: docker
          path: ${{ needs.strings.outputs.build-output-dir }}/docker-*
          if-no-files-found: error

      - name: Push image
        if: ${{ github.ref == format('refs/heads/{0}', env.DEFAULT_BRANCH) }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push "${{ needs.strings.outputs.docker-image-tag }}"
