name: "Ryzom Core: CI / CD"

on:
  push:
    branches: [ "core4", "feature/*" ]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/workflows/**'
      - '!.github/workflows/ci.yml'

  pull_request:
    branches: [ "core4" ]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/workflows/**'
      - '!.github/workflows/ci.yml'

  workflow_dispatch:

jobs:
  strings:
    runs-on: ubuntu-latest
    outputs:
      build-dir: ${{ steps.strings.outputs.build-dir }}
      install-dir: ${{ steps.strings.outputs.install-dir }}
      build-version: ${{ steps.strings.outputs.build-version }}
      image-version: ${{ steps.strings.outputs.image-version }}
      image-group: ${{ steps.strings.outputs.image-group }}
    steps:
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "install-dir=${{ github.workspace }}/build/install" >> "$GITHUB_OUTPUT"
          COMMIT_HASH=${{ github.sha }}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "${{ github.event.repository.default_branch }}" ] && VERSION=latest
          IMAGE_GROUP=ghcr.io/${{ github.repository_owner }}
          IMAGE_GROUP=$(echo $IMAGE_GROUP | tr '[A-Z]' '[a-z]')
          echo VERSION=$VERSION
          echo IMAGE_GROUP=$IMAGE_GROUP
          echo "build-version=${VERSION}+sha.${COMMIT_HASH:0:8}" >> "$GITHUB_OUTPUT"
          echo "image-version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "image-group=${IMAGE_GROUP}" >> "$GITHUB_OUTPUT"

  nel:
    name: "NeL"
    needs: [ strings ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - id: cache
        uses: actions/cache@v4
        with:
          key: nel-${{ matrix.os }}-${{ hashFiles('nel/**', '.github/nel/**', 'cmake/**', 'CMakeModules/**', 'CMakeLists.txt', 'CMakePresets.json') }}
          path: ${{ needs.strings.outputs.build-dir }}/nel/nel-*

      - uses: ./.github/nel
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          build-dir: ${{ needs.strings.outputs.build-dir }}
          build-version: ${{ needs.strings.outputs.build-version }}
          os: ${{ matrix.os }}

      - uses: actions/upload-artifact@v4
        with:
          name: nel-${{ matrix.os }}-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/nel/nel-*
          if-no-files-found: error


  nelns:
    name: "NeL Network Services"
    needs: [ strings, nel ]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: nel-${{ matrix.os }}-*
          merge-multiple: true
          path: ${{ needs.strings.outputs.build-dir }}

      - id: cache
        uses: actions/cache@v4
        with:
          key: nelns-${{ matrix.os }}-${{ hashFiles('build/nel-*.sh', 'nelns/**', '.github/nelns/**', 'cmake/**', 'CMakeModules/**', 'CMakeLists.txt', 'CMakePresets.json') }}
          path: ${{ needs.strings.outputs.build-dir }}/nelns/nelns-*

      - uses: ./.github/nelns
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          os: ${{ matrix.os }}
          install-dir: ${{ needs.strings.outputs.install-dir }}
          image-group: ${{ needs.strings.outputs.image-group }}
          image-version: ${{ needs.strings.outputs.image-version }}
          build-dir: ${{ needs.strings.outputs.build-dir }}
          build-version: ${{ needs.strings.outputs.build-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: nelns-${{ matrix.os }}-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/nelns/nelns-*
          if-no-files-found: error


  ryzom:
    name: "Ryzom"
    needs: [ strings, nel ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: nel-${{ matrix.os }}-*
          merge-multiple: true
          path: ${{ needs.strings.outputs.build-dir }}

      - id: cache
        uses: actions/cache@v4
        with:
          key: ryzom-${{ matrix.os }}-${{ hashFiles('build/nel-*.sh', 'ryzom/**', '.github/ryzom/**', 'cmake/**', 'CMakeModules/**', 'CMakeLists.txt', 'CMakePresets.json') }}
          path: ${{ needs.strings.outputs.build-dir }}/ryzom/ryzom-*

      - uses: ./.github/ryzom
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          os: ${{ matrix.os }}
          install-dir: ${{ needs.strings.outputs.install-dir }}
          image-group: ${{ needs.strings.outputs.image-group }}
          image-version: ${{ needs.strings.outputs.image-version }}
          build-dir: ${{ needs.strings.outputs.build-dir }}
          build-version: ${{ needs.strings.outputs.build-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: ryzom-${{ matrix.os }}-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/ryzom/ryzom-*
          if-no-files-found: error


  snowballs:
    name: "Snowballs"
    needs: [ strings, nel ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: nel-${{ matrix.os }}-*
          merge-multiple: true
          path: ${{ needs.strings.outputs.build-dir }}

      - id: cache
        uses: actions/cache@v4
        with:
          key: snowballs-${{ matrix.os }}-${{ hashFiles('build/nel-*.sh', 'snowballs2/**', '.github/snowballs/**', 'cmake/**', 'CMakeModules/**', 'CMakeLists.txt', 'CMakePresets.json') }}
          path: ${{ needs.strings.outputs.build-dir }}/snowballs/snowballs-*

      - uses: ./.github/snowballs
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          os: ${{ matrix.os }}
          install-dir: ${{ needs.strings.outputs.install-dir }}
          image-group: ${{ needs.strings.outputs.image-group }}
          image-version: ${{ needs.strings.outputs.image-version }}
          build-dir: ${{ needs.strings.outputs.build-dir }}
          build-version: ${{ needs.strings.outputs.build-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: snowballs-${{ matrix.os }}-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/snowballs/snowballs-*


  studio:
    name: "Studio"
    needs: [ strings, nel ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: nel-${{ matrix.os }}-*
          merge-multiple: true
          path: ${{ needs.strings.outputs.build-dir }}

      - id: cache
        uses: actions/cache@v4
        with:
          key: studio-${{ matrix.os }}-${{ hashFiles('build/nel-*.sh', 'studio/**', '.github/studio/**', 'cmake/**', 'CMakeModules/**', 'CMakeLists.txt', 'CMakePresets.json') }}
          path: ${{ needs.strings.outputs.build-dir }}/studio/studio-*

      - uses: ./.github/studio
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          install-dir: ${{ needs.strings.outputs.install-dir }}
          build-dir: ${{ needs.strings.outputs.build-dir }}
          build-version: ${{ needs.strings.outputs.build-version }}
          os: ${{ matrix.os }}

      - uses: actions/upload-artifact@v4
        with:
          name: studio-${{ matrix.os }}-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/studio/studio-*

  web:
    name: "Web"
    needs: [ strings ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: cache
        uses: actions/cache@v4
        with:
          key: studio-${{ matrix.os }}-${{ hashFiles('web/**', '.github/web/**') }}
          path: ${{ needs.strings.outputs.build-dir }}/web/web-*

      - uses: ./.github/web
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          build-dir: ${{ needs.strings.outputs.build-dir }}
          build-version: ${{ needs.strings.outputs.build-version }}
          image-group: ${{ needs.strings.outputs.image-group }}
          image-version: ${{ needs.strings.outputs.image-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: web-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/web/web-*


  publish:
    needs: [ strings, nelns, snowballs, web ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch ) }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-ubuntu-24.04-*"
          merge-multiple: true
          path: ${{ needs.strings.outputs.build-dir }}

      - uses: actions/download-artifact@v4
        with:
          pattern: "web-docker-*"
          merge-multiple: true
          path: ${{ needs.strings.outputs.build-dir }}

      - run: find ${{ needs.strings.outputs.build-dir }}

      - run: find ${{ needs.strings.outputs.build-dir }} -type f -iname *-docker-*.tar -exec docker load --input {} \;

      - name: Push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker images
          docker push "${{ needs.strings.outputs.image-group }}/ryzomcore-nelns"
          docker push "${{ needs.strings.outputs.image-group }}/ryzomcore-snowballs"
          docker push "${{ needs.strings.outputs.image-group }}/ryzomcore-web"
