name: "Test Report"
on:
  workflow_run:
    workflows: ["CMake on multiple platforms", "Ryzom Core: CI / CD"]
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          name: GTests
          artifact: "/.*test-results/"
          path: '**/*.xml'
          reporter: java-junit